### ISSUE TITLE
关于半透明shader

### ISSUE THREAD

**Issue by fenglyu1314** [candycat1992/Unity_Shaders_Book#10]
我写的半透明shader会出现渲染顺序不对的情况，两个半透明的材质重叠的时候，有时后面的会显示在前面，这个问题困扰了我很久，不知道应该如何解决？
下面是我的代码。

**Comment by fenglyu1314** [comment]
`//描述 : 遮罩透明的suface shader
//作者：CatMya
//时间2016-06-14 16:57:43

//修改时间：2016-06-17 17:21:52
//修改内容：增加第二张纹理贴图，遮罩贴图使用RGB通道（不需要Alpha通道了），RG控制纹理1和2的遮罩，B通道控制整体的透明


Shader"Infinite/terrain/plane_2Texture_mask_alpha" {
	Properties {
		_Edge("Edge",Range (0, 1))=0.5
		_Color ("Main Color", Color) = (1,1,1,1)
		_Tex1 ("Texture1 (RGB)", 2D) = "white" {}
		_Tex2 ("Texture2 (RGB)", 2D) = "white" {}
		_AlphaMask ("AlphaMask(RGB)", 2D) = "white" {}
	}
	SubShader {
		Tags {"Queue"="Transparent" "IgnoreProjector"="True" "RenderType"="TransparentCutout"}
		LOD 200

		CGPROGRAM
		#pragma surface surf Lambert  alpha //noforwardadd

		float _Edge;

		sampler2D _Tex1;
		sampler2D _Tex2;
		sampler2D _AlphaMask;
		fixed4 _Color;

		struct Input {
			float2 uv_AlphaMask;
			float2 uv_Tex1;
			float2 uv_Tex2;
};
		

void surf(Input IN, inout SurfaceOutput o)
{
			fixed4 m = tex2D(_AlphaMask, IN.uv_AlphaMask);
			fixed4 lay1 = tex2D(_Tex1, IN.uv_Tex1);
			fixed3 lay2 = tex2D(_Tex2, IN.uv_Tex2);
			//o.Albedo.rgb = (lay1 * m.r + lay2 * m.g) * _Color;
			o.Alpha = m.b;
	//o.Alpha = lay1.a;
	clip(o.Alpha - 0.3);

	float x = lerp(1, _Edge, smoothstep(0, 0.25, m.r * m.g));
	
	o.Albedo.rgb = (lay1 * m.r + lay2 * m.g * x) * _Color;
}
		ENDCG
	}
	FallBack "Diffuse"
}
`

**Comment by candycat1992** [comment]
首先这是surface shader，不是本书的重点。其次，Fallback写得不规范哦，应该使用半透明的内置shader作为Fallback比较好。

相比于回答你这个问题，你更应该好好看一下本书的第8章，这样你大概就能自己回答这个问题了。简单来说，就是因为半透明关闭了深度写入，导致排序不再是像素级别的，而是逐物体的，这就导致排序很不精确，当模型之间互相穿插的时候就会有问题。解决方法就是尽量不要穿插。

既然买了书，何不先好好看下原理讲解呢？这才是买书的价值啊~
