### ISSUE TITLE
关于第九章延迟渲染的疑问

### ISSUE THREAD

**Issue by Wangsh09** [candycat1992/Unity_Shaders_Book#100]
作者您好~
我对延迟渲染一直没有太理解~看到您第9章关于延迟渲染的介绍，又有两点疑问，想向您请教一下~

1.在您9.1.3关于延迟渲染的伪代码中，写到
writeGBuffer(materialInfo, pos, normal, LightDir, viewDir)
其中传入了参数LightDir，将LightDir存入了GBuffer。
我理解GBuffer中应该没有存入逐像素的光源方向信息，不知是否我理解错误。
如果GBuffer存入了光源方向信息，而且假如某个像素受到多个光源影响，那么存入的应该是哪个光源的光源方向信息呢~

2.关于延迟渲染的流程
如下是我的理解，不知是否正确：
假如场景中有5个物件和3个光源。那么先对该5个物件执行pass1，得到一个GBuffer，然后再对GBuffer执行三遍pass2（每个光源执行一次）。得到最终的结果。
这样的话pass1执行5遍，pass2执行3遍~而前向与渲染的话想得到同样的结果，需要执行5*3=15遍pass。

不知我想的是否正确~谢谢~

**Comment by kalashnikov2986** [comment]
1。GBuffer不存储light的任何信息，light的信息是RenderLighting的时候逐个渲染灯光的时候写入shader寄存器的。
2。pass1叫做RenderBasePass  pass2叫做RenderLighting 还有一个pass3 叫做RenderFinalPass,实际情况要渲染阴影，还要有很多的pass。我觉得你的理解对于延迟着色框架是对的，但是对于unity引擎来说不是这样的，因为这样无法保证shader的多样性，所以我理解其实unity的延迟着色（prepass rendering)还是一个利用了部分延迟着色特性的前向渲染系统。

**Comment by candycat1992** [comment]
你好，
1. 其实这里把lightDir写到参数里只是为了完整性，的确常见的GBuffer里面的信息通常是depth、normal和texture color、roughness等材质属性。这样写的确有一些误导性……会在后面的版本里去掉lightDir和viewDir这两个参数。
2. 简单说来，延迟渲染的基本流程就如你所说，理解基本没问题，所以可以在光源很多的情况下大大节省Pass的数目。

**Comment by Wangsh09** [comment]
好的！明白了~多谢！
