### ISSUE TITLE
关于第九章阴影的问题

### ISSUE THREAD

**Issue by SaberStereo** [candycat1992/Unity_Shaders_Book#101]
作者好，
我在shadow.shader中Base Pass计算diffuse如果使用Half Lambert在Base Pass中计算diffuse，效果在阴影面和光照面的交汇处就会出现错误，但是如果让diffuse不再乘上shadow，效果就正常了，想请教下原因

**Comment by SaberStereo** [comment]
问题出在使用directional light时，如果用自带的函数计算光的衰减，阴影就会出现问题

**Comment by candycat1992** [comment]
不清楚你所说的错误是指什么呢？？可以把图片贴上来么？？

**Comment by SaberStereo** [comment]
好的,这个object的shader用的就是shadow，只是我在计算漫反射时用的是halflambert，然后就会出现这种问题。我也不知道如何解决，就自己试试，法线如果使用自带的函数去计算atten就会出现这个问题..
<img width="375" alt="screenshot" src="https://cloud.githubusercontent.com/assets/20660418/23949927/30208c6c-09c4-11e7-8d0c-beb83b4a003c.png">

**Comment by candycat1992** [comment]
从你的图来看，如果你说的是图里那种锯齿的问题，应该是阴影分辨率等设置的问题，你可以参考[Unity的文档](https://docs.unity3d.com/Manual/ShadowOverview.html)。
