### ISSUE TITLE
这个等式有点颠覆我的逻辑

### ISSUE THREAD

**Issue by yzy1987523** [candycat1992/Unity_Shaders_Book#103]
![image](https://cloud.githubusercontent.com/assets/16916558/23745306/b1238c00-04f2-11e7-833c-e058d9799415.png)
希望可以为我解惑

**Comment by yzy1987523** [comment]
上面的等式是：数组中的每个元素分别加上后面的常数吗？

**Comment by candycat1992** [comment]
你好，这个操作在Cg里叫做[Smearing](http://http.developer.nvidia.com/Cg/Cg_language.html)，它会发生在一个标量和一个多维向量进行运算的时候，此时这个标量会自动转换成和向量相同维数的向量，这个新向量里面的每个分量值都是该标量的值，然后再与原先的向量进行运算。也就是说，这里的o.w会自动转换成float2(o.w, o.w)，再和前面的结果进行相加。
