### ISSUE TITLE
关于第13章脚本中“|=”运算符的问题

### ISSUE THREAD

**Issue by AKA009** [candycat1992/Unity_Shaders_Book#104]
作者您好，我是一名初学者，在阅读269页13.1.2节（获取深度/法线/深度+法线贴图）过程中发现有一个我没有见过的运算符“|=”，出现在如下两处
```
    camera.depthTextureMode |= DepthTextureMode.Depth;
    camera.depthTextureMode |= DepthTextureMode.DepthNormals;
```
可是在您前面的叙述中使用的代码直接使用了“=”来进行赋值
    `camera.depthTextureMode = DepthTextureMode.DepthNormals;`
在您提供的随书素材中，C#脚本Chapter13/MotionBlurWithDepthTexture.cs里使用的代码如下
```
void OnEnable() 
{
    camera.depthTextureMode |= DepthTextureMode.Depth;

    previousViewProjectionMatrix = camera.projectionMatrix * camera.worldToCameraMatrix;
}
```
我在您给出的场景中进行测试，将“|=”改为“=”不会出现问题。所以我对此不是很理解，希望作者您能解释一下，谢谢。

**Comment by candycat1992** [comment]
这是一种运算符，表示“或”运算，你可以参考[MSDN的文档](https://msdn.microsoft.com/zh-cn/library/h5f1zzaw.aspx)。具体到这个例子里面，就是说把camera.depthTextureMode设置成包含DepthTextureMode.Depth的状态。这是因为camera.depthTextureMode之前可能已经被设置成了其他状态，如果直接使用"="，那么就会破坏原来的状态设置；如果使用"|="，那么就会在设置新的状态时同时保留原来的状态。

**Comment by AKA009** [comment]
哦，我明白了，感谢您的解答！

**Comment by QiuG8** [comment]
那是等於十進位的3唄?  01 10 做OR運算 = 11 等於十進位的3

看看列舉 DepthTextureMode內沒有 3
