### ISSUE TITLE
请教一下第十章模拟玻璃效果用切线空间下的法线方向来进行偏移的问题

### ISSUE THREAD

**Issue by laijingquan** [candycat1992/Unity_Shaders_Book#107]
fixed4 frag (v2f i) : SV_Target {		
				float3 worldPos = float3(i.TtoW0.w, i.TtoW1.w, i.TtoW2.w);
				fixed3 worldViewDir = normalize(UnityWorldSpaceViewDir(worldPos));
				
				// Get the normal in tangent space
				fixed3 bump = UnpackNormal(tex2D(_BumpMap, i.uv.zw));
				
				// Compute the offset in tangent space
				float2 offset = bump.xy * _Distortion * _RefractionTex_TexelSize.xy;
				i.scrPos.xy = offset * i.scrPos.z + i.scrPos.xy;
				fixed3 refrCol = tex2D(_RefractionTex, i.scrPos.xy/i.scrPos.w).rgb;
				
				// Convert the normal to world space
				bump = normalize(half3(dot(i.TtoW0.xyz, bump), dot(i.TtoW1.xyz, bump), dot(i.TtoW2.xyz, bump)));
				fixed3 reflDir = reflect(-worldViewDir, bump);
				fixed4 texColor = tex2D(_MainTex, i.uv.xy);
				fixed3 reflCol = texCUBE(_Cubemap, reflDir).rgb * texColor.rgb;
				
				fixed3 finalColor = reflCol * (1 - _RefractAmount) + refrCol * _RefractAmount;
				
				return fixed4(finalColor, 1);
			}
下面有这么一段话：”在这里，我们选择使用切线空间下的法线方向来进行偏移,是因为该空间下的法线可以反映顶点局部空间下的法线方向”，这句话完全不理解啊,能稍微详细点吗?还有一个疑问是,fixed3 bump = UnpackNormal(tex2D(_BumpMap, i.uv.zw));这句代码之后为什么没有求bump.z?

**Comment by candycat1992** [comment]
你好，关于第一个问题你可以参考[之前的issue：关于模拟折射的问题请教](https://github.com/candycat1992/Unity_Shaders_Book/issues/64)。

第二个问题的话，你可能已经解决了，因为UnpackNormal是内置函数，它在函数里面已经求过z了。
