### ISSUE TITLE
Chapter7-SingleTexture.shader

### ISSUE THREAD

**Issue by zhutaorun** [candycat1992/Unity_Shaders_Book#108]
o.worldNormal = UnityObjectToWorldNormal(v.normal);
UnityObjectToWorldNormal
在5.4.2f上报错了，这个方法被替换成了什么了

**Comment by candycat1992** [comment]
据我所知这个API没有什么变化。这种问题一般自己就可以解决哦，如果你真的解决不了要提问的话，建议把报错信息也贴上来会比较好哦。
