### ISSUE TITLE
P275 坐标转换的疑问

### ISSUE THREAD

**Issue by linyuhe** [candycat1992/Unity_Shaders_Book#109]
片元着色器的代码：
`fixed4 frag(v2f i): SV_Target{
...
// divide by w to get the world position.
float4 worldPos = D / D.w;
...
}`
这个地方有点不理解，为什么要除以D.w呢，NDC下的坐标应该怎么变换到世界坐标系下呢？NDC下的坐标首先应该转换到剪裁空间吧，可是W分量又丢失了？

不是很懂，如果讲解下就更好了。谢谢

**Comment by linyuhe** [comment]
证明过程：http://feepingcreature.github.io/math.html

**Comment by candycat1992** [comment]
所以，你已经自己解决了是么……赞！

**Comment by tantelu** [comment]
感觉矩阵运算真是一个神奇的东西！这种运算时可以携带信息进行传递！
