### ISSUE TITLE
P148页描述错误

### ISSUE THREAD

**Issue by gameboy12615** [candycat1992/Unity_Shaders_Book#110]
>>"如果一个变换中仅存在**平移**和旋转变换，那么这个变换的逆矩阵就等于它的转置矩阵"这句有误。
===========================================================
有平移不能直接转置。令Matrix4X4的左上角3x3矩阵R为正交矩阵，有Transpose(R) = Inverse(R)。
令T为平移向量。则有：
|R　T|　　　|I   　T|　　　|R　0|
|　　|　=　　|　　|　*　|　　|
|0　1|　　　|0　　1|　　|0　1|
|R　T|-1　|R　0|-1　　|I　T|-1　　|Inverse(R)　0|　　|I　-T|　　|Transpose(R)　-Transpose(R)*T|
|　　|　=　|　　|　*　|　　|　=　|　　　　　　|　*　|　　|=　|　　　　　　　　　　　　　|
|0　1|　　|0　　1|　　|0　1|　　　|0　　　　　1|　　|0　1|　　|0　　　　　　　　　　　　1|
=============================================================
对于左上角R，可以同时存在旋转和镜像（正交矩阵乘以正交矩阵依然是正交矩阵），若存在统一缩放，提取缩放因子S后依然是正交矩阵。
（真不会编辑gitbub，给跪了_(:зゝ∠)_，见谅）

**Comment by candycat1992** [comment]
这个的确有问题，你可以参见[之前issue的讨论](https://github.com/candycat1992/Unity_Shaders_Book/issues/87)。

**Comment by gameboy12615** [comment]
好的 谢谢。
