### ISSUE TITLE
P252 传递自定义数组的问题

### ISSUE THREAD

**Issue by flashsong** [candycat1992/Unity_Shaders_Book#114]
P252 half uv[9] : TEXCOORD0; 这个数组占用了TEXCOORD0-TEXCOORD8吗?还是TEXCOORD0就可以存储9组数据呢? 一个TEXCOORDn不是最多只能存储4个float数据的? 网上查了好久没找到答案,忘老师指导!

**Comment by candycat1992** [comment]
你好，是会分开存储成TEXCOORD0-TEXCOORD8，具体你可以参见[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/74)。
