### ISSUE TITLE
关于十二章GaussianBlur边缘值处理的问题

### ISSUE THREAD

**Issue by ArionTT** [candycat1992/Unity_Shaders_Book#116]
在十二章有讲到高斯模糊处理图片。关于算法中，对图片像素采样时用到了四周的像素值，可是当像素点取到边缘时，那么它周边的像素值又是多少呢？我看普通的C实现高斯模糊，有些会产生非模糊边缘
Unity中是怎么做到的呢？

**Comment by candycat1992** [comment]
这要看图片的Wrap Mode了。第12章里面的屏幕图片默认Wrap Mode是Clamp，所以采样到边界的时候会重复边界像素值。普通的C等编程语言实现的话可能需要自己处理边界条件，一般也是类似Clamp或者补0。
