### ISSUE TITLE
关于矩阵的运算问题

### ISSUE THREAD

**Issue by HTWER** [candycat1992/Unity_Shaders_Book#117]
![image](https://cloud.githubusercontent.com/assets/18010177/25471767/17b5224c-2b5b-11e7-9e94-4211b5f90cad.png)
为什么通过左乘原矩阵就可以得到右乘一个转置矩阵的结果？
就是有一条这样的公式吗: **aTM=MTa** (T代表转置，不太会搞格式= =)

**Comment by candycat1992** [comment]
你在纸上把矩阵按行/按列展开，再手动和矢量相乘看结果就可以知道了。

**Comment by HTWER** [comment]
那就是说存在一条这样的公式咯：**aTM=MTa**（a为行向量，T代表转置，M代表原矩阵）

**Comment by candycat1992** [comment]
你写的那个公式的左边是行向量，右边是列向量，所以严谨写的话应该是：(a^T M)^T = M^T a，a是列向量。其实这就是个恒等式。

**Comment by HTWER** [comment]
好的 谢谢了！之前笔误，现在已经更正！
