### ISSUE TITLE
4.3勘误

### ISSUE THREAD

**Issue by zuijinmi** [candycat1992/Unity_Shaders_Book#12]
4.4.3习题中的5（2） 我算的是12倍根号3 而不是12倍根号2.
第54页 第二行cos60°=1/2=0.5 不应该用≈0.5

**Comment by candycat1992** [comment]
你好，谢谢勘误，这些问题在电子版（http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_chapter_4.pdf）和下一次印刷版都已更正，感谢 :)
