### ISSUE TITLE
P141-7.1.1-(6)

### ISSUE THREAD

**Issue by zhenlinyang** [candycat1992/Unity_Shaders_Book#120]
> 我们需要在 Cg 代码片中声明和上述属性类型相匹配的变量。

这句话中的“声明”改成“定义”是否更合适？

非常感谢！

**Comment by candycat1992** [comment]
这种咬文嚼字的我不是很在行……你可以说下为什么定义更合适么？这里用声明是为了表示需要从其他地方给该值赋值，再传递给Cg代码片的意思，也就是这个变量并不是在Cg代码片内部就定义好的。
