### ISSUE TITLE
可视化副切线的问题

### ISSUE THREAD

**Issue by HTWER** [candycat1992/Unity_Shaders_Book#123]
![image](https://cloud.githubusercontent.com/assets/18010177/25690780/5ff67120-30c7-11e7-9c63-f9c138f80779.png)
问题在图中

**Comment by candycat1992** [comment]
w表示方向，可以是1或者-1，具体你可以参考[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/32)。

**Comment by HTWER** [comment]
我去看了下之前你们的讨论，简单总结一下。就是：
w可以用来修正副切线的方向是吗？

**Comment by candycat1992** [comment]
对，因为可选择的方向有两个。

**Comment by HTWER** [comment]
好的
