### ISSUE TITLE
法线变换推到公式疑问

### ISSUE THREAD

**Issue by matrix09** [candycat1992/Unity_Shaders_Book#124]
![1](https://cloud.githubusercontent.com/assets/7876723/25768843/c851de4e-323e-11e7-9a1f-7ec0edbf66a7.png)

hello，才女童鞋，在第87页，我没有看懂你的推导，
TA . NA = 0， 你推算G的时候，对MA-B . TA做了转置，那么公式的最后是这样的
TA的转置 * （MA-B的转置 * G） * NA = 0
那么我要理解成
TA * NA = TA的转置 * NA。
我的问题是为什么切线向量和切线向量的转置是一样的呢？

**Comment by candycat1992** [comment]
额我大概猜想你是不理解A * B = A^T B这个公式，这个等式左边是把A和B当成向量来对待，所以等式左边是两个向量的的点乘，A点乘B得到一个标量，在这页里面(Ma->b Ta)就是一个向量A，而(GNa)是向量B，它们点乘得到标量0。而等式右边是把A和B当成列矩阵来对待，所以A的转置A^T得到一个行矩阵，它和列矩阵B进行矩阵乘法也会得到一个同样大小的标量。

这和切线不切线没有关系哦。

**Comment by giterwen** [comment]
确实，当时我看这个也很懵逼，还两边同时乘以逆矩阵、转置矩阵。。现在想想向量的话一般是1*n维的或者转置一下，而两个向量当做矩阵相乘，其中一个肯定得转置一下==

**Comment by giterwen** [comment]
而且我想问下关于这个问题下issues/45，o.worldNormal = mul(v.normal, (float3x3)_World2Object);（假设mormal是1x3的）是否可以写成直接写成o.worldNormal = mul( (float3x3)_Object2World，v.normal);（假设mormal是3x1的）。这两个式子等价吧，为什么不这么写呢？

**Comment by candycat1992** [comment]
当然不等价。

o.worldNormal = mul(v.normal, (float3x3)_World2Object); 相当于 (W2O)^T * n，而
o.worldNormal = mul( (float3x3)_Object2World，v.normal); 相当于 O2W * n，。

W2O的转置矩阵不一定是O2W，你再好好想想。

**Comment by giterwen** [comment]
噢，是的，其实就是上面那张图里的，我不能想当然加上_World2Object是正交矩阵(⊙o⊙)。

**Comment by giterwen** [comment]
噢，是的，其实就是上图的式子，我不能想当然加上_World2Object是正交矩阵这个条件(⊙o⊙)。

**Comment by iiRecord** [comment]
![default](https://cloud.githubusercontent.com/assets/3625222/26309435/93cd872e-3f2f-11e7-9faf-ba4ba9fd1740.png)

想问一下这一步怎么计算得到的。为啥突然变成 (Ma-bTa)T (GNa) 为什么突然变成 转置 * (GNa) 了。

**Comment by iiRecord** [comment]
突然明白了。这个和才女刚才解释的是一样的。第一步是两个向量的点击，然后变成了矩阵x向量。

**Comment by helpking** [comment]
> 额我大概猜想你是不理解A * B = A^T B这个公式，这个等式左边是把A和B当成向量来对待，所以等式左边是两个向量的的点乘，A点乘B得到一个标量，在这页里面(Ma->b Ta)就是一个向量A，而(GNa)是向量B，它们点乘得到标量0。而等式右边是把A和B当成列矩阵来对待，所以A的转置A^T得到一个行矩阵，它和列矩阵B进行矩阵乘法也会得到一个同样大小的标量。
> 
> 这和切线不切线没有关系哦。

我有个疑问：
线性代数不是太好，说的不对的还请见谅。
向量点积：A * B 结果是一个标量。结果是个实数。
矩阵相乘：既把A和B当成列矩阵来对待的话，结果按理解上不是一个矩阵（1x1）吗？
虽然两个结果实际的数字上是一样的，但是几何意义不一样，可以这么操作吗？
