### ISSUE TITLE
4.6.2模型空间的左右手坐标系问题

### ISSUE THREAD

**Issue by Giresharu** [candycat1992/Unity_Shaders_Book#125]
模型空间和世界空间都是左手坐标系，为什么在4.6.5中 使用的是右手坐标系的y轴旋转矩阵呢？

**Comment by xiangwei71** [comment]
作者只是用row major的矩陣來解說，這跟右手左手沒有關系喔

**Comment by xiangwei71** [comment]
看來是不小心夾了個row major的y軸旋轉

**Comment by candycat1992** [comment]
你是指P74的旋转矩阵吗？左右手坐标系对旋转矩阵没有影响，它们不同的仅仅在于旋转正方向的定义不同。

**Comment by xiangwei71** [comment]
書上那個TRS是colume major，R是Y軸旋轉

colume major的Y軸旋轉矩陣是
cos(theda) 0 -sin(theda) 
      0          1        0
sin(theda) 0   cos(theda)

書上不小心寫成transpose的版本，板主可能是指這個

**Comment by candycat1992** [comment]
@xiangwei71 colume major和书上写的一致，并没有写反。旋转过后的坐标应该是：

```
x` = cos(theta) x + sin(theta) z
y` = y
z` = -sin(theta) x + cos(theta)z 
```

你是在哪里看到你所说的版本呢？

**Comment by xiangwei71** [comment]
那個.. 看來又是我不小心搞錯了

////////////////////////
colume major的旋轉旋轉不是可以寫成
|X Y Z|

在左手座標下如果繞Y軸轉動
用左手法則，是Z往X才是正轉的方向

因為我犯了1個錯誤
不小心在左手座標下使用了右手法則
所以繞Y軸轉動，看成是X往Z才是正轉的方向
所以我計算出來的結果
x軸：(cos(theda),0,sin(theda))=(x,y,z);  (這裡我是用極座標的想法思考的，假設這個向量在第1象限)
z軸：(-sin(theda),0,cos(theda))=(x,y,z); (所以和上面正的的向量會在第2象限)
tanspose之後就得到

```
cos(theda) 0 -sin(theda) 
     0      1        0
sin(theda) 0   cos(theda)
```
這個繞y軸轉負theda的版本

///////
最後把-theda代入，或是直接transpose才會是正確的版本
(也就是妳書上的版本)

喔喔這麼說來
樓主也許不小心跟我犯了同的錯..
