### ISSUE TITLE
关于边缘检测涉及的数学

### ISSUE THREAD

**Issue by laijingquan** [candycat1992/Unity_Shaders_Book#127]
想在这里请教一下 关于12.3边缘检测用到的卷积，边缘检测算子，滤波等这些数学知识应该去看哪本数学啊，想了解一下原理，但又找不到合适的资料，作者能提供个方向吗？

**Comment by candycat1992** [comment]
这属于图像处理的基础知识，这有很多方向都可以搜到，比如图像处理的书籍等。网上很多链接也都有资料，比如[Kernel_(image_processing)的wiki](https://en.wikipedia.org/wiki/Kernel_(image_processing))。
