### ISSUE TITLE
谢谢candy。。。。

### ISSUE THREAD

**Issue by GITHUB243884919** [candycat1992/Unity_Shaders_Book#128]
首先得感谢下candy，然后想说的是书确实是本好书！我觉得第二版应该增加一些项目中实际用到效果的例子。个人认为shader是游戏开发中属于深水区，一般人很难上手，但是第一版已经写的很好了，能很好帮助入门。就学习路径来说，应该是看一些实际的例子更有帮助。并且这些例子是非学术性的，而是游戏项目中实际用的。

**Comment by candycat1992** [comment]
感谢你的支持，书中其实有很多不足，每次看到读者对书的肯定总是喜悲交加。这本书的目的主要是，“师傅领进门”，后面的修炼就要考验大家自己的学习能力了。如果有时间和能力的话，可能会在后面的版本里更新一些新的例子。（但我是懒癌患者
