### ISSUE TITLE
第6章提到的逐顶点光照漫反射例子是否不正确呢？

### ISSUE THREAD

**Issue by yixiaoqingyuz** [candycat1992/Unity_Shaders_Book#129]
具体表现在当给对应的材质设置一个纯红色的时候，假如把环境光的颜色设为纯白色，则整个物体表现出来的颜色都是白色的，这和系统自带的顶点光照shader不一样，系统自带的会变成无明暗的纯红，感觉这才是正确的

**Comment by candycat1992** [comment]
你可以把环境光乘以材质颜色_Diffuse.rgb就可以得到类似的效果，也就是用下面的代码替换一下：

```
o.color = ambient * _Diffuse.rgb + diffuse;
```

Unity内置的Shader也是用了类似的方法，用间接光照乘以了材质颜色。

**Comment by yixiaoqingyuz** [comment]
感谢回复！

官方文档上的例子里获取环境光用的是这个代码：
o.ambient = ShadeSH9(half4(worldNormal,1));

和颜色混合用的是这两行代码： 
fixed3 lighting = i.diff * shadow + i.ambient;
col.rgb *= lighting;

我已经试过了，这可以获得和内置Shader一样的效果。

**Comment by candycat1992** [comment]
我们俩的方法本质是一样的，书上的例子只是直接使用了UNITY_LIGHTMODEL_AMBIENT来作为环境光，而文档上的例子是使用ShadeSH9去取。你如果只是把环境光的计算使用ShadeSH9去代替的话，在本书的这个例子里其实是没有任何变化的：

```
// Get ambient term
fixed3 ambient = UNITY_LIGHTMODEL_AMBIENT.xyz;
ambient = ShadeSH9(half4(worldNormal, 1)); // Use ShadeSH9 to replace UNITY_LIGHTMODEL_AMBIENT
```

你可以去UnityCG.cginc里看ShadeSH9的实现，它主要的一步是使用内置参数unity_SHAr、unity_SHAg、unity_SHAb去计算SH光照：
```
// normal should be normalized, w=1.0
half3 SHEvalLinearL0L1 (half4 normal)
{
	half3 x;

	// Linear (L1) + constant (L0) polynomial terms
	x.r = dot(unity_SHAr,normal);
	x.g = dot(unity_SHAg,normal);
	x.b = dot(unity_SHAb,normal);

	return x;
}
```

而在本书例子这种只有一个主光源、且Environment Lighting只取固定的颜色的情况来说，和直接取UNITY_LIGHTMODEL_AMBIENT是一样的效果，Unity只是把固定环境光颜色的RGB分别放到了unity_SHAr、unity_SHAg、unity_SHAb的第四个分量而已。

你之所以会得到基本和内置Shader一样的效果，是因为你进行了col.rgb * i.ambient的计算，也就是和我之前的答案提到的那样，把环境光乘以了材质颜色。

当然，如果你的Environment Lighting设置成其他的选项，比如有天空盒或者是Gradient Color的话，用ShadeSH9来计算环境光效果当然更好。书里这么写是考虑到学习曲线的问题，不想在这种时候牵扯这些比较复杂的计算。

**Comment by yixiaoqingyuz** [comment]
确实如你所说，获取环境光的方式本质是一样的。
不一样的是材质颜色和光照混合的计算方式，我没有记错的话，你的书上应该是材质颜色和方向光混合后的结果去和环境光做加法，而Unity官方文档上的计算方式是方向光和环境光相加后的结果再乘以材质颜色。

我贴一下官方文档上的例子：

Shader "Lit/Diffuse With Ambient"
{
    Properties
    {
        [NoScaleOffset] _MainTex ("Texture", 2D) = "white" {}
    }
    SubShader
    {
        Pass
        {
            Tags {"LightMode"="ForwardBase"}
        
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "UnityCG.cginc"
            #include "UnityLightingCommon.cginc"

            struct v2f
            {
                float2 uv : TEXCOORD0;
                fixed4 diff : COLOR0;
                float4 vertex : SV_POSITION;
            };

            v2f vert (appdata_base v)
            {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
                o.uv = v.texcoord;
                half3 worldNormal = UnityObjectToWorldNormal(v.normal);
                half nl = max(0, dot(worldNormal, _WorldSpaceLightPos0.xyz));
                o.diff = nl * _LightColor0;

                // the only difference from previous shader:
                // in addition to the diffuse lighting from the main light,
                // add illumination from ambient or light probes
                // ShadeSH9 function from UnityCG.cginc evaluates it,
                // using world space normal
                o.diff.rgb += ShadeSH9(half4(worldNormal,1));
                return o;
            }
            
            sampler2D _MainTex;

            fixed4 frag (v2f i) : SV_Target
            {
                fixed4 col = tex2D(_MainTex, i.uv);
                col *= i.diff;
                return col;
            }
            ENDCG
        }
    }
}

**Comment by candycat1992** [comment]
我明白你的意思，这两种都是经验模型。所以，你是想建议我用这种方法算环境光是吗？

**Comment by yixiaoqingyuz** [comment]
好像是的，因为这种计算方式的结果和Unity内置的其他shader的结果是一致的，更符合用户的预期吧。
当然，我只是提一下，并没有别的意思，你如果觉得没有必要可以直接关掉这个issue

**Comment by candycat1992** [comment]
我知道~书上那么写完全是为了按照一开始介绍的Phong模型去写的。其实我当时写的时候大概是Unity 4到5的过渡时期，当时Unity内置的Shader和书里现在这种写法是一样的，后来5.x版本逐渐变成了现在这种计算。这两种都不是物理精确的，我个人感觉完全按自己喜好选择就好，这种加加减减乘乘除除的，你觉得怎么好看怎么来就好（我指的是在经验模型下）。如果书有后续版本的话，会考虑更新到这种计算，感谢建议~
