### ISSUE TITLE
关于4.6 坐标空间有两个问题

### ISSUE THREAD

**Issue by CaigerDeng** [candycat1992/Unity_Shaders_Book#13]
1. 在第67页中间，讲到在Unity里的旋转顺序是zxy，得到的组合变换矩阵是MzMxMy = [...][...][...]，没有看懂对于公式书写顺序的解释。
    下面解释怎么从zyx顺序开始的？
    我理解“旋转顺序颠倒一下，它们得到的结果就会是一样的”，但这和上面的公式的书写顺序有什么关系呢？我被绕晕了。

    2. 在第69页里，讲确定在父坐标空间下的位置Ap，步骤2开始就没看懂，这里的“x轴”是说子空间还是父空间的？
    步骤2里的Oc+axc，a为什么要乘xc呢？这是一个比例吗？

**Comment by candycat1992** [comment]
1. 因为本书使用的是列矩阵，采取右乘的方法，因此阅读顺序是从右往左读，书里讲到Unity里的旋转顺序是zxy，但公式是MzMxMy，按照之前的阅读顺序实际是yxz，是反的，所以下面解释了一段为什么看起来是反的。

2. 空间变换是比较搞脑子，需要你自己好好体会下。这里的x轴（xc）指的是子空间的x轴在父空间下的表示，a是子空间里面该点的x分量值，a乘以xc就意味着沿着x轴平移了a的单位，这就是坐标的意义呀。建议再反复阅读下~

**Comment by CaigerDeng** [comment]
1. 那就是说在书里，在讲到前面列矩阵的时候，都是整个坐标轴一块旋转，但这到了Unity里，并不转动坐标轴，所以写成MzMxMy的样子对吧？
2. 空间转换我再想想，感谢解答。

**Comment by candycat1992** [comment]
这里是因为旋转矩阵本身就是复合变换，书里这么写是因为Unity文档里写得顺序和书里看起来不符合，因此才会有这么一段来特此说明哈

**Comment by adachigit** [comment]
第二个问题中，子空间的三个坐标轴在父空间下的表示，应该必须是单位向量吧。

**Comment by candycat1992** [comment]
空间的坐标轴不需要是单位向量，如果子空间进行了缩放显然就不是单位向量了，也不需要是单位向量~子空间的坐标轴在父空间下的表示就表明了子空间坐标轴的单位是多少，不需要是1。

**Comment by adachigit** [comment]
明白了，确实是可以允许缩放的，多谢多谢。：）

**Comment by CaigerDeng** [comment]
我现在又回头看到这里了，还是没有搞清楚第一个问题。
因为列矩阵，需要右乘，明白。
对于坐标系的两种选择，明白。
“说得明白点，在第一种情况下，按zxy顺序旋转和在第二种情况下，按yxz的旋转顺序是一样的”，这一句是我能找到的和前面按书上前面说法顺序是yxz的唯一有联系的地方了。
为什么最终顺序是MzMxMy，还是不明白，感觉就直接给我结论了。这里是抛弃了前面的列矩阵右乘的说法吗？

**Comment by candycat1992** [comment]
其实是这样的，因为[Unity官方文档](https://docs.unity3d.com/ScriptReference/Transform.Rotate.html)里面写的是：

> Transform.Rotate: Applies a rotation of eulerAngles.z degrees around the z axis, eulerAngles.x degrees around the x axis, and eulerAngles.y degrees around the y axis (in that order).

也就是说文档里面写的是，旋转顺序为ZXY，它这个阅读顺序是从左往右读的，这和书里一直遵循的顺序是反的，我当时是担心读者在看文档的时候产生困惑，所以书里解释了一下。

换句话说，文档里写的“旋转顺序是ZXY”是从左往右读矩阵的，但其实我们都是用的列矩阵，因此阅读顺序按理应该是从右往左，所以如果是按照书里面的惯例来说，Unity的旋转顺序是“YXZ”，书上这么写仅仅是为了和文档里的文字配合来解释。不知道你这次明白了没…

**Comment by ArcherLew** [comment]
乐乐真是好耐心！赞！
