### ISSUE TITLE
第二章模板测试（StenCil Test）的疑惑

### ISSUE THREAD

**Issue by GITHUB243884919** [candycat1992/Unity_Shaders_Book#130]
hi，candy，P15的流程图看起来很简单，尤其是不通过后就舍弃片元。但Unity对于如何使用的定义，貌似还比较复杂。感觉不是很好理解。尤其是Fail和ZFail。都舍弃了还有Fail操作干嘛？Stencil Test是在Depth Test之前的，为什么还会有ZFail。还有看到很多UI的例子上写的 Comp[_StencilComp]而_StencilComp=8，这个8导致指什么呢？官方文档一共定义了Greater	，GEqual，	Less，LEqual，Equal，NotEqual，Always	Never，一共8种。不是从0开始计数的吗？最后一个Never是7，那这个8到底指的什么呢？

**Comment by candycat1992** [comment]
P14、15、16的流程图是非常简化后的版本。Stencil Test的确发生在Depth Test之前，所以如果Stencil Test本身没有通过的话，这个片元会直接舍弃，不会再进行Depth Test。但模板缓冲的更新操作却不是在Stencil Test完成后立刻执行的，P15的图的确有误导性。Stencil Buffer的更新是可以根据Stencil Test和Depth Test的结果来决定的。

8代表的是Always的操作，官方目前定义了9种，你可以在[文档](https://docs.unity3d.com/ScriptReference/Rendering.CompareFunction.html)里找到。个人感觉，最好还是不要直接写数字，还是在脚本里通过[UnityEngine.Rendering.CompareFunction](https://docs.unity3d.com/ScriptReference/Rendering.CompareFunction.html)来设定比较好。

**Comment by GITHUB243884919** [comment]
哦，了解啦。说到这个8的问题，是不是官方的文档有个bug。你给的链接确实是定义了9种，但是我之前看的链接上确实只有我上面说的8种。[这里](https://docs.unity3d.com/Manual/SL-Stencil.html )

**Comment by candycat1992** [comment]
你可以对比下两个链接里的种类就知道了，没有bug。
