### ISSUE TITLE
7.2.3实践部分（9）定义顶点着色器。我的在P150

### ISSUE THREAD

**Issue by tantelu** [candycat1992/Unity_Shaders_Book#131]
这里构建rotation为什么没有全部归一化？
float3x3 rotation=float3x3(v.tangent.xyz,bitangent,v.normal);
主切线和法线没有做归一化处理，还是说它们导入进来就本身就是单位向量？ 但是上面一句求叉积的时候又做了归一化，说明导入进来的时候并不是单位向量。
 float3 bitangent=cross(normalize(v.normal),normalize(v.tangent.xyz))*v.tangent.w;

**Comment by candycat1992** [comment]
这里的确假定tangent和normal在传递给vertex shader的时候已经归一化了。这两个方向可以是在建模软件里导出的，也可以是在Unity的模型导入面板里设置成让Unity自己算。如果是从建模软件直接导出的数据的话的确有可能不是归一化的，但是一般大家的共识都是要归一化的向量，所以这里没有对tangent和normal再进行归一化操作。至于bitangent的计算在代码里归一化了，恩，这纯碎是我自己的习惯 - -|||
