### ISSUE TITLE
275页从NDC到世界空间的一些疑惑

### ISSUE THREAD

**Issue by klkucan** [candycat1992/Unity_Shaders_Book#132]
代码中：float4 H = float4(i.uv.x * 2 - 1, i.uv.y * 2 - 1, d * 2 - 1, 1);我能理解是获得NDC中的坐标，但是裁剪空间到NDC是经过齐次除法的，不过因为w已经无法得到了，所以才直接把H当做裁剪空间的坐标用来计算世界坐标的吗？如果是，那么计算出来的结果是否正确呢？还有为何要在世界坐标的结果上除以W，这个能详细解释下吗？

感谢

**Comment by candycat1992** [comment]
这个问题之前[有读者给出过完整证明的链接](https://github.com/candycat1992/Unity_Shaders_Book/issues/109)，你可以看看。

**Comment by klkucan** [comment]
@candycat1992  感谢，看来下文章，确实说的很明白。
