### ISSUE TITLE
法线纹理一节152页，变换矩阵的插值问题？

### ISSUE THREAD

**Issue by Rubiphisto** [candycat1992/Unity_Shaders_Book#133]
在第152页里定义了结构体
```
struct v2f
{
	float4 pos : SV_POSITION;
	float4 uv : TEXCOORD0;
	float4 TtoW0 : TEXCOORD1;  
	float4 TtoW1 : TEXCOORD2;  
	float4 TtoW2 : TEXCOORD3;
}
```
但我理解texcoord是插值寄存器，在从顶点着色器传到片元着色器后，存储在 texcoord1-3中的值不是会被插值吗？那这样这个变换矩阵的值就不会是顶点着色器中的值，这样还能进行正常的矩阵变换吗？
同样的疑惑也存在于顶点着色器传送 worldPos 给片地着色器的地方，烦请指教

**Comment by candycat1992** [comment]
的确会被插值。对单位向量的插值的确会有问题，但如果模型的三角面片细分足够，相邻顶点的向量差别不会过大，就算不是数学正确的，绝大多数人也无法分辨出来。

对位置的插值则是数学正确的，所以，理论上在计算世界空间下的light dir和view dir的时候，应该在fragment shader里通过正确插值后的worldpos来得到。如果是在vertex shader里直接算这些单位向量的话，在模型细分程度不够的情况下就会出现比较明显的问题。

你可以参考下面几篇文章：
http://candycat1992.github.io/2016/05/05/graphic-hardware-1/
https://interplayoflight.wordpress.com/2013/05/17/correctly-interpolating-viewlight-vectors-on-large-triangles/

**Comment by Rubiphisto** [comment]
多谢，帮助很多：）
