### ISSUE TITLE
Cg教程地址失效

### ISSUE THREAD

**Issue by awin2001** [candycat1992/Unity_Shaders_Book#134]
http://http.developer.nvidia.com/CgTutorial/cg_tutorial_chapter01.html
这个网址无法打开。冯先生有备份可以共享吗？

**Comment by awin2001** [comment]
http://http.developer.nvidia.com/CgTutorial/cg_tutorial_chapter01.html
这个网址无法打开。冯先生有备份可以共享吗？

**Comment by candycat1992** [comment]
额我也没有。最近nVidia更新了他们的一些链接，导致原来的失效了，不知道过一阵子会不会修复。你可以去网上直接搜，应该是有的，找到了可以来共享(•̀ω•́)✧
