### ISSUE TITLE
8.1章的深度写入的关闭

### ISSUE THREAD

**Issue by Giresharu** [candycat1992/Unity_Shaders_Book#135]
书上写的原因是因为深度测试会导致看不到后面的物体，那为什么关闭的是深度写入呢？

**Comment by candycat1992** [comment]
你可以参考[知乎上Milo Yip的回答](https://www.zhihu.com/question/60898307/answer/182508073)：

'''
对于不透明（opaque）的 fragment，最后只需要看到最接近视点的 fragment。在实时渲染一般是通过深度缓冲来取得这个最近的 fragment。

但对于半透明的 fragment，每一个都会影响最终的结果，需要从远至近地渲染。由于深度缓冲不能用于排序多个 fragment，所以只能用于保存最接近视点的不透明 fragment 深度，远于该深度的透明 fragment 不用渲染，所以仍需要深度测试（depth test）。

由于需要手动排序半透明的物体，写入深度已没有意义。如果能完美地手工排序不透明 fragment，写入深度也没有影响；但若物体在深度方向有重叠，有些 fragment 的顺序会有误，如果开启深度写入，会令到渲染错误很明显，而关掉的话影响较小一点。

当然理想的话，应该用顺序无关透明（order independent transparency, OIT）技术，例如用逐像素链表存储多个 fragment，以像素为单位排序渲染。
'''
