### ISSUE TITLE
P83不等式疑似错误

### ISSUE THREAD

**Issue by awin2001** [candycat1992/Unity_Shaders_Book#136]
与w比较的不等式中的第二个，好像写错了，现在是-w<=x<=y， 应该是-w<=y<=w吧？

**Comment by candycat1992** [comment]
你好，的确是写错了，已经更新到了[勘误列表](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)，非常感谢 :)
