### ISSUE TITLE
关于4.6.6节观察空间的疑惑

### ISSUE THREAD

**Issue by findstr** [candycat1992/Unity_Shaders_Book#138]
我使用4.6.6~4.6.7分别给出的观察空间和裁剪空间的公式来计算unity_Matrix_VP值时发现，与FrameDebugger上显示的unity_Matrix_VP的值不太一样。代码如下：

        Matrix4x4 V = camera1.worldToCameraMatrix;
        Matrix4x4 P = camera1.projectionMatrix;
        var N = new Matrix4x4();
        N.SetRow(0, new Vector4(1.0f, 0.0f, 0.0f, 0.0f));
        N.SetRow(1, new Vector4(0.0f, 1.0f, 0.0f, 0.0f));
        N.SetRow(2, new Vector4(0.0f, 0.0f, -1.0f, 0.0f));
        N.SetRow(3, new Vector4(0f, 0f, 0f, 0f));
        Debug.Log("testCamera");
        Debug.Log(N);
        Debug.Log(P * N * V);`

上述代码得到的结果是：

        0.97384    -0.02902    0.00304    3.04939
        0.05073    1.72168    0.18231    179.67620
        0.00624    0.10518    -0.99504    -990.16710
        0.00623    0.10512    -0.99444    -989.57320`

而FrameDebugger上显示与上面结果不太一样。

![khuog](https://user-images.githubusercontent.com/6435010/27215420-b682994e-52a3-11e7-8be0-cf4331f4c482.png)

**Comment by candycat1992** [comment]
你好，首先我看到你自己计算了一个矩阵N，应该是想要自己翻转z轴。这个是不需要的，因为本身camera.worldToCameraMatrix就已经翻转过坐标空间了。

然后是和shader中不一致的问题。Unity在脚本（C#）端的各个矩阵是遵循OpenGL传统的。因此如果按camera.projectionMatrix * camera.worldToCameraMatrix这么来计算VP矩阵的话，你可以得到符合OpenGL传统的VP转换，也就是NDC坐标范围在[-1, 1]之间。然而，因为各个平台API对传递过来的NDC有不同的标准，因此在shader里面实际的投影矩阵会不同于C#里调用API计算得到的结果。据我个人的实验总结，camera.worldToCameraMatrix是和shader里面的unity_MatrixV一样的，也就是说shader里面的从世界空间到观察空间的变换是符合OpenGL传统的，即是从左手坐标系变换到右手坐标系。而对于投影矩阵则会跟平台相关。如果符合OpenGL传统的平台，那么shader里面的和camera.projectionMatrix是一样的。如果是符合DirectX传统的，就会不一样。不过，无论哪种平台，你都可以通过[GL.GetGPUProjectionMatrix](https://docs.unity3d.com/ScriptReference/GL.GetGPUProjectionMatrix.html)来在脚本中获取到当前平台下传递给shader端的投影矩阵。

总体来说，你之所以得到不一样的结果，是因为你的平台应该是Windows等默认使用DirectX接口的平台。大体来说区别就在于对z分量的转换，OpenGL传统转换后的范围在[-1, 1]，而DirectX传统则是在[0, 1]。并且，Unity 5.5以后，又引入了reverse-z来提高深度缓存的精度，这使得在一些特定的平台下会反转z的转换，使得NDC下的z分量范围是[1, 0]。具体你可以参考[官方文档](https://docs.unity3d.com/Manual/SL-PlatformDifferences.html)。

**Comment by findstr** [comment]
谢谢，果然是这样。

顺便问一下：我之所以这样做，是想在C#中算出一个投影坐标系，然后在shader用我自己算出来的坐标系来达到投影贴花的效果。这样做不知道会不会很低效啊

**Comment by candycat1992** [comment]
如果你只是替换成自己在脚本里算的投影矩阵，然后传递给shader的话，基本不会对性能有什么影响的。

**Comment by findstr** [comment]
好的，谢谢~
