### ISSUE TITLE
从半透明到不透明的做法难点

### ISSUE THREAD

**Issue by JOKULLIU** [candycat1992/Unity_Shaders_Book#14]
作者你好。我现在才看到第八章透明混合。
我们项目有个需求是这样的，舰船进入场景的时候要求是半透明的，等待一定时间后由半透明渐变为不透明。那么半透明"Queue"="Transparent"。但在大部分时间里，舰船都是不透明的。
所以如果采用Transparent的做法，我猜测即便Alpha=1也是比默认的渲染队列要消耗更多资源，因为毕竟还存在Blend命令。
我有个偷懒的办法，就是准备两个材质球，一个是Transparent，一个是Geometry，让负责逻辑的程序自己去置换。
but，有没有一个好的办法可以在一个Shader里面解决呢？

**Comment by candycat1992** [comment]
换材质球的方法你是觉得有什么缺点吗？如果长时间是不透明的话，还是要换到Geometry。除了不同材质球，你也可以试试Material.renderQueue来改变渲染队列

**Comment by JOKULLIU** [comment]
谢谢，我让程序用renderer.shader来置换了。
