### ISSUE TITLE
4.9.3, p91, 倒数第二句话，应该是4.6.8节，不是3.6.8节。

### ISSUE THREAD

**Issue by HellGame** [candycat1992/Unity_Shaders_Book#140]
4.9.3, p91, 倒数第二句话，应该是4.6.8节，不是3.6.8节。

**Comment by candycat1992** [comment]
你好，已经更新到[勘误列表](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)里，感谢勘误 :)
