### ISSUE TITLE
4.6.8节 p83

### ISSUE THREAD

**Issue by HellGame** [candycat1992/Unity_Shaders_Book#141]
齐次除法的定义，是x/w, y/w, z/w这样吗？
如果是的话就不应该是“用齐次坐标系的w分量去除以x、y、z分量”，应该是“用齐次坐标系的w分量去除x、y、z分量” 或者 “用x、y、z分量去除以齐次坐标系的w分量”吧？

**Comment by candycat1992** [comment]
对的，这个是书中的笔误，之前已经更新在了[勘误列表](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)里，感谢反馈。
