### ISSUE TITLE
高光反射计算的问题?

### ISSUE THREAD

**Issue by HTWER** [candycat1992/Unity_Shaders_Book#142]
![image](https://user-images.githubusercontent.com/18010177/27768700-6cf9a7bc-5f4c-11e7-9a4f-561280a62fc4.png)
这里的"*"代表着点乘还是叉乘？好像都不对.....，到底什么？
这条公式我有去了解它的实际意义，但是我回头看代码的时候突然看不懂......

**Comment by candycat1992** [comment]
*就是普通的逐分量乘法，就是a乘以b。点乘和叉乘计算都需要调用单独的API才会计算，点乘是dot，叉乘是cross。

**Comment by HTWER** [comment]
好的 明白了 谢谢
