### ISSUE TITLE
屏幕空间阴影问题

### ISSUE THREAD

**Issue by chenyong2github** [candycat1992/Unity_Shaders_Book#143]
Unity版本5.5.1
Hidden/Internal-ScreenSpaceShadows 里的
struct v2f {
        ...
        // View space ray, for perspective case
	float3 ray : TEXCOORD1;
}
vert里o.ray = v.normal;为什么就能得到view空间下的法线呢？Unity背后做了什么事情？

**Comment by candycat1992** [comment]
你好，

你可以再仔细阅读下这个shader。o.ray的用处主要是为了计算当前屏幕像素在摄像机空间下三维坐标位置，而不是法线。这里涉及的计算和13.3.1节重建世界坐标基本一致。我猜想Unity背后是把该小节中讲到的四个射线值存到的quad四个顶点的法线信息中，而不是像文中那样存储到一个单独的矩阵中。因此，可以直接由顶点的法线信息得到该顶点处对应的射线信息。具体请参考13.3节。
