### ISSUE TITLE
基础光照模型，代码与书上一样 ，效果不一样 

### ISSUE THREAD

**Issue by miccall** [candycat1992/Unity_Shaders_Book#145]
书上的图片效果 ，几乎和unity的标准材质差不多 有空间立体感
我按书上写了以后，几乎就是一张平面图 ？？
本人初入小白 ，希望多多指导一下 @candycat1992

**Comment by candycat1992** [comment]
你好，

如果有问题的话请详细描述问题，并附上相应的材料，例如书的章节、代码、截图。鉴于你目前的问题描述，我无法做出任何有效的回答。感谢对书的支持 :)

**Comment by miccall** [comment]
@candycat1992  
首先先来看我的效果 
![](http://onh0umlhz.bkt.clouddn.com/0721Shader001.PNG)
我用的是第六章第一个代码 Diffuse-Vertex-Level 
下面是代码截图 
![](http://onh0umlhz.bkt.clouddn.com/0721Shader002.PNG)
刚开始觉得效果与书上不同 ，就很奇怪 刚刚clone了您的项目 
也附上相同的材质 效果是这样的
![](http://onh0umlhz.bkt.clouddn.com/0721Shader003.PNG)
我现在还没懂 代码几乎是一样的 效果为什么不一样 ?

**Comment by candycat1992** [comment]
从你的材质缩略图来看shader本身应该没有问题，你可以看看环境光的值是不是很大，以及directional light的intensity是否过大。
