### ISSUE TITLE
关于第10章(10.2.2)玻璃效果折射部分的疑问

### ISSUE THREAD

**Issue by GITHUB243884919** [candycat1992/Unity_Shaders_Book#146]
这个示例中玻璃的折射是是通过对GrabPass { "_RefractionTex" `}的结果进行一定的偏移实现的折射。但这部分代码我不是很明白。
`				
fixed3 bump = UnpackNormal(tex2D(_BumpMap, i.uv.zw));	
float2 offset = bump.xy * _Distortion * _RefractionTex_TexelSize.xy;
				i.scrPos.xy = offset * i.scrPos.z + i.scrPos.xy;
				fixed3 refrCol = tex2D(_RefractionTex, i.scrPos.xy/i.scrPos.w).rgb;`
第一个疑问偏移和bump有什么关系？第二个疑问offset这么算的道理是什么？也就是上面第2,3行。
我尝试用tex2Dproj，不用bump，但貌似结果不对
`
i.scrPos *= _Distortion; 
				fixed3 refrCol = tex2Dproj(_RefractionTex, i.scrPos);`
求指点

**Comment by candycat1992** [comment]
你好，你可以参见之前我回答过的[相关issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/64)。
