### ISSUE TITLE
特定物体的描边

### ISSUE THREAD

**Issue by linyuhe** [candycat1992/Unity_Shaders_Book#147]
13章讲了基于屏幕空间的描边，但是只针对指定物体的描边应该怎么做呢？13章的最后给出了一些提示，但是还是不知道做😅作者能不能详细的说下或者给出一些参考的链接什么的？谢谢~

**Comment by candycat1992** [comment]
基本思路就是只把特定物体渲染到RT中，然后进行描边。你只要谷歌一下就会有很多教程，Unity商店里也有很多这样的插件。

参考链接：
[谷歌搜索](https://www.google.com.hk/search?safe=strict&biw=1920&bih=950&q=unity+outline+selected+object&oq=unity+outline+selected+object&gs_l=psy-ab.3...99625.101779.0.101963.9.8.0.0.0.0.218.218.2-1.1.0....0...1.1j4.64.psy-ab..8.1.218...0i7i30i19k1j0i19k1j0i8i30i19k1.VsMgBL6MogY)
https://willweissman.wordpress.com/tutorials/shaders/unity-shaderlab-object-outlines/
