### ISSUE TITLE
7.1 单张纹理 P142环境光的疑问

### ISSUE THREAD

**Issue by p0e0o0p0l0e0** [candycat1992/Unity_Shaders_Book#148]
P142第二段代码里，先计算材质反射率albedo，为什么在环境光上也要乘以albedo，不应该是只用在漫反射计算中吗？
因为和前面6.5.3的Blinn-Phong光照模型比较，如果把_Diffuse和_Color设置为同一个颜色，如果环境光*albedo，那么第二个胶囊的颜色会比第一个胶囊的颜色深一倍。

**Comment by candycat1992** [comment]
其实乘不乘albedo完全看你自己更喜欢那种效果，这几章都是经验模型，所以自己觉得怎么好看怎么来就好。我也忘记当时为什么只有这里乘了albedo……后面几章为了遵循标准的Phong模型公式，所以都没有乘以albedo。你可以看[之前的一个issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/129)，和你的疑问有点类似。

**Comment by p0e0o0p0l0e0** [comment]
了解了，谢谢~
