### ISSUE TITLE
7.2 反映射法线问题

### ISSUE THREAD

**Issue by p0e0o0p0l0e0** [candycat1992/Unity_Shaders_Book#149]
法线贴图是通过将法线的3个分量分别规范化到[0, 1]中然后按颜色存储的。
P151代码中，从_BumpMap中采样得到的像素值的xy进行反映射，然后再为了得到单位矢量来计算z分量的值。为什么不是对xyz三个分量进行凹凸程度计算，然后再normalize呢？

**Comment by candycat1992** [comment]
因为_BumpMap的xy分量代表了tangent和bitangent轴的偏移量，z代表normal轴的偏移，所以可以在xy分量上乘以凹凸度，相当于向tangent和bitangent所在平面压扁/拉长法线，起到控制凹凸的目的。
如果是：
```
// The codes do nothing
tangentNormal.xyz *= _BumpScale;
tangentNormal.xyz = normalize(tangentNormal.xyz);
```
相当于什么也没有做，因为对矢量所有轴乘以非0数再归一化，和直接归一化没有任何区别。

**Comment by p0e0o0p0l0e0** [comment]
谢谢Candy，我大概了解了，tangent和bitangent分别对应纹理坐标u和v，因为与法线垂直的切线有很多，规定了纹理的u和为作为切线和副切线。BumpMap里存储的颜色值，是新法线在切线空间中的坐标再映射，因此xy对应的uv与BumpScale相乘，可以调整凹凸程度。
现在有另一个问题，代码中的这部分：
`bump.xy *= _BumpScale;
bump.z = sqrt(1.0 - saturate(dot(bump.xy, bump.xy)));`
为什么不直接normalize呢？

**Comment by candycat1992** [comment]
直接normalize会改变我们修改过后的bump.xy，从而改变压扁的程度，这不是我们的意愿。

**Comment by p0e0o0p0l0e0** [comment]
嗯，了解了。谢谢
