### ISSUE TITLE
第70页的勘误

### ISSUE THREAD

**Issue by CaigerDeng** [candycat1992/Unity_Shaders_Book#15]
Ap公式的第一行的第一个矩阵的左下角，多打了一个C。

**Comment by candycat1992** [comment]
是实体书第一版次是吗？方便拍个照片么？电子版（http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_chapter_4.pdf）里好像没有问题

**Comment by CaigerDeng** [comment]
这是第一版第一次印刷，书上的：
第70页的：
![img_20160712_134953](https://cloud.githubusercontent.com/assets/13826934/16756538/7536ebdc-4838-11e6-8094-2a34aecfe383.jpg)
第71页的：
![img_20160712_135127](https://cloud.githubusercontent.com/assets/13826934/16756539/7864cd9c-4838-11e6-8dd5-fbdd06c2c3b8.jpg)

**Comment by candycat1992** [comment]
嗯呢的确是有问题，这个在电子版和第二次印刷里已经修改，非常感谢！
还做了笔记，看得很认真啊
