### ISSUE TITLE
第八章 透明效果 Alpha通道

### ISSUE THREAD

**Issue by p0e0o0p0l0e0** [candycat1992/Unity_Shaders_Book#150]
P162第一段。“当透明度为1时，表示该像素是完全不透明的…………”
Alpha应该代表的是不透明参数，不透明度为1是不透明，不透明度为0是透明的。

**Comment by candycat1992** [comment]
你好，这里直译了Alpha这个单词，虽然你的建议可能更符合逻辑，但我认为alpha channel这个词大家已经有约定俗成的共识了，所以这里还是不打算改了。
