### ISSUE TITLE
关于第四章 空间坐标的疑问 

### ISSUE THREAD

**Issue by FzuLiWei** [candycat1992/Unity_Shaders_Book#151]
感谢作者写了这么好的书，买了你的书，看到第四章 4.6节 ：
在裁剪空间，如果x , y , z 都在w分量的范围里，则说明该顶点在裁剪空间里。

如何理解这句话，为什么会有这个结论？

**Comment by candycat1992** [comment]
你好，定义裁剪矩阵的目的就是为了能够靠这样的不等式方便地判断是否在裁剪空间内。也就是说，我们是为了可以有这样的不等式判断，求出了满足这样条件的裁剪矩阵表达式，而这本书省略了推导过程，所以你问的这个结论原本就是成立的。如果你对推导过程有兴趣，可以参考第四章的扩展阅读部分，或者在网上搜索其他推导材料，有很多的~

**Comment by FzuLiWei** [comment]
好的，感谢
