### ISSUE TITLE
第八章 8.1节 为什么要关闭深度写入？ 我测试后与书中描述的“无法透过半透明表面看到后面的物体”不符

### ISSUE THREAD

**Issue by FzuLiWei** [candycat1992/Unity_Shaders_Book#153]
![1](https://user-images.githubusercontent.com/7477767/29466768-b69c80da-8470-11e7-9f60-5489e5e37d9c.png)
![2](https://user-images.githubusercontent.com/7477767/29466777-ba4960f4-8470-11e7-9a47-6c19e7559f4e.png)
![3](https://user-images.githubusercontent.com/7477767/29466784-bd9249f6-8470-11e7-8b8f-fdd7f8c828b8.png)

**Comment by FzuLiWei** [comment]
图2为蓝色方块shader

**Comment by candycat1992** [comment]
书里的意思是，如果半透明物体开启了深度写入的话，就无法看到在该fragment处后面渲染的fragment，这个主要是为了在半透明物体互相交叉、无法得到正确渲染效果时，我们折中的一种方式。

举个例子，我们来创造一个半透明物体互相交叉的例子：

![qq 20170822191617](https://user-images.githubusercontent.com/5907064/29563078-a13e2a1c-876e-11e7-969d-80772177377a.png)

这两个方块使用的Shader是一样的，但使用了两个各自的材质。为了让效果明显我故意把它们材质的透明度调成不同的值，摄像机靠后的方块透明度较低，靠前的较高。

在不采用其他方法的前提下，如果我们使用书里这种传统的透明混合的方式（指关闭深度写入进行混合）会得到下面的效果：

![qq 20170822190453](https://user-images.githubusercontent.com/5907064/29563177-09825f58-876f-11e7-9e95-7a9c4c1ce360.jpg)

实际上，这种效果是有问题的。错误的地方在于中间两个方块互相重叠的地方，这个混合效果有问题。我们可以在脑海里重现这个渲染过程：首先Unity会基于物体中心对两个方块进行排序，来实现半透明物体的从后往前渲染的目的。所以，Unity会先渲染方块B、再渲染方块A（参见第一张图里面两个方块在摄像机空间下的位置）。然而在重叠区域，正确的渲染顺序应该是先渲染方块A，因为在这部分区域内，它被方块B覆盖住了，它位于后面。出现错误的本质原因是因为我们的排序都是基于object level的，而不是基于pixel level的排序。

如果此时我们把深度打开，则会得到下面的效果：

![qq 20170822190454](https://user-images.githubusercontent.com/5907064/29563341-ad87dc40-876f-11e7-956e-3b2c5613cbf4.jpg)

你可以一眼就看出来这里面的错误，那就是方块A的重叠部分别完全剔除掉了，这部分完全没有渲染！它被剔除掉的 原因就是因为Unity会先渲染方块B，由于方块B进行了深度写入，所以等到方块A渲染的时候，重叠部分A的像素根本无法通过depth test，会直接被剔除掉。

我绝大看到这里你应该知道我们为什么要关闭深度写入。总结一下的话，可以参考[知乎上Milo Yip的回答](https://www.zhihu.com/question/60898307/answer/182508073)：

```
对于不透明（opaque）的 fragment，最后只需要看到最接近视点的 fragment。在实时渲染一般是通过深度缓冲来取得这个最近的 fragment。

但对于半透明的 fragment，每一个都会影响最终的结果，需要从远至近地渲染。由于深度缓冲不能用于排序多个 fragment，所以只能用于保存最接近视点的不透明 fragment 深度，远于该深度的透明 fragment 不用渲染，所以仍需要深度测试（depth test）。

由于需要手动排序半透明的物体，写入深度已没有意义。如果能完美地手工排序不透明 fragment，写入深度也没有影响；但若物体在深度方向有重叠，有些 fragment 的顺序会有误，如果开启深度写入，会令到渲染错误很明显，而关掉的话影响较小一点。

当然理想的话，应该用顺序无关透明（order independent transparency, OIT）技术，例如用逐像素链表存储多个 fragment，以像素为单位排序渲染。
```

**简而言之，就是因为，传统的半透明混合总是会在物体交叉、渲染重叠的情况下，出现错误的混合效果。如果开启深度写入，会令到渲染错误很明显，而关掉的话影响较小一点。**

回到你的图里，由于你的两个方块摆放规则不存在相互重叠，所以Unity对于两个物体的排序在pixel level也是正确的排序，即每个像素也都是满足从后往前渲染的，所以你不会发现问题。

**Comment by FzuLiWei** [comment]
OK明白了

**Comment by FzuLiWei** [comment]
OK明白了

**Comment by zhuolin1995** [comment]
我也有点不理解，即使是按照candy所说的，蓝色物体片元在红色物体前面，那么红色物体的片元应该被舍弃了呀，为什么还是能够被渲染出来

**Comment by lxbhahaha** [comment]
> 我也有点不理解，即使是按照candy所说的，蓝色物体片元在红色物体前面，那么红色物体的片元应该被舍弃了呀，为什么还是能够被渲染出来

按照我的理解，红色方块是不透明的，所以它是先渲染的。所以蓝色方块渲染的时候，它的深入写入也不会导致红色方块被剔除，因为渲染红色方块的时候深度缓存中并没有蓝色方块的深度数据。
而且就算红色也是半透明的，他们也会按照距离摄像头远近的顺序先渲染红色的方块，同理也不会被遮挡。

只有当先渲染蓝色方块再渲染红色方块的时候才会出现剔除的现象，但是由于透明队列里面的物体的排序，一般不会出现这种情况。除非就像Candy例子中的情况，这种情况下才会导致后面的方块被遮挡。

**Comment by TheZoomFlash** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到邮件，尽快给您回复。
