### ISSUE TITLE
9.4.2小节 第202 页中有关描述“顶点着色器的输出结构体v2f必须命名为v”是否有误？

### ISSUE THREAD

**Issue by FzuLiWei** [candycat1992/Unity_Shaders_Book#155]
我看autolight.cginc
#define TRANSFER_SHADOW(a) a._ShadowCoord = mul (unity_WorldToShadow[0], mul(unity_ObjectToWorld,v.vertex));
里应该是描述的是“顶点着器的输入结构体a2f”吧

**Comment by candycat1992** [comment]
这里的确有问题，应该是“顶点着色器的输入结构体a2v”。这处问题之前已经更新到了[勘误列表](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)里，感谢勘误 :)

**Comment by FzuLiWei** [comment]
好的
