### ISSUE TITLE
122页漫反射的解释问题？

### ISSUE THREAD

**Issue by yu-xiaowen** [candycat1992/Unity_Shaders_Book#157]
122页倒数第9行，“而漫反射(diffuse)部分则表示有多少光线会被折射、吸收和散射出表面”这句里的“散射”一词不太好理解，因为上一段提到，“散射”的结果有多种可能，包括折射、反射、重新发射，这一句里的“散射”是指什么呢？

**Comment by candycat1992** [comment]
这里的“散射“需要跟后面的“散射出表面”连在一起理解，指的就是图6.2里面那些首先折射进入物体内部、跟内部颗粒相交后又重新发射出物体表面的部分，这部分光线属于散射的一部分，是“散射出表面”的那部分。
