### ISSUE TITLE
关于第八章颜色混合的疑问

### ISSUE THREAD

**Issue by TableBreaker** [candycat1992/Unity_Shaders_Book#158]
您好，在读第八章的混合因子部分有一点疑问想请教一下，书中说只有两个操作数的混合命令（例如Blend SrcAlpha OneMinusSrcAlpha）混合时会把alpha通道也按照相同公式混合，按照前面的公式假设源颜色a = 0.5，目标颜色a = 1，混合之后则a = 0.75。是表示一个半透明物体和一个不透明物体混合之后也变成了半透明么？ 另一个问题是按照我的理解混合之后的颜色会写入颜色缓存，那么颜色缓存中的alpha通道一般有什么用呢，显示器显示的时候是不需要alpha的吧？

**Comment by candycat1992** [comment]
1. 混合之后的确alpha通道发生了变化，如你所说混合之后a=0.75，这个值会写入frame buffer的alpha通道，但并不是你所说的“表示一个半透明物体和一个不透明物体混合之后也变成了半透明”。只是frame buffer的alpha通道会随alpha blending发生变化，等到下一个半透明物体需要混合的时候，它同样只会使用自身的alpha值进行混合，不会用到frame buffer的alpha通道，因此对后面的半透明渲染没有影响。

2. 通常来说不需要alpha通道进行显示。有一些效果会用到frame buffer里的值，比如[用来说油漆喷射的染色效果](http://forum.china.unity3d.com/thread-25098-1-1.html)，这个就看你想怎么利用了。

**Comment by TableBreaker** [comment]
感謝百忙之中的指點~
