### ISSUE TITLE
关于第11章11.3.2小节数学的疑问

### ISSUE THREAD

**Issue by FzuLiWei** [candycat1992/Unity_Shaders_Book#159]
239页，得到广告牌技术三个基向量后：
float3 localPos = center + rightDir * centerOffs.x + ....
能否解惑下这句是怎么得出来的。

以及，后面写到的，必须是多边形必须是竖直排列，计算中心位置偏移量才会正确，这句话也不是很理解，能否麻烦解惑下。

感谢

**Comment by candycat1992** [comment]
你好，你可以参考之前我回答过的两个issue：[P239页billboard位置变换的相关问题](https://github.com/candycat1992/Unity_Shaders_Book/issues/106)，[P238 对广告牌锚点的疑惑](https://github.com/candycat1992/Unity_Shaders_Book/issues/27)。
