### ISSUE TITLE
第1版第2次印刷 P6勘误

### ISSUE THREAD

**Issue by Ruijie-Qin** [candycat1992/Unity_Shaders_Book#16]
章节 | 页码 | 位置 | 错误文字 | 正确文字
--- | --- | --- | --- | ---
2.1.2 | P6 | 第2段第1行 | 《Render-Time Rendering, Third Editon》 | 《Real-Time Rendering, Third Edition》

**Comment by candycat1992** [comment]
我竟然把圣经名字写错了…………加到勘误里了，感谢！
