### ISSUE TITLE
Question:Color相乘的数学计算定义？ 

### ISSUE THREAD

**Issue by huochilian** [candycat1992/Unity_Shaders_Book#160]
p128 vert()方法体中
fixed3 diffuse = _LightColor0.rgb * _Diffuse.rgb * saturate(dot(worldNormal,worldLight));
求问颜色矢量_LightColor0.rgb * _Diffuse.rgb 相乘的数学定义，猜测如下：
假设颜色 color1 = {r,g,b,a}; color2 = {x,y,z,w};
那么颜色乘 color1*color2 = {r*x, g*y, b*z,a*w};
不知道理解的对不对，或者书中其它地方有过定义，但是我没有找到。

**Comment by candycat1992** [comment]
的确就是各分量相乘的结果，也就是说这个操作是[component-wise](https://en.wikibooks.org/wiki/Cg_Programming/Vector_and_Matrix_Operations#Operators)的。除此之外，其他的二元操作例如/、+、-、*=、+=、/=等等，也是逐分量操作的。这一点书里没有明确定义，我当时写的时候以为这是一个显而易见的操作，因此没有进行说明。不过有好几个读者都问过这个问题，看来书上应该要补上的。
