### ISSUE TITLE
法线存储的问题

### ISSUE THREAD

**Issue by LANYT** [candycat1992/Unity_Shaders_Book#163]
hi，书中讲到法线存储的时候，有说到使用模型空间和切线空间存储时的优点，其中说到：使用切线空间存储的第二个优点是可以进行uv动画，我想问的是，uv动画和法线有什么关系，uv动画不是变化纹理顶点吗，是说要用法线来计算光照吗？望告知，谢谢

**Comment by yqlizeao** [comment]
你好，我也是一名读者，根据你的提问重新去看了下书。作者有说这种UV动画用于水跟火山熔岩，那么势必就有凹凸感，为了产生这种凹凸感，会用到法线进行光影变换，至于为什么会采用法线纹理而不使用高度纹理（感觉差不太多），就是一个通用和复用性。

**Comment by AllenSky** [comment]
我也很好奇这个问题，希望作者详细解释一下，谢谢🙏

**Comment by candycat1992** [comment]
这个优点本质上和书里提到的第一个优点其实是同一个意思。书里提到，切线空间的法线纹理自由度很高，模型空间下的法线纹理通常仅可用于创建该纹理时的那个模型，用到其他的模型上效果就完全错了。比如下面的例子：
![-1](https://user-images.githubusercontent.com/5907064/30804332-a6fa7390-a21f-11e7-8f29-d21a69abc471.jpg)

而切线空间下的法线纹理记录的是相对法线信息，应用到完全不同的模型上也可以得到合理的结果：
![-2](https://user-images.githubusercontent.com/5907064/30804435-0b83971a-a220-11e7-81be-aa3ff7fd76c6.jpg)

 如果你明白了这一点，那UV动画这个也是同样的道理。这里的UV动画指的就是在Shader里变换UV坐标，如果使用模型空间的法线纹理，当UV坐标变换的时候，模型网格和法线信息就会发生错乱了。

**Comment by LANYT** [comment]
@candycat1992 我试着理解一下你的意思你看是否正确？你的意思是不是说：使用切线空间存储的法线纹理即使进行uv动画时模型网格发生变化也不会导致法线信息出错，还可以正常使用来计算后续的光照信息。而使用模型空间的话法线信息就出错了。那我觉得这个优点不应该是说：可进行uv动画，而是进行uv动画也不会影响法线信息，否则我以为是说法线跟uv动画有什么直接的关系，比如用法线计算高度啥的（我瞎说的），不知我我理解是否正确，资质愚钝，望请见谅。

**Comment by yqlizeao** [comment]
实践出真理，不如自己动手操作的试试看。再问乐乐：第二版书啥时候出，想入！

**Comment by candycat1992** [comment]
@LANYT 进行UV动画的时候整体的模型网格不一定会发生变化，你所说的是顶点动画。如果存在UV动画，可以理解成法线纹理会在模型表面流动，所以模型空间的法线就会有问题，因为它存储的是“绝对的法线信息”。而非“相对法线信息”。

**Comment by candycat1992** [comment]
@yqlizeao 第二版啊，默默望天  ￣ω￣=

**Comment by LANYT** [comment]
@candycat1992 谢谢回复
