### ISSUE TITLE
请问7随书资源中，7.2节提供的法线贴图是不是有错？

### ISSUE THREAD

**Issue by bcydl0116** [candycat1992/Unity_Shaders_Book#164]
您好，请问7.2节中提供的normal map是不是有问题？

正常情况下，砖块是突出的，所以在normal map中砖块右侧边缘应当呈现红色。
因为那里的的法线应该偏向右侧，即偏向U方向，也就是切线空间的x轴方向。切换到RGB值的话，就是偏向R值，即偏向红色。

然而在您提供的normal map中，砖块的红色却呈现在左侧（或者说呈现在水泥缝隙的右侧）。

如此一来，当Dump Scale为正值时，水泥缝隙就突出，而砖块却下陷了。为了渲染出正确的效果，我们就不得不将Dump Scale值设为负，这样就有些不合常理了。

**Comment by candycat1992** [comment]
如果是按常理的话，的确是反了。这张图是当时在网上找的免费资源，没怎么关注这块。感谢建议 :)

**Comment by bcydl0116** [comment]
啊，bump写成了dump，好丢人……
感谢你的这本shader入门书，在知乎关注你了。期待你的下一部作品。
