### ISSUE TITLE
unity 中的 viewport space 是啥呀？

### ISSUE THREAD

**Issue by haolly** [candycat1992/Unity_Shaders_Book#167]
今天在看文档的时候发现 Camera.WorldToViewportPoint 这个函数，

> Viewport space is normalized and relative to the camera. The bottom-left of the camera is (0,0); the top-right is (1,1). The z position is in world units from the camera.

看起来有点像是裁剪空间，但又不是，candycat能解释下吗？
是不是可以理解为一个设备无关的坐标系？

**Comment by haolly** [comment]
本来以为是屏幕空间，看了4.9.3 之后发现还是有点不一样，4.9.3 中说 z 分量是和投影类型有关的 😢

**Comment by candycat1992** [comment]
就是4.9.3节所说的视口空间，你可以再仔细看下。Unity的这个函数返回值中的z分量是Unity指定的，广义的视口空间并不会对z分量做特殊规定。
