### ISSUE TITLE
10.2实现Glass效果的章节Github上的源码有错

### ISSUE THREAD

**Issue by ZhangRuFu** [candycat1992/Unity_Shaders_Book#168]
https://github.com/candycat1992/Unity_Shaders_Book/blob/master/Assets/Shaders/Chapter10/Chapter10-GlassRefraction.shader
第81行
i.scrPos.xy = offset * i.scrPos.z + i.scrPos.xy;
这一行应该是offset * i.scrPos.w吧？或者像书中代码直接加上offset（乘上w分量效果更好）

**Comment by candycat1992** [comment]
你好，这里没有错误，你可以参考[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/64)。
