### ISSUE TITLE
关于SV_POSITION语义

### ISSUE THREAD

**Issue by liumazi** [candycat1992/Unity_Shaders_Book#169]
P110 表5.6, 称其为"裁剪空间中的顶点坐标"

似乎在顶点着色器和片元着色器中含义是不同的？
作为顶点着色器的输出时 对应的是gl_Position
作为片元着色器的输入时 对应的是gl_FragCoord
https://msdn.microsoft.com/en-us/library/windows/desktop/bb509647(v=vs.85).aspx#VPOS

测试代码
struct v2f
{
	float2 uv : TEXCOORD0;
	float4 vertex : SV_POSITION;
	float4 test: COLOR; // 只做普通插值没有特殊含义
};

v2f vert(appdata v)
{
	v2f o;
	o.vertex = mul(UNITY_MATRIX_MVP, v.vertex);
	o.test = mul(UNITY_MATRIX_MVP, v.vertex);
	o.uv = v.uv;
	return o;
}

fixed4 frag(v2f i) : SV_Target
{
	return fixed4(i.vertex.x / 1000, i.vertex.y / 400, i.vertex.z, 1);
}
在frag中使用i.vertex和i.test效果是不同的, 其中1000和400是Scene或Game小窗口的尺寸

**Comment by candycat1992** [comment]
因为SV_POSITION是系统语义，是具有特殊含义的，在不同的地方使用它的含义也不同。如果要在fragment shader里直接访问它，它的含义则是屏幕空间的像素位置（有0.5的中心偏移），具体可以参考[MSDN的文档][https://msdn.microsoft.com/en-us/library/windows/desktop/bb509647(v=vs.85).aspx]。所以，如果你用它除以屏幕宽高值，是可以得到在[0, 1]范围内的值的。

如果你直接使用非SV_POSITION语义修饰的顶点值传递到fragment shader，它走的就是普通的插值过程，所以i.test就是是插值后的未经过透视除法的裁剪空间坐标。
