### ISSUE TITLE
4.7 法线变换的疑惑

### ISSUE THREAD

**Issue by CaigerDeng** [candycat1992/Unity_Shaders_Book#17]
在第87页上面，求矩阵G的过程：
![image](https://cloud.githubusercontent.com/assets/13826934/16796092/6055dcec-4913-11e6-8839-38061b7c9a4c.png)
这里红框里的内容，为什么出现了转置矩阵？
我看了原英文版（ http://www.lighthouse3d.com/tutorials/glsl-12-tutorial/the-normal-matrix/ ）里的解释，“因为要乘向量所以要转置”，没有理解。
![image](https://cloud.githubusercontent.com/assets/13826934/16796201/f5ff51ec-4913-11e6-94e6-bf434b2bd191.png)

**Comment by candycat1992** [comment]
你红框框住的那一行的第一个公式是矢量点乘，你可以注意到中间有个黑点。然后为了推导到矩阵里面，因此把矢量运算替换成了等价的矩阵乘法。因为书里面默认矢量可以当成是列矩阵，所以第二个公式就是把它们当成列矩阵进行矩阵乘法。转置是因为矩阵乘法有行列规则，不转置的话这个乘法是没法进行的，不符合矩阵乘法定义。你可以在纸上画一画，第二个那个转置矩阵乘法后也是一个标量，和第一个矢量点乘的结果是相同的。

**Comment by CaigerDeng** [comment]
原来如此，感谢解答。
