### ISSUE TITLE
请问如何在顶点片元Shader里使用Unity的PBR光照模型

### ISSUE THREAD

**Issue by winSwinSHEN** [candycat1992/Unity_Shaders_Book#170]
我既想用Unity里的Standard Shader，又想自定义一些Shader效果，请问女神如何办到？是调用它的函数吗？我看书上的光照模型是自己定义的，但没有PBR的效果好，特此请教下~

**Comment by candycat1992** [comment]
你可以先看一下书的第18章基于物理的渲染，里面有解析Standard Shader的部分。然后可以自己去官网下载built-in shaders的实现，里面有完整的Standard Shader的代码，你只需要在它的基础上改就可以了。

**Comment by winSwinSHEN** [comment]
好吧，看来只能把书看完了- -。
