### ISSUE TITLE
9.1.3 中的所说的前向渲染问题

### ISSUE THREAD

**Issue by haolly** [candycat1992/Unity_Shaders_Book#171]
> 前向渲染的问题是：当场景中包含大量实时光源时，前向渲染的性能会急剧下降。例如，如果我们在场景中的某一块区域放置了多个光源，这些光源影响的区域互相重叠，那么为了得到最终的光照效果，我们就需要为该区域内的每个物体执行**多个 Pass** 来计算不同光源对该物体的光照结果，然后在颜色缓存中把这些结果混合起来得到最终的结果。

根据9.1.1 中所描述的，这里的**多个 Pass ** 是指 每个 shader 中的 Addition Pass (ForwardAdd) 吧？
每个 shader 中的 Base Pass 应该还是只执行一次的吧？

如果一个场景中有两个光源，一个平行光，两个点光源，（举个例子），那么 Base Pass 执行一次，Addition Pass 执行两次？因为 Base Pass 中只能计算平行光？

**Comment by candycat1992** [comment]
对的，Base Pass只会执行一次，Additional Pass可能会执行多遍。需要注意的是，即便场景里只有两个点光源，而没有任何平行光，Base Pass也会走一遍的，只是传进去的光照颜色是黑色而已，所以简单来说，Base Pass是会执行且仅执行一次的（当然前提是当前摄像机可以看见该物体）。

**Comment by haolly** [comment]
嗯，知道了
