### ISSUE TITLE
7.4 Mask Texture 请问Normal可以在世界空间下计算吗

### ISSUE THREAD

**Issue by TechBolun** [candycat1992/Unity_Shaders_Book#172]
如果可以的话 我根据上一节在世界空间计算Normal的方法对MaskTexture进行了改写 但是无法运行

**Comment by TechBolun** [comment]
![2017-10-16](https://user-images.githubusercontent.com/10966416/31599293-0154876e-b20f-11e7-917a-a773b7918001.png)

问题已经解决了
之前在MaskTexture Shader file里面的贴图是空的
都赋值之后可以运行了

不过还是很感谢你出这本书 
期待第二版！
继续买继续支持！

**Comment by candycat1992** [comment]
感谢支持呀 :)
