### ISSUE TITLE
13.3.1 中， scale 是不是计算有误？ i.interpolatedRay 怎么理解？

### ISSUE THREAD

**Issue by haolly** [candycat1992/Unity_Shaders_Book#175]
书上由 dist = |TL| / Near * depth 推导出  scale = |TL| / |Near|

然后说 Ray<sub> TL</sub> = TL / |TL| * scale,    

是不是少乘了 depth ?

第二个问题：
` float3 worldPos = _WorldSpaceCameraPos + linearDepth * i.interpolatedRay;` 
其中 i.interpolatedRay 是在vertex 函数中计算的，但是我想不通的是，在vertex 中将屏幕分成了四个象限，每个象限对应一个射线（在c#中计算出来的）,象限只是我的描述性比喻。
但是，难道在同一个象限中射线都是一样的吗？
如果从摄像机出观察，[0,0] 和 [0.4, 0.4]处的射线应该方向不一样呀

**Comment by candycat1992** [comment]
1. 没有少乘depth。最后我们推导得到的这4个Ray对应了P277最上面代码所表示的那个等式中的interpolatedRay：
```
float4 worldPos = _WorldSpaceCameraPos + linearDepth * interpolatedRay;
```
depth的值是在这里和ray相乘的，书里dist=...这个等式其实是在推导上面这句代码。

2. 的确，我们算的这4个Ray只对应了屏幕四个角的射线，而屏幕中间部分的interpolatedRay是靠对这4个射线插值得到的，这也就是为什么我们要在vertex shader里计算这4个射线，因为我们想要利用vertex to fragment的硬件插值，来得到具体到每个fragment自己对应的那条interpolatedRay。你可以再仔细看一下P277的推导部分，自己在纸上画一画。

**Comment by haolly** [comment]
谢谢乐乐
第一个问题我清楚了
第二个问题中，插值我是知道的，我疑惑的一点是，为啥要把屏幕分成四部分，然后用四个角来做插值，
例如屏幕坐标 [0.4,0.4] 这个点插值应该和[0,0],[0,1],[1,0],[1,1] 这个四个点都相关的，应该根据这四个点的某种运算来最终决定最后的结果，而不是只用 [0,0] 这个点来做插值

不知道我有没有说清楚，举个例子吧，例如，在两个点之间做插值，最后的结果在这两个点组成的线段上；在三个点钟做插值，例如组成模型的三角形的三个顶点，那么结果就是在这个三角形中，但是做插值的时候需要知道三个顶点的坐标，而不仅仅只是一个顶点的坐标

是我对插值的过程理解有误/不清楚吗？

**Comment by candycat1992** [comment]
你对插值理解有问题，从vertex到fragment的插值就是在三角形的三个顶点属性上进行插值的，插值的时候是知道三个顶点的坐标以及它们的顶点属性。你可以再看下P13的图和解释，网上也有很多关于插值的资料。

**Comment by haolly** [comment]
哈，知道了，光栅化阶段会进行三角形和三角形遍历，这样三角形的三个顶点信息都就是已知的了。

-------
再问最后一个问题，真的是最后一个了，我保证 :laughing:
屏幕后处理中，顶点着色器需要处理的顶点应该只有四个吧，正方形的四个角，正如P282所说，
那么在 *FogWithDetpthTexture.shader* 中，顶点着色器的输入 `v.texcoord` 应该就是固定的四个值吧？
*[0,0]，[0,1]， [1,0]， [1,1]* ，所以在代码中也可以直接用等式判断，例如 `if  v.texcoord.x == 0 && v.texcoord.y == 0 then index = 0` ?  还是说不一定是这四个坐标？

**Comment by candycat1992** [comment]
是固定的，但浮点数的判断最好不要用“==”，因为精度问题。所以这里采用了范围判断，本质想法和你的是一样的。
