### ISSUE TITLE
关于11.2.1的序列帧动画问题

### ISSUE THREAD

**Issue by LANYT** [candycat1992/Unity_Shaders_Book#176]
在11.2.1中，初始我的Boom.png的warp mode是设置为Clamp模式，但是显示效果出错，而对比后我发现示例项目中是设置为Repeate模式，虽然我知道这两种模式的意思，但是我确实没想明白在这个问题中为什么设置Clamp会导致显示出错，望解疑

**Comment by candycat1992** [comment]
因为fragment shader里算行列数的代码使用了对时间值取floor，会使得计算得到的纹理坐标超过[0, 1]范围：
```
float time = floor(_Time.y * _Speed);  
float row = floor(time / _HorizontalAmount);
float column = time - row * _HorizontalAmount;
```

**Comment by LANYT** [comment]
@candycat1992 超过范围会取到边缘的值透明度为零，所以显示有问题，但是repeat的话他会重复取到颜色值，但是为什么显示出来的特效不会是一次显示若干个相同特效出来，比如显示了九个一样的特效1的爆炸，而显示出来却很正确，是因为播的太快？（ps：我觉得我可能表述的不清楚，不知道你是否明白，总之谢谢回答）

**Comment by candycat1992** [comment]
我的确没太明白额……因为代码里的计算保证了每次我们只会取atlas里面一帧的画面：
```
half2 uv = i.uv + half2(column, -row);
uv.x /=  _HorizontalAmount;
uv.y /= _VerticalAmount;
```
