### ISSUE TITLE
Unity 2017.2 兼容?

### ISSUE THREAD

**Issue by optimisez** [candycat1992/Unity_Shaders_Book#178]
目前能不能兼容Unity 2017.2或以上的版本?

**Comment by candycat1992** [comment]
你好，经我目前的测试，你直接使用[unity_2017_1的分支](https://github.com/candycat1992/Unity_Shaders_Book/tree/unity_2017_1)在Unity 2017.2下是没有问题的。如果有问题的话可以在这里反馈给我。
