### ISSUE TITLE
在法线贴图的计算中，为什么解压法线并且使用xy和Scale控制凹凸程度之后，需要重新计算z？

### ISSUE THREAD

**Issue by vvency** [candycat1992/Unity_Shaders_Book#179]
我理解这样做是为了保证法线长度为1，但是为什么要这样做？
在测试中有发现如果不重新计算z，光照的计算结果会变弱。并且在切线空间中变弱的程度要比在世界空间中更强。请问这是为什么呢？

**Comment by candycat1992** [comment]
因为在计算dot(lightDir, normalDir)的时候要求这些向量都必须是单位向量（长度为1），这样dot的值才等于夹角的余弦值。

**Comment by vvency** [comment]
谢谢！我没有考虑到这个方面。。看来还需要多学习
