### ISSUE TITLE
                                       p66 4.5.7 关于母牛妞妞缩放和平移的问题                            

### ISSUE THREAD

**Issue by songchaoxx** [candycat1992/Unity_Shaders_Book#18]
我在unity中做了一个实验，对一个cube进行缩放 3 和平移（0,1,0），无论顺序如何，表现结果都是一样的。
transform.localToWorldMatrix：
3.00000	0.00000	0.00000	0.00000
0.00000	3.00000	0.00000	1.00000
0.00000	0.00000	3.00000	0.00000
0.00000	0.00000	0.00000	1.00000
平移矩阵并没有和缩放矩阵相乘，平移直接赋值了。
作者的讲法在数学上是没啥问题的。但是私以为，缩放应该是在模型坐标系做的，点缩放后的坐标变换也是相对模型坐标系而言的。这里容易引起误解，似乎用旋转和平移讲更合适一些。
我不是专业的图形程序员，如果有理解不对的地方，请谅解~

**Comment by candycat1992** [comment]
你可以把你的测试代码放上来，我并不理解你的意思“移矩阵并没有和缩放矩阵相乘，平移直接赋值了”，你最后得到的是一个矩阵很明显是相乘的结果呀，这个结果更加说明unity里是先缩放再平移的，否则就不是这个结果，顺序是很重要的，只是unity隐藏了这个顺序。

**Comment by songchaoxx** [comment]
if (GUI.Button(new Rect(20, 40, 80, 20), "1")) 
        {
            transform.localScale = new Vector3(3, 3, 3);
            transform.Translate(new Vector3(0, 1, 0));
            Debug.LogError(transform.localToWorldMatrix);
        }

        if (GUI.Button(new Rect(120, 40, 80, 20), "2"))
        {
            transform.Translate(new Vector3(0, 1, 0));
            transform.localScale = new Vector3(3, 3, 3);
            Debug.Log(transform.localToWorldMatrix);
        }

1 先缩放再平移，2先平移后缩放。输出的结果是一样的，所以感觉平移部分像是直接赋值的。或许Unity把这些东西先缓存起来，最后一起处理的吧，像你说的细节隐藏了。
矩阵相乘顺序是很重要的，我对此没有异议。只是觉得书上讲的部分理解起来有点困难。

“我们先按（0,0,5）平移它，现在它距离原点5个单位。然后再将它放大2倍，这样所有的坐标都变成了原来的2倍，而这意味着妞妞现在的位置是（0,0,10）。”
按照这个说法，一个线段，两个端点坐标是（-1,0,0）和（1,0,0），平移（2,0,0），放大2倍之后坐标分别是（2,0,0）和（6,0,0）。这大概不对吧。
我理解的缩放，模型的中心点是不动的，其他点在模型坐标系下坐标会缩放。

我似乎忽然明白了，transform是把平移，缩放和旋转这些参数先存起来了，然后在需要的时候再按照缩放旋转平移的顺序组成复合矩阵，是这样吗？

**Comment by candycat1992** [comment]
嗯呢，书上说的是它们本质计算时候的做法，你说的是调用封装后的API，这是不同的哦，你在调用那些API的时候它们背后是按照书里的原理实现的。
