### ISSUE TITLE
第4章4.7法线变换疑问（p87）

### ISSUE THREAD

**Issue by GITHUB243884919** [candycat1992/Unity_Shaders_Book#182]
p87，第三行的推导，第一步就看不明白
为什么(Ma->b Ta)乘以(GNa) = (Ma->b Ta)的转置矩阵 乘以 (GNa）
我看了unity内置的shader
inline float3 UnityObjectToWorldNormal( in float3 norm )
{
	// Multiply by transposed inverse matrix, actually using transpose() generates badly optimized code
	return normalize(unity_WorldToObject[0].xyz * norm.x + unity_WorldToObject[1].xyz * norm.y + unity_WorldToObject[2].xyz * norm.z);
}
这也相当于用的逆矩阵。就是看不明白原理

**Comment by candycat1992** [comment]
你可以参考[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/17)。

**Comment by GITHUB243884919** [comment]
哦，好像明白了。是不是可以这样说：不是(Ma->b Ta)等于他的转置矩阵，而是整个等式要把点乘转成矩阵乘，所以要转置。

**Comment by candycat1992** [comment]
对的，就是这个意思 :)

**Comment by GITHUB243884919** [comment]
谢谢~
