### ISSUE TITLE
第9章阴影效果不正确问题

### ISSUE THREAD

**Issue by yuna0820** [candycat1992/Unity_Shaders_Book#183]
乐乐姐你好！
在自己写的shader中尝试使用SHADOW_ATTENUATION的值没有效果，输出SHADOW_ATTENUATION之后发现阴影只出现在与别的物体重叠的地方，也不投射阴影的问题如下图。
![image](https://user-images.githubusercontent.com/22795331/33021193-f3533eaa-ce3b-11e7-91af-b910b6bf1ef3.png)
![image](https://user-images.githubusercontent.com/22795331/33021286-43cc2ce8-ce3c-11e7-8fd6-a3a8216e832f.png)
模型meshrenderer里的接受阴影和投射阴影都开了。

后来打开随书资源里第九章的阴影示例shader：Shadow，把fallback注释掉之后也是一样的情况如下图
![image](https://user-images.githubusercontent.com/22795331/33021989-983a763e-ce3e-11e7-923a-4f18c1f39145.png)
不用fallback里的shadow的话就只能加shadowcaster的pass来添加阴影了吗求解0 0
望回复谢谢！

**Comment by candycat1992** [comment]
你好，说实话我没有太看懂你的图，你没有说清楚你设置的到底是哪个物体的shader和状态？阴影这块比较绕，你可以看一下[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/49)，然后把问题描述清楚后我们再来交流，例如你的场景物体设置等。
