### ISSUE TITLE
4.6.6 p75 观察矩阵疑问

### ISSUE THREAD

**Issue by GITHUB243884919** [candycat1992/Unity_Shaders_Book#184]
做了下实验，得出的结果不一致有疑问。
相机的世界postion = （0,1,-10） ，rotation = （0,0,0），scale = （1,1,1）
然后在c#中使用camera.projectionMatrix 得出的结果是
		m00	1f	System.Single
		m01	0f	System.Single
		m02	0f	System.Single
		m03	0f	System.Single
		m10	0f	System.Single
		m11	1f	System.Single
		m12	0f	System.Single
		m13	-1f	System.Single
		m20	0f	System.Single
		m21	0f	System.Single
		m22	-1f	System.Single
		m23	-10f	System.Single
		m30	0f	System.Single
		m31	0f	System.Single
		m32	0f	System.Single
		m33	1f	System.Single

按您书上的理解，我认为这个矩阵是正确的观察矩阵
但是我用p75最后一段的第一种方法构造出来的矩阵结果却不一样，具体代码如下：
                Matrix4x4 viewFrame2 = new Matrix4x4();
                viewFrame2.SetColumn(0, cam.transform.right);
                viewFrame2.SetColumn(1, cam.transform.up);
                viewFrame2.SetColumn(2, cam.transform.forward);
                viewFrame2.SetColumn(3, new Vector4(camPos.x, camPos.y, camPos.z, 1.0f));
                
                viewFrame2.m20 *= -1f;
                viewFrame2.m21 *= -1f;
                viewFrame2.m22 *= -1f;
              Matrix4x4 view3 = viewFrame2.inverse;
其中cam是相机，view3 是最后求出观察矩阵，这个矩阵的结果是
		m00	1f	System.Single
		m01	0f	System.Single
		m02	0f	System.Single
		m03	0f	System.Single
		m10	0f	System.Single
		m11	1f	System.Single
		m12	0f	System.Single
		m13	-10.8f	System.Single
		m20	0f	System.Single
		m21	0f	System.Single
		m22	-1f	System.Single
		m23	-10f	System.Single
		m30	0f	System.Single
		m31	0f	System.Single
		m32	0f	System.Single
		m33	1f	System.Single
这个结果就只有m13和上面不一致，是不是第二种方法代码写的有问题？

**Comment by candycat1992** [comment]
[Camera.projectionMatrix](https://docs.unity3d.com/ScriptReference/Camera-projectionMatrix.html)不是观察矩阵，是投影矩阵。观察矩阵是[Camera.worldToCameraMatrix](https://docs.unity3d.com/ScriptReference/Camera-worldToCameraMatrix.html)。

**Comment by GITHUB243884919** [comment]
噢，噢。果然。观察矩阵直接就有了。如果要实在要自己算，按书的方式1求观察矩阵，是不是应该
`        Matrix4x4 V = Matrix4x4.identity;
        Camera cam = Camera.main;
        V.SetColumn(0, cam.transform.right);
        V.SetColumn(1, cam.transform.up);
        V.SetColumn(2, cam.transform.forward * -1.0f);
        V.SetColumn(3, new Vector4(cam.transform.position.x, cam.transform.position.y, cam.transform.position.z, 1.0f));
        V = V.inverse;`
