### ISSUE TITLE
12.3.3节边缘检测实现中梯度计算的问题

### ISSUE THREAD

**Issue by vvency** [candycat1992/Unity_Shaders_Book#186]
12.3.3节边缘检测shader中计算梯度时为什么是1减去加权后的edgeX和edgeY？
我修改为梯度公式中的edgeX + edgeY之后，实际效果中_EdgeColor和_BackgroundColor的颜色会被互换，而且withEdgeColor的效果也会减弱，请问是为什么呢？

**Comment by ZeroChiLi** [comment]
这个结果只是作为插值控制量而已，如果用edgeX + edgeY的话， 后面插值把前面两个参数互换就可以了。如下：
```
fixed4 withEdgeColor = lerp(tex2D(_MainTex, i.uv[4]),_EdgeColor,  edge);
fixed4 onlyEdgeColor = lerp( _BackgroundColor,_EdgeColor, edge);
```

**Comment by vvency** [comment]
那请问使用1- edgeX - edgeY相比于edgeX + edgeY有什么更好的地方呢？

**Comment by ZeroChiLi** [comment]
应该没有区别吧。

**Comment by candycat1992** [comment]
如@ZeroChiLi 所说，就是数学公式方面的互换参数而已。

**Comment by vvency** [comment]
好的谢谢！
