### ISSUE TITLE
问下P59关于正交矩阵的问题

### ISSUE THREAD

**Issue by w524418617** [candycat1992/Unity_Shaders_Book#187]
p59页队伍正交矩阵的特点用的例子，
两个矩阵，第一个矩阵只有第二列有数值，它的转置矩阵就是只有第二行有数值，其他的符号（-，|）是什么意思？
我将矩阵改为
c1 c1 c1
c2 c2 c2
c3 c3 c3
这样与他的转置矩阵相乘得出的新矩阵的第一行第一列的数值就是3（c1）²，因为正交矩阵的乘积为单位矩阵，所以3（c1）²=1？我理解的对么？

还有下一页的结论，c1、c2、c3是单位矢量，不应该是矩阵的第一行整个是一个单位矢量么？c1,c2,c3只是这个矢量的三个值？

还是矩阵的任何一个值都可以是矢量。

刚开始学，是不是有什么概念弄错了，希望有人能指导下

**Comment by w524418617** [comment]
额，看到后面一节，问题就解决了。。。原来就是矢量的一种写法 。。。

**Comment by candycat1992** [comment]
解决就好，那我就close啦~
