### ISSUE TITLE
第四章 4.7节法线变换（87页） 矩阵推导

### ISSUE THREAD

**Issue by LaserYvTian** [candycat1992/Unity_Shaders_Book#188]
![image](https://user-images.githubusercontent.com/11958240/33473531-bfc85858-d6b1-11e7-9df7-7926a5770d34.png)
红框的推导不是太理解，能解释一下吗？

**Comment by ZeroChiLi** [comment]
https://github.com/candycat1992/Unity_Shaders_Book/issues/17

**Comment by snailedMan** [comment]
我的理解是  前者是向量点乘，后者是矩阵相乘，不知道理解是否正确
