### ISSUE TITLE
5.2中代码的错误

### ISSUE THREAD

**Issue by fengxiaorui** [candycat1992/Unity_Shaders_Book#19]
104,105,106三页的代码片段中，输入和书上一样的shader代码会报错，提示invalid output semantic 'SV_POSITION': Legal indices are in [0,0] at line 22 (on d3d11)
在删除了v2f vert(a2v v)后的 SV_POSITION 后显示结果正常，应该是在顶点着色器输出v2f结构后，就不能使用SV_POSITION语义来标识顶点着色器的输出

**Comment by candycat1992** [comment]
你好,这块的确有问题，之前在github源码里面已经更新过了，勘误列表(http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)也更新过啦

造成你的困扰很抱歉，如果之后再遇到编辑错误或对代码有疑问的时候，可以查看勘误列表以及最新版的github代码

**Comment by fengxiaorui** [comment]
谢谢，书写的很好，收益颇丰

**Comment by candycat1992** [comment]
感谢支持 :)
