### ISSUE TITLE
Procedural Material Asset应该译为“程序材质资源”，不是"程序纹理资源"

### ISSUE THREAD

**Issue by ljcduo** [candycat1992/Unity_Shaders_Book#190]
第7次印刷229页，小错误。

另外感谢作者出版后仍然对此书的勘误非常上心，国内很少见，谢谢！

**Comment by candycat1992** [comment]
感谢建议，已添加到[勘误列表](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)里。

哈哈写的时候就想着要向优秀的前辈们尽量靠近一点，也是因为觉得自己能力有限，怕误人子弟--|||
