### ISSUE TITLE
11章爆炸动画不是很明白

### ISSUE THREAD

**Issue by deviljz** [candycat1992/Unity_Shaders_Book#191]
比如我做了一个爆炸动画的prefab，并且做了预加载，也就是gameobject已经存在，只是隐藏掉了。然后我用的时候把它显示出来，希望它从第一帧开始放爆炸的动画。但是用_Time.y来控制的话，gameobject显示出来的时候在哪一帧是不一定的吧？那么有没有办法做到这一点？

**Comment by ljcduo** [comment]
我有个想法，给shader加多一个startTime属性，在游戏对象通过OnEnable脚本给startTime传入当前的_Time。
着色器中通过_Time.y - startTime代替_Time.y来控制动画进度。
关于通过脚本设置着色器属性，可参考官方文档：https://docs.unity3d.com/Manual/MaterialsAccessingViaScript.html
