### ISSUE TITLE
又有个问题。。。

### ISSUE THREAD

**Issue by w524418617** [candycat1992/Unity_Shaders_Book#193]
P124中最下面求反射方向的公式r=2(n·l)n-l
p132中最上面又列举了反射方向的公式r=l-2(n·l)n
这两个公式结果是一样的么？

**Comment by ljcduo** [comment]
注意矢量l的方向性，图6.3 vs 图6.9

**Comment by candycat1992** [comment]
如@ljcduo所说，也可以参考之前的[issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/41)。
