### ISSUE TITLE
高斯模糊代码化简建议

### ISSUE THREAD

**Issue by ljcduo** [candycat1992/Unity_Shaders_Book#194]
乐乐你好，在P256页（第七次印刷）中这段高斯模糊的代码（Unity_Shaders_Book\Assets\Scripts\Chapter12\GaussianBlur.cs），我认为是可以化简不必要的复杂的：

```
void OnRenderImage(RenderTexture src, RenderTexture dest)
{
    if (material != null)
    {
        int rtW = src.width / downSample;
        int rtH = src.height / downSample;

        RenderTexture buffer0 = RenderTexture.GetTemporary(rtW, rtH, 0);
        buffer0.filterMode = FilterMode.Bilinear;

        Graphics.Blit(src, buffer0);

        for (int i = 0; i < iterations; i++)
        {
            material.SetFloat("_BlurSize", 1.0f + i * blurSpread);

            RenderTexture buffer1 = RenderTexture.GetTemporary(rtW, rtH, 0);

            // Render the vertical pass
            Graphics.Blit(buffer0, buffer1, material, 0);

            RenderTexture.ReleaseTemporary(buffer0);
            buffer0 = buffer1;
            buffer1 = RenderTexture.GetTemporary(rtW, rtH, 0);

            // Render the horizontal pass
            Graphics.Blit(buffer0, buffer1, material, 1);

            RenderTexture.ReleaseTemporary(buffer0);
            buffer0 = buffer1;
        }

        Graphics.Blit(buffer0, dest);
        RenderTexture.ReleaseTemporary(buffer0);
    }
    else
    {
        Graphics.Blit(src, dest);
    }
}
```

我觉得可以化简成如下代码：
```
void OnRenderImage(RenderTexture src, RenderTexture dest)
{
    if (material != null)
    {
        int rtW = src.width / downSample;
        int rtH = src.height / downSample;

        RenderTexture buffer0 = RenderTexture.GetTemporary(rtW, rtH, 0);
        RenderTexture buffer1 = RenderTexture.GetTemporary(rtW, rtH, 0);
        buffer0.filterMode = FilterMode.Bilinear;
        Graphics.Blit(src, buffer0);

        for (int i = 0; i < iterations; i++)
        {
            material.SetFloat("_BlurSize", 1.0f + i * blurSpread);

            // Render the vertical pass
            Graphics.Blit(buffer0, buffer1, material, 0);
            // Render the horizontal pass
            Graphics.Blit(buffer1, buffer0, material, 1);

        }

        Graphics.Blit(buffer0, dest);
        RenderTexture.ReleaseTemporary(buffer0);
        RenderTexture.ReleaseTemporary(buffer1);
    }
    else
    {
        Graphics.Blit(src, dest);
    }
}
```

理由如下：
1. 原来的代码在循环里重复GetTemporary和ReleaseTemporary，会造成性能下降。其实没有必要在循环过程中重复申请和释放缓存，而重复利用buffer0和buffer1。在循环前申请，并在循环后再释放。
2. 一开始看原来这段代码也觉得挺晕的，buffer0和buffer1还多次相互交换，按照我化简后的写法不需要互换。读者理解起来会更简单清晰。

我也测试过，代码化简后的高斯模糊效果也是一样的。

希望有帮助！

**Comment by ZeroChiLi** [comment]
👍 两个好建议

**Comment by candycat1992** [comment]
你好，非常感谢你的建议，的确可以这样简化，会在后续的版本里进行修改。

**Comment by milanow** [comment]
这里有一点小疑问，首先这样写确实更好理解一些~但是UnityDoc在关于GetTemporary这个函数[GetTemporary](https://docs.unity3d.com/ScriptReference/RenderTexture.GetTemporary.html)下写到：“If you are doing a series of post-processing "blits", it's best for performance to get and release a temporary render texture for each blit, instead of getting one or two render textures upfront and reusing them.” 而且也说道“Unity keeps a pool of temporary render textures.” 如果做了pool的话就算频繁调用GetTemporary和ReleaseTemporary也不会有什么问题？只是不明白Unity为什么会建议在每个Blit之后都Release一下。如果按照Unity建议，反而原来的写法更好一点点？

**Comment by RaymondCL** [comment]
> 这里有一点小疑问，首先这样写确实更好理解一些~但是UnityDoc在关于[GetTemporary](https://docs.unity3d.com/ScriptReference/RenderTexture.GetTemporary.html)这个函数下写到：“If you are doing a series of post-processing "blits", it's best for performance to get and release a temporary render texture for each blit, instead of getting one or two render textures upfront and reusing them.” 而且也说道“Unity keeps a pool of temporary render textures.” 如果做了pool的话就算频繁调用GetTemporary和ReleaseTemporary也不会有什么问题？只是不明白Unity为什么会建议在每个Blit之后都Release一下。如果按照Unity建议，反而原来的写法更好一点点？ @ljcduo
我也查看了一下，Release it using ReleaseTemporary as soon as you're done with it, so another call can start reusing it if needed. 官方就是建议一用完，立刻就释放，这样才能保证其内部对TemporaryRenderTexture的重复利用，所以还是乐乐的方法才是更优的

**Comment by MonkeyTomato** [comment]
我也查看了一下，Release it using ReleaseTemporary as soon as you're done with it, so another call can start reusing it if needed. 官方就是建议一用完，立刻就释放，这样才能保证其内部对TemporaryRenderTexture的重复利用，所以还是乐乐的方法才是更优的。所以在勘误里面才没有这一条？

**Comment by MonkeyTomato** [comment]
额，我上一条的想法好像有误。ljcduo 的和乐乐的方法应该都只使用了两个RenderTexture的buffer，虽然unity内部帮我们实现了缓存，但在这里，我们自己都可以直接重复使用的，就不需要使用Unity的Release接口了。
