### ISSUE TITLE
关于卷积部分计算上的问题

### ISSUE THREAD

**Issue by GreenPan** [candycat1992/Unity_Shaders_Book#196]
乐乐你好,我在看你的书时,对P252的卷积运算不是很明白,有些问题希望你能帮我解答一下.

按照书中的代码,你的采样是这样的:
![1](https://user-images.githubusercontent.com/33819294/34086632-bad0bc28-e3e0-11e7-9c40-220805f5dfab.jpg)
是先填充的左下角,后填充的右上角.然后与算子进行计算

但是,通常情况下不是先填充左上角,后填充右下角,才能建立与算子一一对应的关系吗?
![2](https://user-images.githubusercontent.com/33819294/34086653-f8a9cd0a-e3e0-11e7-87a4-42e61fd853bb.jpg)
计算Gx的时候好像没有什么区别,但计算Gy的时候,这两个采样方式计算结果完全是相反的.
请问这是什么原理呢?与UV坐标系有关系吗?

**Comment by GreenPan** [comment]
如果我看漏了某些东西,或者对问题表述不够清晰,还请告诉我.
自从学写shader,我都怀疑自己是不是智力有缺陷(ಥ_ಥ)

**Comment by ZeroChiLi** [comment]
1. 纹理坐标就是从左下角开始的。
2. 因为最后要取得是Gx、Gy相乘的**绝对值**。所以Gx左右翻转、Gy上下翻转对结果都没影响。

**Comment by GreenPan** [comment]
原来是绝对值造成的结果没有影响,理解了.

但是允许我再纠结一下,如果当我在其他计算中,没有这个绝对值的操作,那么我应该选择哪种采样方式呢?
因为我在之前确实看到过一一对应的计算,在 #24 @FreeBlues 5楼的一段代码中

```
// sobel operator
// position.      Gx.            Gy
// 1 2 3     |-1. 0. 1.|   |-1. -2. -1.|
// 4 5 6     |-2. 0. 2.|   | 0.  0.  0.|
// 7 8 9     |-1. 0. 1.|   | 1.  2.  1.|
// 右上角，右，右下角
c[3] = intensity(texture2D( texture, vec2(clamp(p.x+ws,0.,w), clamp(p.y+hs,0.,h) )));
c[6] = intensity(texture2D( texture, vec2(clamp1(p.x+ws,w), clamp1(p.y,h))));
c[9] = intensity(texture2D( texture, vec2(clamp1(p.x+ws,w), clamp1(p.y-hs,h))));

// 上, 下
c[2] = intensity(texture2D( texture, vec2(clamp1(p.x,w), clamp1(p.y+hs,h))));
c[8] = intensity(texture2D( texture, vec2(clamp1(p.x,w), clamp1(p.y-hs,h))));

// 左上角, 左, 左下角
c[1] = intensity(texture2D( texture, vec2(clamp1(p.x-ws,w), clamp1(p.y+hs,h))));
c[4] = intensity(texture2D( texture, vec2(clamp1(p.x-ws,w), clamp1(p.y,h)))); 
c[7] = intensity(texture2D( texture, vec2(clamp1(p.x-ws,w), clamp1(p.y-hs,h))));

// 先进行 sobel 滤波, 再把范围从 [-1,1] 调整到 [0,1]
// 注意: 比较方向要跟坐标轴方向一致, 横向从左到右, 纵向从下到上
float dx = (c[3]+2.*c[6]+c[9]-(c[1]+2.*c[4]+c[7]) + 1.0) / 2.0;
float dy = (c[7]+2.*c[8]+c[9]-(c[1]+2.*c[2]+c[3]) + 1.0) / 2.0;
float dz = (1.0 + 1.0) / 2.0;
```

倒数第二行,可以看到他这里在计算的时候都是一一对应的,左上乘-1,右下乘1,

**Comment by ZeroChiLi** [comment]
确实应该一一对应呢，可能是作者的失误吧。

**Comment by GreenPan** [comment]
嗯嗯,非常感谢你对我的帮助ヾ(ﾟ∀ﾟゞ)
顺序的问题我们还是等待作者的答复吧.

**Comment by candycat1992** [comment]
左、右、上、下这种方位词很容易造成混淆，我还是用下标来表示吧，比如C00表示当前像素，C01表示采样坐标u方向相同、v方向上加1的像素。

我先说我个人的结论，这种检测差值的卷积核的正负值应该与采样坐标变化方向相同，也就是说，应该是采样坐标越大的像素去减去采样坐标较小的像素，算差值。拿Sobel算子的Gy来说，我认为@FreeBlues代码的float dy = (c[7]+2.*c[8]+c[9]-(c[1]+2.*c[2]+c[3]) + 1.0) / 2.0应该反过来，因此如果以这个uv坐标系看来，c[7]和c[1]的差别是c[7]比c[1]在v方向上少了两个单位，所以应该是用c[1]的值减去c[7]的值。

我认为这种规则更符合求导数的定义，即x和y方向上的导数应该是Gh/Gx和Gh/Gy，其中h是关于xy的函数。如果严格按照上面的规则来，这也意味着，uv坐标空间的选择会影响滤波之后的效果。Unity由于背后处理了多平台差异，通常来说左下角是(0,0)点，但在很多图像处理软件里左上角是(0,0)点，wiki里通常是用矩阵的表示方法，即从左到右、从上到下来标记，意味着也是左上角是(0,0)点。@FreeBlues代码的代码注释应该是按照这种左上角是(0,0)点的情况下处理的，但他使用的API是OpenGL，(0,0)点其实是在左下角的。

总结来说就是，我个人认为正负应该符合采样坐标变化方向，因此要注意选择的uv坐标空间。当然，我们总是可以在后面做一些取反操作，如果你觉得效果有问题的话。

**Comment by GreenPan** [comment]
了解了,谢谢乐乐.
