### ISSUE TITLE
P76 关于z轴分量取反操作，第一个矩阵的4行4列的值是不是应该为1呢？

### ISSUE THREAD

**Issue by snailedMan** [candycat1992/Unity_Shaders_Book#197]
在勘误列表中没有找到相关错误修改，自己运算了一下应该是1 才对吧？难道是我算错了？

**Comment by candycat1992** [comment]
我没有找到错误的地方：
![qq 20171219142320](https://user-images.githubusercontent.com/5907064/34143556-31c55ec8-e4c8-11e7-936a-0b5443f74a1a.png)

你可以把截图发上来。

**Comment by snailedMan** [comment]
我这边是这样的的：
![35ba04a6-34e7-44c4-b806-353e4997c6ca](https://user-images.githubusercontent.com/16531415/34287837-b3e2b366-e724-11e7-9558-d0b102ca8546.png)

**Comment by snailedMan** [comment]
是不是出了修订版了？可以在哪里买到？

**Comment by candycat1992** [comment]
这个问题早在第二印刷版次就已经修正过了。如果你手里的还是有问题，可能你是去年年中的时候买的，或者是看的网上的盗版，据我观察盗版电子版一直都是第一版次的，从来没有勘误过……

**Comment by snailedMan** [comment]
好的谢谢，请问什么时候会出第二版本？打算买一本，细度。
