### ISSUE TITLE
About RampDiffuse

### ISSUE THREAD

**Issue by hellogavin** [candycat1992/Unity_Shaders_Book#2]
There is a bug in RampDiffuse line 29.float2 cannot only one argument

**Comment by candycat1992** [comment]
Thanks. Can you specify the exact file name and line number? Did you mean Chapter7-RampTexture.shader?

**Comment by hellogavin** [comment]
Chapter1/RampDiffuse line29
float3 ramp = tex2D(_RampTex, float2(hLambert)).rgb;

**Comment by candycat1992** [comment]
Ok, I know. Did you mean Chapter 1 of the book **Unity Shaders and Effects Cookbook** , which was written in surface shader? The code you pasted indeed has some problems, but I'm not the author of this book and not responsible for the codes. Maybe you can send emails to the author Kenny Lammers :)
