### ISSUE TITLE
第七章基础纹理，关于反射率albedo的问题

### ISSUE THREAD

**Issue by CaigerDeng** [candycat1992/Unity_Shaders_Book#20]
这一章里，常看到求albedo的公式：
fixed3 albedo = tex2D(_MainTex , i.uv).rgb * _Color.rgb ;
对反射率只有初中物理的印象，不知道这里为什么又采样又乘颜色，想问问这个公式是怎么来的。

**Comment by candycat1992** [comment]
你好，这个没有什么很准确的物理模型支持。经验模型里面大多只是“看起来对就好”，这里又采样又乘以颜色只是为了让最后物体的颜色既可以受纹理影响，又可以在材质面板里受颜色参数影响。

**Comment by CaigerDeng** [comment]
原来是这样，感谢解答。
