### ISSUE TITLE
正交投影矩阵是线性的理解？

### ISSUE THREAD

**Issue by deadmarston** [candycat1992/Unity_Shaders_Book#200]
在4.5.1里表4.1提到正交投影矩阵是线性变换的，但是在4.6正交投影里投影矩阵中有最后一列存在一个平移的变化，为什么这还是一个线性变换？
13.1.2中提到深度值是非线性的，需要变换到线性空间下，麻烦您解释一下为什么一定要转换到线性空间下才行，谢谢？

**Comment by HongfeiXu** [comment]
说下我对第二个问题的理解：
主要是结合了下面提到的两本书的部分内容。

这个问题在《游戏引擎架构》的10.1.4.8节中有比较清楚的解释。**主要是为了避免深度冲突**（z-fighting）。（深度冲突：两个足够接近的平面，其各自的深度值可能会是相同的离散值，使得较远的平面像素“刺穿”较近的平面。）
为了让整个场景的深度冲突降至最低，我们希望无论要渲染的平面是远还是近，其深度具有相同的精确度。然而，这里我们从《Unity Shader 入门精要》13.1.2 中的**Z_ndc**的公式可以看到，深度值是非线性的，并且，随着物体到摄像机距离的不断增加，同样的分隔在变换后（透视投影+透视除法）变成细小的NDC空间距离，此结果造成深度冲突，并且当物体越离开摄像机情况越严重。

因此需要将深度值从原来的非线性空间变换到线性空间下。

**Comment by candycat1992** [comment]
你好，抱歉这么久才回答。

1. 正交投影是线性变换的问题

这里的确是我写的有问题。表4.1左侧一栏不应该指某种特定矩阵，线性变换指的是变换类型，而不是局限在某种矩阵，所以左侧一栏应该是对应的变换种类。

具体到正交投影来说。根据[wiki](https://zh.wikipedia.org/wiki/%E4%B8%89%E7%BB%B4%E6%8A%95%E5%BD%B1)，正交投影变换是指：

> 三维投影是将三维空间中的点映射到二维平面上的方法。正投影（正交投影）：投影线垂直于投影平面

简单来说就是把三维物体投影到二维平面。我们以4.6正交投影为例，此时被投影的二维平面可以理解成就是裁剪平面，投影平面上的点对应正交投影矩阵变换后的xy分量。对于xy两个分量来说，它们是满足线性变换的定义的，即在变换的时候可以保证向量加和向量乘，因此正交投影变换是线性变换。

2. 线性深度值

@HongfeiXu 的解释有些问题，当经过投影矩阵变换到裁剪空间之后，就交给了硬件做深度检测。非线性的深度值的确会有精度不均匀的问题，但我们只能在变换的时候尽可能改善精度（比如使用[深度反转](https://github.com/candycat1992/Unity_Shaders_Book/issues/177)），但不会完全避免。

我们之所以要在shader里得到线性空间下的深度值，通常是因为效果需要。例如13.3节全局雾效需要线性深度值（即摄像机空间下的深度值）来重建世界坐标。如果效果不需要，我们当然不用进行这种线性解码。
