### ISSUE TITLE
8.3（P165） 关于相同渲染队列里的渲染顺序疑问

### ISSUE THREAD

**Issue by GITHUB243884919** [candycat1992/Unity_Shaders_Book#201]
P164和P165说透明队列里的渲染顺序是“从后往前的顺序”。对于这个有疑问。我做了下实验。
在两个物体如果同时处于Transparent或Overlay队列中，从FrameDebug上看，是先渲染离相机近的。
而 在Background，Geometry，AlphaTest中是先渲染离相机远的。

**Comment by candycat1992** [comment]
你可以把截图放上来，我个人觉得是你看错了……

**Comment by GITHUB243884919** [comment]
确实，我看错了。在透明队列里，先渲染离相机远的； 不透明队列里，先渲染离相机近的。

**Comment by TinyGhost** [comment]
不对吧，只要在一个渲染队列里就是从后向前的吧

**Comment by candycat1992** [comment]
不透明物体大体上是按照从前往后的顺序渲染的，因为这有利于提前对后面的物体做depth test，那些靠后的、被前面物体挡住的物体就不需要浪费时间再执行fragment shader等计算浪费时间了。半透明物体如果设置正确的话大体上是按照从后往前的顺序绘制的，因为只有这样混合结果才尽可能是正确的。

下面是三个不透明物体在Frame Debugger里显示的绘制顺序：
![tim 20180108121917](https://user-images.githubusercontent.com/5907064/34658949-7aa4308c-f46e-11e7-9455-4920269cbb66.png)

下面是三个半透明物体在Frame Debugger里显示的绘制顺序：
![tim 20180108122012](https://user-images.githubusercontent.com/5907064/34658972-aaacaa5c-f46e-11e7-8e32-53f09561b06c.png)

如果有不同的意见，欢迎截图来说明和交流。
