### ISSUE TITLE
第七章中的法线贴图shader只接受一个光源

### ISSUE THREAD

**Issue by zhaozilie12** [candycat1992/Unity_Shaders_Book#202]
今天测试的时候发现的问题

**Comment by candycat1992** [comment]
你说得没错，但这是故意的。因为在第七章的时候，只讲到了如何实现平行光的光照逻辑，所以这些shader只实现了ForwardBase的Pass。多光源的实现是在第9章才讲到的，所以第9章之前的shader都只接受一个平行光。
