### ISSUE TITLE
UpdateDepthTexture一片黑色 没有任何的深度信息？

### ISSUE THREAD

**Issue by milanow** [candycat1992/Unity_Shaders_Book#203]
乐乐你好，

在书中第九章的内容里提到了camera depth texture~并且在issue页面里您也有 #49 提到对于Shader中有ShadowCast的Pass && Queue <= 2500的物体会在depth texture里面记录。可是我使用Frame Debugger查看“UpdateDepthTexture”这个Event的时候却是一片漆黑，就算我把（camera对着的）物体改成了Standard Shader（源码里面是有ShadowCast的）依旧是黑色的。请问您知道这个问题出在哪儿么？

场景：default settings把skybox去掉，加了一个capsule，场景中只有一个平行光。实际上许多场景camera depth texture都是黑色的，像shadow map这些都是正常渲染的。其实只想对camera depth texture有一个视觉上直观的印象

Note：使用的是Unity2017.2.0f3

感谢！

**Comment by milanow** [comment]
好吧。。。其实是我眼拙。。。。。。。。。。。。。。。。。。。。。。。。。。。。很仔细仔细看的话是能看到的。。。。。。。。。。。。。。。。。。。。。。

**Comment by candycat1992** [comment]
这个现象其实在书的P271有提到：
![tim 20180118133700](https://user-images.githubusercontent.com/5907064/35082400-94361856-fc54-11e7-9ff7-aa57c35be5b1.png)

主要是深度范围的问题，可以试试调整下远裁剪平面距离，保证视锥范围内最大限度的存在有效物体，就可以看到比较明显的深度图像了。
