### ISSUE TITLE
第11章 公告板up跟right向量的计算

### ISSUE THREAD

**Issue by alasja** [candycat1992/Unity_Shaders_Book#204]
根据左手法则，up x normal得到的应该是图中right的反方向。这里是用的右手法则吗？为啥用右手法则呢？![这里写图片描述](http://static.zybuluo.com/candycat/nmwj4c59j8dif8828fehq477/basis_vector.png)

**Comment by candycat1992** [comment]
这个是我把right方向的图画反了……感谢指正。
