### ISSUE TITLE
第12章边缘检测Sobel算子采样的纹理坐标计算

### ISSUE THREAD

**Issue by vizjoy** [candycat1992/Unity_Shaders_Book#205]
因为是新学习Sobel算子，不太理解如下uv的计算逻辑：
1.如下括号中那9个坐标是如何得到的？
2.为什么要用纹素大小的值分别去乘以这个坐标，再和uv值相加呢？
感谢

o.uv[0] = uv + _MainTex_TexelSize.xy * half2(-1, -1);
o.uv[1] = uv + _MainTex_TexelSize.xy * half2(0, -1);
o.uv[2] = uv + _MainTex_TexelSize.xy * half2(1, -1);
o.uv[3] = uv + _MainTex_TexelSize.xy * half2(-1, 0);
o.uv[4] = uv + _MainTex_TexelSize.xy * half2(0, 0);
o.uv[5] = uv + _MainTex_TexelSize.xy * half2(1, 0);
o.uv[6] = uv + _MainTex_TexelSize.xy * half2(-1, 1);
o.uv[7] = uv + _MainTex_TexelSize.xy * half2(0, 1);
o.uv[8] = uv + _MainTex_TexelSize.xy * half2(1, 1);

**Comment by milanow** [comment]
@vizjoy 这9个half2不是坐标 应该是偏移量~uv[9]这个array代表着以当前pixel为中心的(包括当前pixel)周围pixel的坐标。比如half2(-1,-1)就代表当前pixel的左下角那个pixel的索引的偏移量(如果uv starts at top就是左上角)，texelsize是纹素大小，实际上也是两个纹素的距离，texelsize*uv索引偏移量 = 实际uv坐标的偏移量，再加上uv就是相应的周围坐标的uv值

**Comment by vizjoy** [comment]
感谢

**Comment by vizjoy** [comment]
感谢解答，理解了
