### ISSUE TITLE
13章末尾提到的针对特定物体的描边效果基本思路可以详细点吗

### ISSUE THREAD

**Issue by ghost** [candycat1992/Unity_Shaders_Book#207]
首先，感谢作者的真诚之作。这本书是目前来说对我帮助最大的一本书了。
对于13章末尾的特定物体的描边效果，很希望提供一个基本的思路，网上的教程好像没有根据法线纹理或深度纹理进行描边的，期望作者可以完善这一细节。
[Unity Shaderlab: Object Outlines](https://willweissman.wordpress.com/tutorials/shaders/unity-shaderlab-object-outlines/)这篇文章并没有利用Graphics.DrawMesh()及深度/法线图进行描边。

**Comment by ZeroChiLi** [comment]
我写了三篇简单特定物体描边实现，尝试用了Graphics.DrawMesh（在方法2和3中），你可以参考一下。代码以Github上为准。
http://blog.csdn.net/l773575310/article/details/78701756
http://blog.csdn.net/l773575310/article/details/78714406
http://blog.csdn.net/l773575310/article/details/78729906

**Comment by candycat1992** [comment]
谷歌搜索一下是有很多教程的，比如http://xroft666.blogspot.com/2015/07/glow-highlighting-in-unity.html，正如书里最后一章说的，学会科学上网非常重要。

**Comment by MrBaoQuan** [comment]
你的实现均是利用屏幕颜色信息进行的，书中在12.3节尾也有提到。作者在13章结尾提到的是根据深度/法线图进行描边的算法，现在的问题是我不太清楚该在什么地方实施这个算法(怎样获取单个物体的深度/法线贴图?)
