### ISSUE TITLE
13章（雾的计算）interpolatedRay顶点插值后是否需要再归一化

### ISSUE THREAD

**Issue by linyuan5856** [candycat1992/Unity_Shaders_Book#208]
![normalization](https://user-images.githubusercontent.com/12449769/36061280-3e80874c-0e93-11e8-83c1-31967522008f.png)
![nonormalization](https://user-images.githubusercontent.com/12449769/36061281-3eb6fc1e-0e93-11e8-913e-83b9be0c61f0.png)

**Comment by linyuan5856** [comment]
第一张图是做了归一化处理的 
第二张图是书中的效果

**Comment by candycat1992** [comment]
不应该归一化，它本身不是单位向量，是包含了长度信息的值。

**Comment by linyuan5856** [comment]
谢谢 我再去温习下
