### ISSUE TITLE
书中5.2.3顶点着色器和片元着色器之间如何通信

### ISSUE THREAD

**Issue by kafeiweimei** [candycat1992/Unity_Shaders_Book#209]
关于Shader中出现错误如下，请问如何解决？：
Shader error in 'Unity Shaders Book/Chapter 5/Simple Shader': cannot convert from 'struct v2f' to 'float4' at line 36 (on d3d11)

源码为：
// Upgrade NOTE: replaced 'mul(UNITY_MATRIX_MVP,*)' with 'UnityObjectToClipPos(*)'

Shader "Unity Shaders Book/Chapter 5/Simple Shader"
{
	SubShader
	{
	Pass
	{
		CGPROGRAM
		#pragma vertex vert  
		#pragma fragment frag  
	struct a2v
	{
		float4 vertex : POSITION;
		float3 normal : NORMAL;
		float4 texcoord : TEXTCOORD0;
	};

	struct v2f
	{
		//SV_POSITION语义告诉Unity，pos 里包含了顶点在裁剪空间中的位置信息  
		float4 pos : SV_POSITION;
		//COLOR0 语义可以用于存储颜色信息  
		fixed3 color : COLOR0;
	};

	float4 vert(a2v v) : SV_POSITION
	{
		//声明输出结构  
		v2f o;
	    o.pos = UnityObjectToClipPos(v.vertex);
		//v.normal 包含了顶点的法线方向，其分量范围在[-1.0, 1.0]  
		//下面的代码把分量范围映射到了[0.0, 1.0]  
		//存储到o.color 中传递给片元着色器  
		o.color = v.normal * 0.5 + fixed3(0.5, 0.5, 0.5);
		return o;
	}

	fixed4 frag(v2f i) : SV_Target
	{
		//将插值后的i.color显示到屏幕  
		return fixed4(i.color,1.0);
	}
		ENDCG
	}
	}
}

**Comment by ZeroChiLi** [comment]
vert函数返回值应该是`v2f` 而不是 `float`。
见作者源码：https://github.com/candycat1992/Unity_Shaders_Book/blob/master/Assets/Shaders/Chapter5/Chapter5-SimpleShader.shader
