### ISSUE TITLE
勘误 p74 模型变换矩阵的构造

### ISSUE THREAD

**Issue by RouderSky** [candycat1992/Unity_Shaders_Book#210]
p74也中 模型空间 到 世界空间 变换矩阵中的缩放因子是2,2,2，2的来由是 模型缩放大小/世界缩放大小=2，也就是说缩放因子=原空间缩放/目标空间缩放

但是，
《fundamentals of computer graphics》中 NDC 到 屏幕坐标 的变换矩阵是：
![image](https://user-images.githubusercontent.com/18010177/36417698-932ee898-1667-11e8-8a8a-748b45f96f3d.png)
可以看出缩放因子是nx/2，也就是说来由是 屏幕空间缩放大小/NDC缩放大小，即缩放因子=目标空间缩放/原空间缩放

那么，谁是正确的？？？

**Comment by candycat1992** [comment]
没明白你的问题……你也说了《fundamentals of computer graphics》中的矩阵是从NDC到屏幕坐标，P74的是从模型空间到世界空间，完全是不同的。P84也有从NDC到屏幕空间的，你可以去看看。

**Comment by RouderSky** [comment]
比如：要将坐标从A转换到B，那么矩阵中的缩放因子怎么确定，也就是主对角线上的数值怎么确定？是A/B还是B/A？

**Comment by RouderSky** [comment]
好像是我搞错了，不好意思
