### ISSUE TITLE
关于 6.2.5 逐像素还是逐顶点 的困惑

### ISSUE THREAD

**Issue by anarchy0316** [candycat1992/Unity_Shaders_Book#211]
您写到 逐像素的渲染方式是对顶点法线进行插值这句话让我困惑了好久。

后来我觉得自己想明白了，因此前来求证: 

是不是因为在逐顶点渲染中，是利用每个顶点的位置和法线进行计算出颜色，然后面片中对三个顶点圈成的三角形中的每个像素进行插值。

而逐像素，从v2f结构体中得到的法线，已经是经过插值的了，不仅如此，而且 v2f 中的所有数值都是经过插值的。因此能得到相对更为精准的颜色表现。

另外我发现您对v2f中取得的向量都会先做一步normalize，请问是因为这个数值经过插值后已经不再是单位长度了吗？ 否则我找不到不在vertex shader 中将其normalize的理由

**Comment by iiRecord** [comment]
在 fragment shader 中不 normalize normal 然后计算出此时插值后 normal 的长度假设是 len ，然后 fragment shader 返回 float4(len, 0, 0, 1) 看看是不是红色，应该可以大概验证了吧。

**Comment by candycat1992** [comment]
逐顶点/像素渲染是指在顶点/像素着色器中进行渲染颜色的计算，只是指代我们选择在哪个着色器阶段计算光照模型而已。

在像素着色器里对向量会再次进行normalize，是因为即便我们在顶点着色器输出它们之前进行过normalize，这些单位向量经过光栅化插值后不再是单位长度了，具体原因你可以参考[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/78)。如果我们不在像素着色器里对这些向量再次归一化，会导致漫反射结果偏暗（因为长度变短了），有时在效果不明显的情况下，的确可以省略像素着色器里的归一化操作来节省指令数。

**Comment by SteveCruise** [comment]
@candycat1992 好强啊比我低两届的学妹，请问编写 shader/材质 的最佳姿势是用unity3d还是3dmax/maya这种软件？

**Comment by TableBreaker** [comment]
shader本身只是渲染管线的一步，具体是跟图形API挂钩的，unity里的shader是经过封装的，还额外包括了很多渲染参数的设置，并且是只适用于unity的，所以感觉并没有什么最佳姿势的说法，应该视应用场景来选择的吧~

**Comment by SteveCruise** [comment]
@TableBreaker 应用场景就是用unity做游戏，这样的话用unity编shader好呢，还是用别的什么软件编好，再把材质导入进来？

**Comment by TableBreaker** [comment]
@SteveCruise 如果你指的是shader语法的话，unity只认自己的shaderlab，外部材质导入Unity会默认使用unity的standard shader，所以还是要使用unity的shaderlab。
如果你指的是使用哪种文本编辑器的话选择就很多了~
