### ISSUE TITLE
p43.印刷错误：第四段是图4.9不是3.9

### ISSUE THREAD

**Issue by zhangte0604** [candycat1992/Unity_Shaders_Book#212]
如题。
不是什么大错误，但是发现了还是说一下哈哈

**Comment by happyfire** [comment]
请问是刚买的书么？现在版次是最新的第10班么

**Comment by zhangte0604** [comment]
刚买的，看不出第几版，书上写着2016.6重印

**Comment by happyfire** [comment]
内容提要那页最下面，两道横线之间，有一堆小字，里面有个：“2016年6月第1版”，难道一直是第1版？勘误表上都出了第10版次了，难道一直没有印刷？

**Comment by candycat1992** [comment]
勘误表里写的印刷版次是一定已经印刷了的，但具体到哪个平台卖那种版次就不一定了，我身边最近买的似乎都是第8、9版次。
