### ISSUE TITLE
4.6.6 观察空间,关于opengl的坐标系

### ISSUE THREAD

**Issue by happyfire** [candycat1992/Unity_Shaders_Book#214]
原文是
>“Unity在模型空间和世界空间中选用的都是左手坐标系，而在观察空间中使用的是右手坐标系。这是符合OpenGL传统的，在这样的观察空间中，摄像机的正前方指向的是-z轴方向”。

我记得OpenGL应该是模型空间右手，观察空间左手啊。Unity和OpenGL正好是反的。当然如果是用在shader里面应该没关系吧，反正都是自己去变换了。

**Comment by candycat1992** [comment]
“你记得”这个有点太模糊啦，你可以给出你的依据。我的依据部分如下：
[https://softwareengineering.stackexchange.com/questions/17519/why-does-directx-use-a-left-handed-coordinate-system](https://softwareengineering.stackexchange.com/questions/17519/why-does-directx-use-a-left-handed-coordinate-system)
[https://stackoverflow.com/questions/4124041/is-opengl-coordinate-system-left-handed-or-right-handed](https://stackoverflow.com/questions/4124041/is-opengl-coordinate-system-left-handed-or-right-handed)
