### ISSUE TITLE
[勘误] 7.3渐变纹理的代码Chapter7-RampTexture.shader

### ISSUE THREAD

**Issue by happyfire** [candycat1992/Unity_Shaders_Book#215]
其中 v2f.uv没有使用到，应该去除?
包括 vert中o.uv的计算，结构体中v2f.uv和a2v.texcoord的定义应该去掉。谢谢！

edit: 如果这样，看起来 float4 _RampTex_ST; 也不需要了?

**Comment by candycat1992** [comment]
不需要的的确应该都去掉，我当时应该是实验其他写法遗留下来的，不是很严谨，感谢勘误~
