### ISSUE TITLE
第七章法线贴图 切线空间和世间空间对法线贴图的读取(UnpackNormal)

### ISSUE THREAD

**Issue by linyuan5856** [candycat1992/Unity_Shaders_Book#216]
**Unity内置unpack方法已经算出了normal.z的值 书中代码又重复计算了一次**

- 相关脚本
` Chapter7-NormalMapWorldSpace`
`Chapter7-NormalMapTangentSpace`
- 书中代码
``` shaderlab
  // Get the normal in tangent space
 fixed3 bump = UnpackNormal(tex2D(_BumpMap, i.uv.zw));
 bump.xy *= _BumpScale;
 bump.z = sqrt(1.0 - saturate(dot(bump.xy, bump.xy)));
```
- UnityCG.cginc
```  shaderlab
inline fixed3 UnpackNormalDXT5nm (fixed4 packednormal)
{
    fixed3 normal;
    normal.xy = packednormal.wy * 2 - 1;
    normal.z = sqrt(1 - saturate(dot(normal.xy, normal.xy)));
    return normal;
}

inline fixed3 UnpackNormal(fixed4 packednormal)
{
#if defined(UNITY_NO_DXT5nm)
    return packednormal.xyz * 2 - 1;
#else
    return UnpackNormalDXT5nm(packednormal);
#endif
}
```

**Comment by linyuan5856** [comment]
![right](https://user-images.githubusercontent.com/12449769/38244878-9d6d0718-376e-11e8-92d9-659d1b38221f.png)

**被重复计算的图片中出现了 黑色的坑**
![wrong](https://user-images.githubusercontent.com/12449769/38244880-a18e0de2-376e-11e8-9401-ecee90825284.png)

**Comment by candycat1992** [comment]
你好，书中代码之所以要再算一次，是因为使用_BumpScale来对xy分量进行了缩放，所以要计算缩放后的z分量，是没有问题的。
