### ISSUE TITLE
Problem in Chapter-14-ToonShading.shader

### ISSUE THREAD

**Issue by rebas777** [candycat1992/Unity_Shaders_Book#218]
第 14 章中 ToonShading.shader 中对于 speculer 部分的计算未添加衰减以及阴影的影响~~提前有算好 atten 变量，但是忘记乘上去了？~~ 。

导致即便在阴影之下，高光部分仍然存在。如图：
![tim 20180421183640](https://user-images.githubusercontent.com/24671805/39083188-0e7fb0ea-4593-11e8-9b69-b6be3e3a73de.png)

**Comment by candycat1992** [comment]
你好，的确应该乘上去，感谢建议~
