### ISSUE TITLE
P42 关于左右手坐标系的疑问

### ISSUE THREAD

**Issue by RouderSky** [candycat1992/Unity_Shaders_Book#219]
P42 第4段 最后一句话

> 你的大拇指、食指、中指分别对应了+x、+y、+z轴的方向

  这句话是否准确，因为在其它资料中得到这么一个结论：在数学领域中Up向量是+y，在图形领域Up向量是+z，但无论如何，大拇指、食指、中指分别对应了+x、Up向量、Forward向量。

**Comment by candycat1992** [comment]
`因为在其它资料中得到这么一个结论：在数学领域中Up向量是+y，在图形领域Up向量是+z，但无论如何，大拇指、食指、中指分别对应了+x、Up向量、Forward向量。`
你这个肯定是不对的……你看的资料是什么？资料一般会在这些结论之前讲一个前提，就是“在大多数情况下”。而对于每个软件、每篇论文等等，它们选择的坐标朝向是会基于很多原因的，比如领域传统甚至个人喜好……
