### ISSUE TITLE
frac方法的疑问，取的小数部分不准确？

### ISSUE THREAD

**Issue by Ruijie-Qin** [candycat1992/Unity_Shaders_Book#220]
根据5.5节 False Color 的shader，我做了一个测试，发现frac方法的一个奇怪的问题，测试方法如下：
1. 在Unity里面新建一个Plane，然后把使用这个Shader的材质拖上去，顶点着色器的关键代码如下：
`o.color = fixed4(0.0, 0.0, 0.0, 1.0);
o.color.r = frac(v.texcoord.x);
o.color.g = v.texcoord.x;`
2. 贴图的uv是在[0,1]，理论上frac(v.texcoord.x) 和  v.texcoord.x 结果应该一致，但实际测试下来，在接近 1 的时候，两者出现了差别，很困惑，求个解释。如图：
![20180512164159](https://user-images.githubusercontent.com/1065488/39955581-db7bfccc-5603-11e8-830c-eef2d9819143.png)
左侧从绿色的部分开始就不一致了，代码在右侧。

**Comment by candycat1992** [comment]
这个是因为顶点到片元着色器之间的插值导致的。因为你的frac是在顶点着色器里计算的，所以是逐顶点计算结果的。那么对于你图中最右侧的一列顶点来说，它们的v.texcoord.x=1则有frac(v.texcoord.x)=0，而对于倒数第二列顶点来说，它们的v.texcoord.x=0.9则有frac(v.texcoord.x)=0.9，所以经过插值后，这两列顶点之间的像素颜色就是在0.9~0之间插值，也就是你图中的颜色。

如果你把frac计算移到片元着色器里计算就不会出现这个问题了，这和frac精度无关。

**Comment by Ruijie-Qin** [comment]
恍然大悟，这样一看，更能理解两个着色器了，感谢感谢！
