### ISSUE TITLE
关于 Fallback "内置Shader" 的疑问

### ISSUE THREAD

**Issue by HongfeiXu** [candycat1992/Unity_Shaders_Book#226]
你好，现在读到第8章啦，哈哈，书很棒。
说说我的疑问，第 8 章，透明度测试Shader的代码（Chapter8-AlphaTest.shader）最后，有一个Fallback指令
```
Fallback "Transparent/Cutout/VertexLit"
```
我的疑惑是，在 builtin_shaders-5.2.1f1\DefaultResourcesExtra 文件夹下面找到了这个内置 Shader，**AlphaTest-VertexLit.shader**，但由于这个 Shader 已经是作为 Legacy Shader，并且它的名字是 **"Legacy Shaders/Transparent/Cutout/VertexLit"**，我想知道上面的 Fallback 指令中是否需要改为
```
Fallback "Legacy Shaders/Transparent/Cutout/VertexLit"
```
否则它是如何在需要的时候找到并使用这个Shader的？
另外，同样作为一个 Legacy Shader，书中也用到的 Normal Shader Family 中的 Specular 却没有从上面的文件夹中找到，不知道为什么。希望能得到你的解答。

**Comment by candycat1992** [comment]
你用路径全称"Legacy Shaders/Transparent/Cutout/VertexLit"肯定是没有问题的，但对于这些内置shaders来说，使用"Transparent/Cutout/VertexLit"也可以有正确结果的，官方文档里没有明确说明，但我认为这是为了向前兼容，早期在还没有Standard Shader，不存在什么Legacy Shaders的时候，Fallback都是用"Transparent/Cutout/VertexLit"这样的路径写的。后来变成Legacy Shaders后，官方应该是为了向前兼容所以这些路径也还是可以工作的。
