### ISSUE TITLE
关于双面渲染的透明效果的一点疑问？

### ISSUE THREAD

**Issue by HongfeiXu** [candycat1992/Unity_Shaders_Book#227]
作者您好，在书的第8.7节给出了一个透明度混合的双面渲染的实现，方法是在关闭深度写入的前提下，用两个Pass来分别渲染模型的背面和正面。

上面这种方法可以很好地解决那些模型本身没有遮挡关系的情况。可是一旦模型出现了遮挡，比如书中的Knot模型，依然是会出现混合错误的问题，而且这里显然不能通过进行提前深度测试的方式来解决，因为那样的话，一定是渲染不出背面的（实验结果如下图）。不知道有没有好的解决方法？

![](https://github.com/HongfeiXu/UnityShader_FLL/raw/master/Images/KnotBothSided.png)

**Comment by candycat1992** [comment]
如果模型自身相互遮挡超过了两层，那么没有完美的解决方法可以把它内部的各个遮挡层都渲染出来。如果性能上放宽松一点的话，在层数不多的情况下，可以使用OIT，你可以参考我另一个项目[OIT_Lab](https://github.com/candycat1992/OIT_Lab)。

**Comment by HongfeiXu** [comment]
嗯嗯，感谢
