### ISSUE TITLE
11.3.1水流例子里的模型怎么看不到网格呢？

### ISSUE THREAD

**Issue by ArcherLew** [candycat1992/Unity_Shaders_Book#229]
我自己用plane或者quad替换例子里的模型，然后把材质和shader赋予它，参数调成和例子里一样，效果完全不同，而且怎么调都和例子里不一样。quad是整个斜着拉长了，而plane则是要么波长很长，要么波长很短且很不平滑。

不知道例子里的波浪平面模型是由什么特殊处理呢？我在编辑器下甚至都看不到它的网格。

**Comment by candycat1992** [comment]
这是因为水波那个模型是和shader里写的方向配合的，你可以参考[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/189)。

**Comment by ArcherLew** [comment]
谢谢！
