### ISSUE TITLE
关于书本代码进行手机测试的问题

### ISSUE THREAD

**Issue by vsattce** [candycat1992/Unity_Shaders_Book#23]
先跪作者写着本书，好东西啊。
上个礼拜把书看完了，里面的相关例子在电脑上正常通过。不过我在移动设备，比如6S上则是有不少的例子都挂了直接黑掉了，看了下作者的CSDN的关于高效shader的博客做了下优化不过没用。同时对于target的设定也做过更改,也没什么用
所以大胆请教下，这是和shader的内部的计算复杂有关还是和unity的设置有关。

还有个问题，想问下，在unity shader里除了顶点着色器和片元着色器的交互变量会使用寄存器，那么在Properties里面设置的变量也会使用寄存器吗？（可能书里面说了 我没看仔细 问错了请见谅）

这两个问题自己有点搞不明白，所以请教下作者，先谢谢了。

**Comment by candycat1992** [comment]
为什么这么快就close问题了……我还没回答……

黑掉的应该是前9章的一些shader吧？前9章的目的是说明原理，一些宏可能在移动平台上并没有，所以才会这样。如果是后9章也有这种问题的话可以告诉我！因为我大部分都在手机上测试过，应该没问题的。

Properties并不会使用GPU什么的寄存器，两者没有关系，Properties只是为了在材质面板上显示而已，真正会占用GPU寄存器的是你在CGINCLUDE和ENDCG里面声明的各种属性。

感谢支持 :)
