### ISSUE TITLE
13章深度法线纹理

### ISSUE THREAD

**Issue by YZUnity** [candycat1992/Unity_Shaders_Book#231]
想问一下，深度法线纹理被分别编码进R，G和B，A通道。这是说深度、法线纹理是二维向量吗？如果是，每个分量具体保存的是什么内容呢？

**Comment by candycat1992** [comment]
不能理解成向量。本质上一张纹理就是用来存储数据的，例如RGBA32的每一个texel可以存储一个32位的数据，至于这个数据是什么完全由开发者来定，颜色和向量等仅仅是其中一种数据而已。书里讲到的把深度写进RGBA里就是说，把32位的float精度的深度值写到RGBA的32位里，具体代码你可以参考[Aras的博客](https://aras-p.info/blog/2009/07/30/encoding-floats-to-rgba-the-final/)。
