### ISSUE TITLE
你好，关于8.5半透明问题的一点疑惑

### ISSUE THREAD

**Issue by MrRee1995** [candycat1992/Unity_Shaders_Book#232]
我看到在书上165页渲染队列Transparent的描述中，Transparent是在Geometry和AlphaTest队列之后从后往前进行渲染的。
    那么使用Transparent队列是否还需要关闭深度写入呢？
    我对关闭深度写入的理解是：如果后面不透明物体后进行渲染，在深度测试时会被剔除。
    如果使用了Transparent队列，就不会出现不透明物体和在后面的半透明物体后完成渲染的情况。
    另外，我也不是很理解8.5节所说使用两个Pass先打开深入写入再关闭深度写入与直接不关闭深度写入两者的区别。
     因为我在使用这两种方法写出来的Shader在Unity中得到的是同样的效果。
     望解惑。。。谢谢

**Comment by candycat1992** [comment]
你好，这个问题在[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/153)里回答过，你可以参考下。

**Comment by MrRee1995** [comment]
对于关闭深度写入的原因明白了，谢谢。
对于8.5使用第一个Pass来写入深度缓冲与直接不关闭深度写入有什么区别吗？二者都把模型的深度信息写入了深度缓冲。多使用一个pass的原因是什么呢？

**Comment by candycat1992** [comment]
区别在于：
如果是直接不关闭深度写入，那么像素在渲染的时候会同时写入color buffer和depth buffer，这会导致明显的错误排序效果。可以考虑如果一个自交叉物体，某些部位的背面片元先于正面渲染，那么这些背面片元会首先进行透明混合并写入深度缓冲，等到相同位置的正面片元渲染时由于可以通过深度测试所以也会进行透明混合。而对于另一些部位则可能是正面先渲染，这样会导致只有正面进行透明混合。以上情况会导致对于复杂的模型来说，有些位置上透明混合发生了好几层，但某些地方可能只有一层，这取决于提交片元的顺序。在效果上会产生明显的错乱。
如果是先写入深度，那么在后续真正进行透明混合的时候我们可以保证模型所有位置都只会发生一层透明混合，即模型最靠近摄像机的那部分才会发生透明混合，因此不会出现明显的错乱效果。

**Comment by MrRee1995** [comment]
明白了，就是说不关闭的话透明混合的次数由渲染的顺序决定，可能有的地方出现了多次透明混合，而有的地方只有一次，渲染完成的效果就会出现明显错乱，如果先写入深度缓冲，后进行透明混合，就保证了不通过深度测试的不参与混合，屏幕上每个位置都只进行一次透明混合，就避免了效果的错乱。。。
感谢大大，讲解的非常仔细。。。谢谢

**Comment by candycat1992** [comment]
嗯呢对，而且不仅仅是混合次数，那些错乱地方的混合顺序也是无法保证的。对于一些非常简单的几何体，比如球体，的确可以先绘制背面，再绘制正面来保证绘制次数和顺序，从而实现正反面的半透明效果。但对于复杂一些的模型，比如自交叉物体的正背面其实是交错的，没法划分，所以仍然是有问题。感谢对书的支持~
