### ISSUE TITLE
[勘误] 5.2 Simple Shader

### ISSUE THREAD

**Issue by ChongChongS** [candycat1992/Unity_Shaders_Book#234]
v2f vert(a2v v) : SV_POSITION
{
	v2f o;
	o.pos = UnityObjectToClipPos(v.vertex);
	o.color = v.normal * 0.5 + fixed3(0.5, 0.5, 0.5);
	return o;
}

: SV_POSITION应该删去

**Comment by candycat1992** [comment]
你好，你可能看得是比较早的版本，这个早在第四印刷版次里就已经[勘误](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)过了。
