### ISSUE TITLE
Alpha Test添加阴影遇到没有阴影的问题

### ISSUE THREAD

**Issue by Mr-susu** [candycat1992/Unity_Shaders_Book#238]
首先，谢谢乐乐姐的辛勤付出。Alpha Test添加阴影，当时乐乐姐，提醒说，shader中必须要有_Cutoff属性，但是自己手打完shader后，一直没有阴影。
比对过代码也没有问题，最后发现_Color属性必须要有，当时只写了_MainTex和_Cutoff两个属性，没有写_Color属性，导致一直没有阴影。
仅此，希望再版时，提醒其他读者。
这一本书真是良心之作，卖的太便宜了，它值得更高。帮助我很多，再次感谢。

**Comment by mxrhyx233** [comment]
因为AlphaTest-VertexLit.shader里使用了_Color和_Cutoff两个属性做投影的计算吧，所以如果使用Fallback的话这2个一定要有。

**Comment by candycat1992** [comment]
以上两位说得都对，建议也很好非常感谢对书的支持，很开心~如果再版的话一定吸取建议。
