### ISSUE TITLE
P151计算切线空间下的法线z值没有详细解释，到底是什么意思？

### ISSUE THREAD

**Issue by moxinyu1221** [candycat1992/Unity_Shaders_Book#241]
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/5027252/45804114-d749a900-bced-11e8-9d9a-36ba7498b4d4.png">
后面的向量，自己点成自己，如果是单位向量的话，不就是1乘以1吗？我Debug后法线不一样，咋回事？

**Comment by mxrhyx233** [comment]
这里的点乘相当于tangentNormal的分量x^2+y^2结果

**Comment by moxinyu1221** [comment]
@mxrhyx233也就是说tangentNormal并不是单位向量，两个向量点成就是为了求两个向量的长度的乘积是吗？|a||b|Cos0=|a|*|b|

**Comment by leeshortway** [comment]
tangentNormal.x^2+tangentNormal.y^2+tangentNormal.z^2=1^2
tangentNormal.z=sqrt(1^2-(tangentNormal.x^2+tangentNormal.y^2))
tangentNormal.z=sqrt(1-dot(tangentNormal.x,tangentNormal.y))

**Comment by ylme** [comment]
这里就是用于计算光照的法线是一个单位矢量，已知 x y 分量，求 z 分量。
$x^2 + y^2 + z^2 = 1$
$z = sqrt(x^2 + y^2)$

**Comment by candycat1992** [comment]
如上正解。
