### ISSUE TITLE
首页的pdf文件怎么下载？提示无法访问

### ISSUE THREAD

**Issue by JupiterJiang** [candycat1992/Unity_Shaders_Book#244]
如题，
![image](https://user-images.githubusercontent.com/41321266/47495188-14253480-d886-11e8-868d-58468e2a3148.png)

**Comment by candycat1992** [comment]
国内访问github.io似乎一直不是很好，你翻墙试试看应该就可以了~

**Comment by JupiterJiang** [comment]
> 国内访问github.io似乎一直不是很好，你翻墙试试看应该就可以了~

好的 谢谢你
