### ISSUE TITLE
7.2 凹凸映射 副法线 binormal 计算

### ISSUE THREAD

**Issue by ylme** [candycat1992/Unity_Shaders_Book#245]
文件 Chapter7-NormalMapTangentSpace.shader 中计算 worldBinormal 是 

```
fixed3 worldBinormal = cross(worldNormal, worldTangent) * v.tangent.w; 
```

这里选择的 worldNormal 在前，是如何根据的呢？

**Comment by candycat1992** [comment]
通常我们代码里都是这么写：
`fixed tangentSign = v.tangent.w * unity_WorldTransformParams.w;
fixed3 worldBinormal = cross(worldNormal, worldTangent) * tangentSign;`

v.tangent.w是必须的，因为每个顶点自己本身的切线可能会反向。unity_WorldTransformParams.w是Unity赋值的：
`float4 unity_WorldTransformParams; // w is usually 1.0, or -1.0 for odd-negative scale transforms`
