### ISSUE TITLE
4.7 法线变换,电子版内容有误

### ISSUE THREAD

**Issue by lingzerg** [candycat1992/Unity_Shaders_Book#248]
公式错误
GAa 应该是 GNa
![8u9pxpmd5 bywtqxz 9x2m](https://user-images.githubusercontent.com/4156329/49640274-16171180-fa48-11e8-98d3-60aa520e5b18.png)

![img_0207](https://user-images.githubusercontent.com/4156329/49640242-fda6f700-fa47-11e8-9249-408104582b86.png)

**Comment by candycat1992** [comment]
感谢勘误 (*￣︶￣)
