### ISSUE TITLE
camera深度图_CameraDepthTexture手机上精度不够

### ISSUE THREAD

**Issue by xp168** [candycat1992/Unity_Shaders_Book#249]
sampler2D _CameraDepthTexture;
一些手机上sampler2D的精度不够，会出现梯度
 需要换成sampler2D_float

**Comment by candycat1992** [comment]
感谢勘误！

**Comment by candycat1992** [comment]
补充：
手机平台上sampler2D会默认转换成low precision samplers，因为depth texture通常是16或24 bits的，所以应该使用更高精度采样。

参考：https://docs.unity3d.com/Manual/SL-DataTypesAndPrecision.html
