### ISSUE TITLE
关于世界空间到观察空间变换的问题

### ISSUE THREAD

**Issue by Ojors** [candycat1992/Unity_Shaders_Book#25]
书上P75，为什么平移观察空间后得到的矩阵就是最终的变换矩阵呢？

**Comment by candycat1992** [comment]
这个可以继续看下面的解释。平移和旋转观察空间的过程其实就是对变换取逆变换的过程。想象把一个点从世界空间变换到观察空间，其实我们只需要按摄像机在世界空间变换的逆变换顺序变换该点即可，先平移相反的单位，再旋转相反的单位即可。

**Comment by Ojors** [comment]
嗯，懂了~！感谢~
