### ISSUE TITLE
关于第8章透明效果为什么只计算了漫反射不计算高光反射？

### ISSUE THREAD

**Issue by littleChoppe** [candycat1992/Unity_Shaders_Book#251]
你好，在第九章中实现的标准光照着色器里以及除第8章的透明效果之外都实现了高光反射，为什么透明效果不计算高光反射呢？是因为透明物品不需要高光反射效果吗？

**Comment by candycat1992** [comment]
你好，当时应该是考虑到这一小节只专注于解释半透明的原理，不想让shader代码太复杂，就只写了计算漫反射的部分（我是推测我当时是这么想的……--|||）。

**Comment by littleChoppe** [comment]
明白了。谢谢你这么热心回答唉，看着很多问题跟答案都隔了好久了，，以为不回有回复了，，，很是惊喜ヽ✿゜▽゜)ノ

**Comment by littleChoppe** [comment]
明白了。谢谢你这么热心回答唉，看着很多问题跟答案都隔了好久了，，以为不回有回复了，，，很是惊喜ヽ✿゜▽゜)ノ
