### ISSUE TITLE
法线映射问题

### ISSUE THREAD

**Issue by linda012518** [candycat1992/Unity_Shaders_Book#253]
你好，感谢作者出了这么好的书籍。
请教一下有关法线映射的问题：bump.z = sqrt(1.0 - saturate(dot(bump.xy, bump.xy)));
为什么 z 值要这样计算呢？
       dot(bump.xy, bump.xy)                                点积相同向量？
       1.0 - saturate(dot(bump.xy, bump.xy))        1.0减去点积结果意义如何？saturate已经确定大于0了
       sqrt()                                                            开平方意义如何，难到是经验公式？

**Comment by candycat1992** [comment]
你好，
法线向量是单位向量，即向量长度（模）为1，则有x^2 + y ^2 + z^2 = 1，所以z = sqrt(1 - x^2 - y^2) = sqrt(1 - dot(xy, xy))。saturate是为了防止dot(xy, xy)结果大于1，这样会使得sqrt里的参数未负，会有潜在bug。

**Comment by linda012518** [comment]
@candycat1992 
感谢女神解答，豁然开朗
