### ISSUE TITLE
page 9 的图2.6颜色问题

### ISSUE THREAD

**Issue by powerblood** [candycat1992/Unity_Shaders_Book#26]
书是黑白的，但是区分编程课操控性是用颜色区分的，怎么破？？

**Comment by candycat1992** [comment]
项目页面有提供所有的彩色插图（https://github.com/candycat1992/Unity_Shaders_Book），还有很多其他信息，要仔细看下的哦~书的前沿部分也有提到过的~

**Comment by powerblood** [comment]
sorry！我后来看到了，就是刚用github不知道怎么删掉这个留言。。。。。很感谢你的书，我是学艺术出身的，立志要做技术美术，你的书对新手比较友好啊

**Comment by candycat1992** [comment]
我也一直想学习美术呐，哈哈，非常感谢对书的支持，希望能帮到你 :)

**Comment by powerblood** [comment]
目前开始啃，看了下你也是研究生，我是GAFA的艺术设计，之前写论文的时候发觉国外已经在走融合的道路了，再后来了解到“Technical Artist”这种职业，在朋友的研发团队蹲了1年多又接触到shader，有人告诉我这个是技术美术的核心特征之一，所以我是死活要啃下来了辣

**Comment by candycat1992** [comment]
融合是指什么意思？哈哈技美对美术要求也很高的啊

**Comment by powerblood** [comment]
融合means别人也在吧技术和美术的结合作为一个大的方向来做，我是写动态图形设计的时候查了国外的资料，然后伦敦有个F.O.T.B（Flash On The Beach）艺术图形大会，与会者包括但不限于艺术家 / 设计师 /网络安全工程师 / 多媒体工作者 / 程序开发 / 教育学家 ··· ··· 主要议题是美学与技术的融合，这种场面在国内（以与会者身份来看）难以见到，这样的一个会议基本都是商务人员在派名片，上海的GDC就是这样不办的了···你在上海应该有了解GDC··········Anyway，国外的这个举动，国内我觉的多多少少迟迟早早都是要跟的了吧····所以我结合个人兴趣选了这样的方向，目前还在苦逼的找工作
