### ISSUE TITLE
线性变换

### ISSUE THREAD

**Issue by muyu7** [candycat1992/Unity_Shaders_Book#260]
平移变换满足标量乘的疑问：
![4 5 1](https://user-images.githubusercontent.com/19581517/58012107-4c43db80-7b26-11e9-91fa-790358ed6ad1.png)
![4 5 1_prove](https://user-images.githubusercontent.com/19581517/58012114-51a12600-7b26-11e9-8598-0d6b433de616.png)

**Comment by jeason1997** [comment]
修改为：既不满足，也不满足。
支持正版数据，低质PDF

**Comment by candycat1992** [comment]
这个很早就在[勘误](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)里面写过了。

@jeason1997 感谢支持正版！
