### ISSUE TITLE
关于SH光源计算的代码

### ISSUE THREAD

**Issue by JOKULLIU** [candycat1992/Unity_Shaders_Book#29]
作者好，我看到9.2.2这节，基本上靠自己的理解写完了，根据“看上去正确，就是正确”这一原则，应该大致不差，但是书中并未给出计算SH的代码，我自己写的，想请你给瞧瞧看到底是不是这样：
在 v2f vert (a2v v)函数中我直接用了Shade4PointLights函数：
o.shade4Col = Shade4PointLights (unity_4LightPosX0,
    unity_4LightPosY0, unity_4LightPosZ0, unity_LightColor[0].rgb, 
    unity_LightColor[1].rgb, unity_LightColor[2].rgb, unity_LightColor[3].rgb,
    unity_4LightAtten0, mul(_Object2World, v.vertex).xyz, 
    UnityObjectToWorldNormal(normalize(v.normal))); 
return o;
接下来在 fixed4 frag (v2f i) : SV_Target 函数中，把shade4Col加上去：
half4 finalCol;
finalCol.rgb = ambient + (diffuse + spec) * atten + i.shade4Col;
finalCol.a = 1;
return finalCol;
根据测试，大致是这样子的，光源被设置为 not Important时，还是能够照亮胶囊，但是没得高光，感觉像是没得高光的lambert照明，但不及lambert变化细致，请看看是不是这样？

另外我没有按照书上的做法去区分光的类型并计算光的方向，因为我还是习惯在ObjectSpace下面去写代码，所以我在ForwardAdd的Pass中，计算光的方向时，没有区分光的类型，因为ObjSpaceLightDir函数已经做了这个事情，所以我直接用了：
half3 lightDir = normalize(ObjSpaceLightDir(i.pos));
half3 viewDir = normalize(ObjSpaceViewDir(i.pos));
请问我的理解对吗？

此外在衰减代码中有一句是dot(lightCoord, lightCoord).rr，对这个.rr是什么意思不是太明白呢？

**Comment by candycat1992** [comment]
1. SH

SH的代码最好不要自己写，可以参考内置的surface shader生成的vf，里面依靠各种宏来辅助计算，可以防止出现错误的结果，例如光照在不需要的时候也计算了等等问题。按内置的逻辑大概是：

vert里是：

```
// SH/ambient and vertex lights
#ifdef LIGHTMAP_OFF
	#if UNITY_SHOULD_SAMPLE_SH
	o.sh = 0;
	// Approximated illumination from non-important point lights
		#ifdef VERTEXLIGHT_ON
			o.sh += Shade4PointLights (
					unity_4LightPosX0, unity_4LightPosY0, unity_4LightPosZ0,
					unity_LightColor[0].rgb, unity_LightColor[1].rgb, unity_LightColor[2].rgb, unity_LightColor[3].rgb,
					unity_4LightAtten0, o.worldPos, o.worldNormal);
		#endif
		o.sh = ShadeSHPerVertex (o.worldNormal, o.sh);
	#endif
#endif // LIGHTMAP_OFF
```

然后在frag里：

```
fixed3 color = ambient + (diffuse + specular) * atten;
#if UNITY_SHOULD_SAMPLE_SH
	color += i.sh;
#endif
return fixed4(color, 1.0);
```

变成not Important使用SH来计算的确会减弱高光，因为压根就没有算嘛~

2. 全部在ObjectSpace当然可以，书里也说到过，只要保证所有参与计算的矢量都在同一个坐标空间下就没问题。ObjSpaceLightDir和ObjSpaceViewDir在计算时要注意传进去的参数，应该也是ObjectSpace下的顶点坐标。另外，其实你可以看ObjSpaceLightDir和ObjSpaceViewDir的源码，相比于在世界空间下计算，这两个需要进行额外的矩阵乘法，把光源方向和视角方向从世界空间下转换到模型空间下，所以，我个人还是建议在世界空间下计算，减少这一次矩阵乘法的消耗。

**Comment by JOKULLIU** [comment]
感谢作者，再追问一下，在衰减代码中有一句是dot(lightCoord, lightCoord).rr，对这个.rr是什么意思不是太明白呢？

**Comment by candycat1992** [comment]
.rr就是float2(dot(lightCoord, lightCoord).r, dot(lightCoord, lightCoord).r)，swizzle操作。

是我之前没有说清。书在P183的9.1节的图9.4中有说明前向渲染中的Bass Pass可以做的事情：

![qq 20160817125137](https://cloud.githubusercontent.com/assets/5907064/17724983/71589990-6479-11e6-9f26-07a0a0a9f720.png)

Shade4PointLights其实是负责上图中的逐顶点光源，而ShadeSHPerVertex（在UnityStandardUtils.cginc中定义）则是负责上面的SH光照。

其实像这种内置函数都是可以查到源代码的，不需要瞎猜。

**Comment by JOKULLIU** [comment]
Shade4PointLights确实是逐顶点光源计算，这个我之前误以为是做SH光照。但是在代码中加上了你说那一段之后，整个光照明显不对了，所以我怀疑肯定是什么地方没做对。ShadeSHPerVertex我找到定义了，悲催的是Unity没给出任何注解，然后它里面还在不断引用其它内定的函数，我试图去理解……但实在办不到啊！
请求作者提供完整的前向渲染Shader，感激不尽~~~~
另外dot(lightCoord, lightCoord).rr这句还是没懂，dot是2个矢量的点乘啊，结果是个标量，何来后面.rr呢？实在理解不到，请作者明示~~~~

**Comment by CaigerDeng** [comment]
同关注 rr

**Comment by candycat1992** [comment]
你可以和内置的shader效果对比就知道大概对不对了。我的代码没什么特别的地方，就是参考内置的shader生成的vf shader写的，也就是修改了Bass Pass：
```
			struct a2v {
				float4 vertex : POSITION;
				float3 normal : NORMAL;
			};
			
			struct v2f {
				float4 pos : SV_POSITION;
				float3 worldNormal : TEXCOORD0;
				float3 worldPos : TEXCOORD1;
				half3 sh : TEXCOORD2; // SH
			};
			
			v2f vert(a2v v) {
				v2f o;
				o.pos = mul(UNITY_MATRIX_MVP, v.vertex);
				
				o.worldNormal = UnityObjectToWorldNormal(v.normal);
				
				o.worldPos = mul(_Object2World, v.vertex).xyz;

				// SH/ambient and vertex lights
				#ifdef LIGHTMAP_OFF
					#if UNITY_SHOULD_SAMPLE_SH
					o.sh = 0;
					// Approximated illumination from non-important point lights
					#ifdef VERTEXLIGHT_ON
						o.sh += Shade4PointLights (
							unity_4LightPosX0, unity_4LightPosY0, unity_4LightPosZ0,
							unity_LightColor[0].rgb, unity_LightColor[1].rgb, unity_LightColor[2].rgb, unity_LightColor[3].rgb,
							unity_4LightAtten0, o.worldPos, o.worldNormal);
					#endif
					o.sh = ShadeSHPerVertex (o.worldNormal, o.sh);
					#endif

				#endif // LIGHTMAP_OFF
				
				return o;
			}
			
			fixed4 frag(v2f i) : SV_Target {
				fixed3 worldNormal = normalize(i.worldNormal);
				fixed3 worldLightDir = normalize(_WorldSpaceLightPos0.xyz);
				
				fixed3 ambient = UNITY_LIGHTMODEL_AMBIENT.xyz;
				
			 	fixed3 diffuse = _LightColor0.rgb * _Diffuse.rgb * max(0, dot(worldNormal, worldLightDir));

			 	fixed3 viewDir = normalize(_WorldSpaceCameraPos.xyz - i.worldPos.xyz);
			 	fixed3 halfDir = normalize(worldLightDir + viewDir);
			 	fixed3 specular = _LightColor0.rgb * _Specular.rgb * pow(max(0, dot(worldNormal, halfDir)), _Gloss * 128);

				fixed atten = 1.0;
				
				fixed3 color = ambient + (diffuse + specular) * atten;
#if UNITY_SHOULD_SAMPLE_SH
				color += i.sh;
#endif
				return fixed4(color, 1.0);
			}
```

以场景Scene_9_2_2_1为例，如果场景里面的两个Point Light都设成Important，我的代码和内置的Legacy Shaders/Specular的对比如下：
![qq 20160818125633](https://cloud.githubusercontent.com/assets/5907064/17762508/e2af4df8-6543-11e6-9e71-128248b1b961.png) ![qq 20160818125641](https://cloud.githubusercontent.com/assets/5907064/17762507/e2ad8586-6543-11e6-8fc1-d67257a5f75a.png)

如果场景里面的两个Point Light都设成Not Important，我的代码和内置的Legacy Shaders/Specular的对比如下：
![qq 20160818125646](https://cloud.githubusercontent.com/assets/5907064/17762513/f17e1ac6-6543-11e6-997d-7d253b2d060a.png) ![qq 20160818125649](https://cloud.githubusercontent.com/assets/5907064/17762514/f186f8bc-6543-11e6-9125-e1fdd452177c.png)

这效果还是挺像的吧，没有图不明白你说的光照不对是什么样子~

你所说的完整的前向渲染shader大概就是指内置的这些包含了所有计算的shader吧，我没有提供是因为一些概念和算法例如SH等不属于我认为的入门内容。而且，我本来的目的就是想要读者看完这本书后可以靠自己的分析去实现其他效果，例如你读了书就应该要有看内置shader（内置的大部分都是surface shader，尤其是要看它们生成的vertex&fragment shader）的觉悟呀~

最后，dot(lightCoord, lightCoord).rr已经说得很明白啦~就是等同于float2(dot(lightCoord, lightCoord).r, dot(lightCoord, lightCoord).r)。dot(lightCoord, lightCoord)是一个标量，也可以认为是一个只有一维的矢量，用.r就可以取到这个分量，两个r是说用分量构建一个二维矢量。我也说了这是swizzle操作，其实你只要谷歌一下cg swizzle就有非常详细的资料。

**Comment by JOKULLIU** [comment]
感谢作者耐心细致的教导。
之前我把顶点和SH光加进去之后，胶囊整个曝光过度了。后头发现是我没有把默认的Skybox取消。把Skybox取消后就正常多了，对比系统自带的Specular也还过得去。所以当时我以为是Lighting-Scene下面的Ambient的影响造成曝光过度。进一步思考，我觉得假设取消Shader里面的UNITY_LIGHTMODEL_AMBIENT.xyz;不让它参与计算，是不是就不受Ambient的影响了呢？但是我这么做了之后，发现调整Ambient Color，还是会对整个场景颜色有影响。所以我怀疑是系统自带的SH光中，依然让Ambient参与了计算，进一步测试印证了这个想法。
当然这样一来会有个尴尬的情况，就是项目中存在Skybox，如果把SH加上，必定曝光过度，我只能被迫削弱了SH光的数值。

**Comment by candycat1992** [comment]
你可以调整Ambient Intensity参数，就不会造成环境光强度过大了~

![qq 20160819105744](https://cloud.githubusercontent.com/assets/5907064/17797489/db0b5200-65fb-11e6-9b7c-8dc6c4010465.png)

**Comment by JOKULLIU** [comment]
惭愧……居然看漏了……

**Comment by candycat1992** [comment]
@HongfeiXu ShadeSHPerVertex的确是已经考虑了环境光颜色，的确不需要在frag里再计算一次了。已经更改了我回答里的代码，感谢~

没什么副作用，直接使用UNITY_LIGHTMODEL_AMBIENT.xyz;作为ambient是最暴力计算环境光的方法，在物理意义上环境光本来就应该是周围其他物体对当前物体的光照影响，使用ShadeSHPerVertex来计算是更好的做法，当然也更费性能一些，因为要用到light probe。
