### ISSUE TITLE
第7章7.2.3法线贴图在切线空间下计算的一些疑问

### ISSUE THREAD

**Issue by happyfire** [candycat1992/Unity_Shaders_Book#290]
书上的例子，包括代码是构建一个模型空间到切线空间的矩阵，然后用这个矩阵，将模型空间的光的方向和模型空间的视线方向变换到切线空间。 但是github上最新的代码：https://github.com/candycat1992/Unity_Shaders_Book/blob/master/Assets/Shaders/Chapter7/Chapter7-NormalMapTangentSpace.shader
里面的方法是构建一个世界空间到切线空间的矩阵，然后用这个矩阵，将世界空间的光的方向和世界空间的视线方向变换到切线空间。
请问这两种方法哪种更好呢？从表面上看，书上的方法，即构建模型空间到切线空间的矩阵，需要的计算更少些，因为顶点属性中的法线和切线就是模型空间的，只要再计算出副切线就可以直接构建矩阵。而下面计算模型空间的光和视线方向貌似也比计算世界空间的方向简单些。那么为啥github上最新的代码使用世界空间呢？

ps 做个广告：这是我第二遍刷这个书，书写的很好，第一遍的时候我是跟着书上的例子在Unity里面操作一遍，第二遍，我是用WebGL写了一个渲染框架，然后在上面用GLSL去写这些效果。欢迎大家star我的项目，谢谢！  https://github.com/happyfire/mini3d.js

**Comment by HardJoker** [comment]
兄弟看这里https://github.com/candycat1992/Unity_Shaders_Book/issues/45

**Comment by spicy-ice** [comment]
亲╭(╯3╰)╮邮件收到啦 ！   O(∩_∩)O~
                                                       -----徐方凯
