### ISSUE TITLE
10.3程序纹理的部分，用了SetProperty的插件，面板改了值没有效果

### ISSUE THREAD

**Issue by fengxiaorui** [candycat1992/Unity_Shaders_Book#30]
代码和例子里的代码一样，面板上改值没有效果，不知道为什么

**Comment by fengxiaorui** [comment]
查了一下发现是还有一个Editor下的SetPropertyDrawer.cs没有导入，导入了之后工作正常，在这个例子里应该是执行频率太快，拖动属性的时候卡顿非常明显

**Comment by candycat1992** [comment]
这是一个很小的插件，在书中P226页有提到哦：
![qq 20160818131524](https://cloud.githubusercontent.com/assets/5907064/17762743/ef91e9de-6545-11e6-931b-820a5a7b50e7.png)

这一节只是一个例子，想要说明什么是程序纹理。卡顿是因为你拖动属性的时候是一直都在调用_GenerateProceduralTexture这个函数，而它的计算量比较大。真实项目里的程序纹理和程序材质肯定是要进行优化和权衡的~
