### ISSUE TITLE
数中的表格

### ISSUE THREAD

**Issue by oOFlyOo** [candycat1992/Unity_Shaders_Book#31]
如果书中的表格可以像图片那样有单独的图片页面，甚至表格方便拷贝收藏就好了

**Comment by candycat1992** [comment]
的确挺好，图的话因为都是自己画的有单独的图片存档，表格都是内嵌到文字里的，所以如果要单独整理出来就要手动一张一张去截图…………工作量很大………………我如果有精力的话会尝试弄一下，谢谢建议 :)

**Comment by oOFlyOo** [comment]
内嵌进文字不可以单独复制出来提供一个html或者doc之类的么
其实我更喜欢文字，方便我搜索，现在我都是自己敲进有道云笔记里面
anyway 谢谢你的书 之前也有在看你的博客 感觉挺不错的

**Comment by candycat1992** [comment]
因为得一页一页翻书把它们复制出来呀……图的话我本来就有专门的文件夹来管理，图本来就是和文字分开的~

谢谢支持！有人喜欢很开心 :)
