### ISSUE TITLE
Page151 7.2.3（9）v.tangent.w

### ISSUE THREAD

**Issue by 777777716** [candycat1992/Unity_Shaders_Book#32]
在原文中写到：“因为和切线与法线方向都垂直的方向有两个”
但是实际上，两向量叉乘只会得到一个向量，因为计算时只会使用两个法则之一，所以得到的结果应该是确定的。
那为何还需要w来确定方向呢？
这个w又是从何而来呢？

**Comment by candycat1992** [comment]
其实在定义切线空间的时候，Z轴方向即切线方向是有无数条的，建模软件在计算切线的时候会选择和UV展开方向相同的那个方向作为切线方向，这样的选择导致如果直接用法线插乘切线的方向也一定会和UV相关，但这可能不是模型的法线方向（可能是反的），因此w会再存储一个信息。

**Comment by 777777716** [comment]
书中说到“w分量决定副切线的方向性”，但如你所说，叉乘的结果可能是相反的，也可能是正确的。
又依据书中给出的计算方法，叉乘结果 * w = 正确结果
1.叉乘结果正确 -> w = 1
2.叉乘结果相反 -> w = -1
w在存储值时事先做了处理，预知了叉乘结果，并将对应“修正值”存储。
所以w并不能决定副切线的方向性，而应该是修正因子（标量）。

**Comment by candycat1992** [comment]
我不明白你的意思，在我看来乘以w决定了副切线到底取哪个方向，这里说的方向性不是说左手性右手性，而是说方向，有什么不对么？

**Comment by 777777716** [comment]
1.w受什么控制（从何而得）
2.w可能的取值
3.叉乘方向 * w = 正确方向
4.
if（叉乘方向 == 正确方向）{
    //w为1
}else{
    //w为-1
}
5.在我看来w已经是事先知道的，那么意味着这就预知了“叉乘方向和正确方向之间的关系”。
6.如果仅仅知道w就可以知道正确方向，那“.叉乘方向 * w = 正确方向”这个想法就是错的，打个比方，一维方向，w表示方向（-1或1），那应该是|A| * w = B，而不是 A * w = B

**Comment by candycat1992** [comment]
是不是有些在概念上太钻牛角尖了？叉乘的结果会得到一个方向，然后w分量又进一步决定了最终的正确方向，没有人说仅仅知道w就可以知道正确方向呀~因为我对建模软件不够了解，因此我没法跟你解释清楚它们到底是怎么生成的。如果你这么想了解可以去建模软件自己生成一个法线贴图试一下呗。你的第5点我没看出来和我的观点有任何冲突的地方啊，本来就都是已知的，建模软件对法线纹理的生成是一个encode的过程，而我们在shader里做的是一个decode的工程，这样说你是不是会明白一些

**Comment by 777777716** [comment]
@candycat1992 
抱歉，这牛角确实钻得太深了。
我上一条回复内容只是简述了一下我的思考顺序和逻辑，感觉自己直接用类代码的东西可能更容易表述意思，并不是提问。
其实理论我都懂了，主要是书中说到“w分量决定副切线的方向性”，我将这句话理解成 “w分量代表了副切线的方向性”，然后认为这句话与实际情况不符。
给你带来困扰，实在不好意思

**Comment by candycat1992** [comment]
没关系~说不定下一次钻牛角尖就能发现新的东西呀

感谢对书的支持 :)

**Comment by xiangwei71** [comment]
@777777716 
這個問題我之前剛好有測試過

可以把下面這個script放到顯示你模型的GameObject上。
```
public class PeekGeo : MonoBehaviour {

    public Transform r;//自己準備1個紅色球
    public Transform g;//自己準備1個綠色球
    public Transform b;//自己準備1個藍色球
    public void createGS()
    {
        Mesh mesh = GetComponent<MeshFilter>().sharedMesh;

        int triCount = mesh.triangles.Length / 3;
        int[] triangles = mesh.triangles;

        Vector4[] tangents = mesh.tangents;
        Vector3[] normals = mesh.normals;
        Vector3[] vertices = mesh.vertices;
        for (int i = 0; i < triCount; i++)
        {
            //只查看你要的索引資料
            //if (i != 33 && i != 18)
            //    continue;

            int v0 = triangles[3 * i];
            int v1 = triangles[3 * i + 1];
            int v2 = triangles[3 * i + 2];





            Vector3 center = transform.position + vertices[v0] ;
            Instantiate(r, center, Quaternion.identity, this.transform);

            Vector3 normal = center + normals[v0];
            Instantiate(g, normal, Quaternion.identity, this.transform);

            Vector3 temp = new Vector3(tangents[v0].x, tangents[v0].y, tangents[v0].z);
            Vector3 tangent = center + temp;
            Transform obj=Instantiate(b, tangent, Quaternion.identity, this.transform);
            obj.name = obj.name + "[("+i+")tangent.w=" + tangents[v0].w + "]";

            center = transform.position + vertices[v1];
            Instantiate(r, center, Quaternion.identity, this.transform);

           

            center = transform.position + vertices[v2];
            Instantiate(r, center, Quaternion.identity, this.transform);

           

        }

    }
}
```
再把下面這個script放到路徑Assets/Editor/的資料夾下。
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

[CustomEditor(typeof(PeekGeo))]
public class PeekGeoEditor : UnityEditor.Editor
{

    PeekGeo behavior;
    void OnEnable()
    {
        behavior = (PeekGeo)target;
    }

    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();

        if (GUILayout.Button("createGS"))
        {
            behavior.createGS();
        }

    }
}
```

測試後應該可以發現，如果你的模形裡的三角形存放的uv是正常的(tangent方向和貼圖的u軸方向一致)
那麼tangent的w都是-1。

以下解譯原因：
3dsmax是右手座標下來觀看和建立資料，在3dsmax裡：
(這裡是用右手法則作cross)
(一)當三角型的uv是正常的(tangent方向和貼圖的u軸方向一致)，tangent的w會是1，在3dsmax裡計算 cross (N,T)*tangent.w就可得到正確的BN。
(二)當三角型的uv是鏡射的(tangent方向和貼圖的u軸方向相反)，tangent的w會是-1，在3dsmax裡計算 cross (N,T)*tangent.w就可得到正確的BN。



再來看看當模型從3dsmax被放入unity會怎麼被處理：
//////////////////////////分隔線

在3dsmax是z軸向上，假設在3dsmax裡建了1個模型，這個模型是一隻打開的右手掌，而且中指的方向指向世界的z軸，那這個手掌在3dsmax裡看起來就是立起來的(手心指向y軸)。

unity是左手座標(在還沒到view space前都是)，而且y軸向上. 
「如果把3dsmax建的右手掌，沒作任何處理」就放進unity render，畫出來會是什麼？
你可以自己在筆記本上畫看看...
應該會發現1個「左」手掌平放在世界上，而且手背是向上的(在unity裡Y軸向上)

變成左手了，而且是平放的，這樣看起來看3dsmax裡完全不一樣阿怎麼辦？
所以Unity「可以」對資料作下面這樣的處理
(1)先定義這樣的3軸對從3dsmax來的模型資料作一次轉換
X軸 (-1,0,0)
Y軸 (0,1,0)
Z軸 (0,0,1)
這樣一來至少可以得到平放的「右」手掌

(2)然後他對物件transform的x軸旋轉了-90度
這樣右手掌就又立起來了。


至於tangent，在Unity裡可以選擇[import]或是[cauculate tangent space]。
不管選了那一個，因為有發生(1)這個轉換，所以tangent在進入Unity後也被改變了。
這時在shader(用左手法測)裡作 cross (N,T)得到的BT，就需要乘上-1。
(你可以自己在筆記本上畫看看)
所以原本在3dsmax裡tangent.w是1，到了unity就變成-1了。

//////////////////////////分隔線

**Comment by xiangwei71** [comment]
又發現一種新的情況
就是當在3dsmax設定smooth時，頂點上的法向量Normal會由鄰近三角形原來的法向量作平均(大概吧)。
放入Unity測試後，發現這時Tangnet不再相切於平面了。

https://goo.gl/photos/YSPPdbzWmUaR1w4x5

**Comment by xiangwei71** [comment]
再可視化一次頂點的tangent，感覺這樣比較能說服自己
https://goo.gl/photos/kdht3gsNiRrDnxLt7

**Comment by xiangwei71** [comment]
當沒有smooth時，4個頂點上的normal變化，可以想像成1張名片
當smooth時，4個頂點上的normal變化，可以想像成你把4個手指放在名片上，向內擠壓
