### ISSUE TITLE
12.4 高斯模糊里的纹理采样按照for循环来进行采样好像会有一个纹理坐标用不上

### ISSUE THREAD

**Issue by pengyanmin** [candycat1992/Unity_Shaders_Book#328]
`v2f vertBlurVertical(appdata_img v) {
    v2f o;
    o.pos = mul(UNITY_MATRIX_MVP, v.vertex);

    half2 uv = v.texcoord; 

    o.uv[0] = uv;
    o.uv[1] = uv + float2(0.0, _MainTex_TexelSize.y * 1.0) * _BlurSize;
    o.uv[2] = uv - float2(0.0, _MainTex_TexelSize.y * 1.0) * _BlurSize;
    o.uv[3] = uv + float2(0.0, _MainTex_TexelSize.y * 2.0) * _BlurSize;
    o.uv[4] = uv - float2(0.0, _MainTex_TexelSize.y * 2.0) * _BlurSize;

    return o;
}`

`fixed4 fragBlur(v2f i) : SV_Target {
    float weight[3] = {0.4026, 0.2442, 0.0545};

    fixed3 sum = tex2D(_MainTex, i.uv[0]).rgb * weight[0];

    for (int it = 1; it < 3; it++) {
        sum += tex2D(_MainTex, i.uv[it]).rgb * weight[it];
        sum += tex2D(_MainTex, i.uv[2*it]).rgb * weight[it];
    }

    return fixed4(sum, 1.0);
}`

不懂就问，这两段代码，这个For循环，高斯采样的纹理这样遍历是不是会有一个值遍历不到，1 2 2 4，是不是少了个3。
虽然结果只有细微区别-- = - =

**Comment by spicy-ice** [comment]
亲╭(╯3╰)╮邮件收到啦 ！   O(∩_∩)O~
                                                       -----徐方凯

**Comment by pengyanmin** [comment]
额，好像更新版本里有对这个进行更新=- =，我没看到。
