### ISSUE TITLE
关于TEXCOORD数量的问题

### ISSUE THREAD

**Issue by JOKULLIU** [candycat1992/Unity_Shaders_Book#33]
作者你好，我又来麻烦你了。
在书的110页说到了TEXCOORD数量受到Shader Model的限制。我的一个Shader因为用到多通道混合纹理，所以数量上比较多，我的两个结构体是这样写的：
```
struct a2v{
    half4 vertex : POSITION;
    half2 uv0 : TEXCOORD0;
    half2 uv1 : TEXCOORD1;
    half2 uv2 : TEXCOORD2;
    half2 uv3 : TEXCOORD3;
    half2 magmaUV : TEXCOORD3;
    half3 normal : NORMAL;
};
```
还有一个是：
```
struct v2f
{
    half2 uv0 : TEXCOORD0;
    half2 uv1 : TEXCOORD1;
    half2 uv2 : TEXCOORD2;
    half2 uv3 : TEXCOORD3;
    half4 pos : SV_POSITION;
    half4 objectPos : TEXCOORD4;
    half3 normal : NORMAL;
    half3 sh : TEXCOORD5;
    SHADOW_COORDS(6)
    half2 magmaUV : TEXCOORD7;
};
```
上述代码都正常工作。
当然我没有在代码里面添加
#pragma target 3.0
实际上加不加，对上述的代码都没有什么影响，所以我觉得上面并没有超出8个的限制。
问题出在a2v的这一句：
half2 magmaUV : TEXCOORD3;
如果我改成：
half2 magmaUV : TEXCOORD4;
马上会报错：
Shader error in 'WarShip/Shader_Scene_Volcano': Vertex program 'vert': unknown input semantics TEXCOORD/4
 (on d3d11)
我猜测是TEXCOORD数量引起的，但是#pragma target 3.0这句代码依然是加不加都没影响。
混合纹理这个技术是学自《Unity着色器和屏幕特效开发秘笈》，它那个第29页的代码也是这个问题，照着写，直接报错：
Too many texture interpolaters......would be used for ForwardBase pass......（嗯……前向……）
当时我的解决方案只能是让Input结构体里面的uv变量不超过2个。
那本书除了数不清的翻译错误之外，查勘误极其麻烦，当然里面的介绍的技术还是比较实在，我知道你也读过……这次学习你的书后重新编写这部分代码，成功让TEXCOORD达到4个，但是第5个就……
这次我应该怎么办呢？

**Comment by candycat1992** [comment]
struct a2v{
    half4 vertex : POSITION;
    half2 uv0 : TEXCOORD0;
    half2 uv1 : TEXCOORD1;
    half2 uv2 : TEXCOORD2;
    half2 uv3 : TEXCOORD3;
    half2 magmaUV : TEXCOORD3;
    half3 normal : NORMAL;
};

首先TEXCOORDX是不可以共用的，不能都使用TEXCOORD3。其次，你这样的用法很浪费，我在书里说过可以合并两个uv到一个插值寄存器的，比如定义一个half4 uv，uv.xy存一个UV，uv.zw存一个UV，这样就够用了。

嗯那本书看过~但主要是讲surface shader的，实际手游项目还是不推荐用。但书里面的很多算法还是值得学习的~

**Comment by JOKULLIU** [comment]
谢谢作者解答，我重写的代码，减少了一半的寄存器。
有个地方不是很明白，你在P141中写到：“a2v结构中定义了一个新的变量texcoord，这样Unity会把模型的第一组纹理坐标存储在该变量中。”
这里我误以为a2v中，第一组纹理坐标储存在第一个TEXCOORD0，第二组纹理存储在TEXCOORD2……
这里我用了5张图，所以一口气写了5个寄存器。
改写之后发现，a2v中只使用一个寄存器就够了，只是在v2f中把它们的坐标分开存储。
问题是，为什么a2v中只使用一个寄存器就够了呢？难道Unity只是把a2v中的寄存器作为跳板，一个跳板就够了？

**Comment by candycat1992** [comment]
这个你可以在去重读P109页的5.4节。TEXCOORD0这些语义在不同的结构体意义是不同的。如果你看完之后还有疑问再来讨论~

**Comment by JOKULLIU** [comment]
谢谢作者，我读了，但还是对“第一组纹理……”这个说法琢磨不透。
PS：另外顺便还拜读了你《写给学弟学妹的一封信》和《********》后面这个文章标题我匿了^-^

**Comment by candycat1992** [comment]
因为你不是美术，你去问美术就知道什么是第一组纹理啦。一个模型可以有多套纹理，这是被保存在它们的模型文件里面的，比如FBX、OBJ文件里，Unity会读取这些数据，并把这些特定含义的数据放到对应语义修饰的变量里。

**Comment by JOKULLIU** [comment]
谢谢，我懂了，不过我是如假包换学美术出身后来转程序的-_-!
一时没反应过来……天资不佳啊。
