### ISSUE TITLE
P49 除和除以的问题

### ISSUE THREAD

**Issue by Wecica** [candycat1992/Unity_Shaders_Book#34]
第三段末“为了对矢量进行归一化，我们可以用矢量的模除以该矢量来得到。” 而下面公式则是矢量除以矢量的模。
应把“以”字去掉 。
可能是我太咬文嚼字了，除和除以是反的，查了一下，提出来，希望乐乐大大确定一下。
PS:我前几天买的书，却没有给我发第二版......

**Comment by candycat1992** [comment]
应该是“用矢量除以该矢量的模来得到”。很细心，感谢勘误~

额版次问题我也没有办法 %>_<%，网上买的书的确可能会滞后……

**Comment by Wecica** [comment]
嗯
