### ISSUE TITLE
p67 倒数第五段第一句是否应该删除？

### ISSUE THREAD

**Issue by funing0912** [candycat1992/Unity_Shaders_Book#37]
倒数第4段：”绕坐标系 E 下的 z 轴旋转 θz，绕坐标系 E 下的 y 轴旋转 ....“
倒数第5段：“绕坐标系 E 下的 z 轴旋转 θz，在坐标系 E 下绕 z 轴旋转 θz后的新坐标系 E'下的...“

我觉得倒数第5段的第一句好像有点奇怪，想问确认下 
（这部分，网上的第四章pdf 版本和书里是一样的）

**Comment by candycat1992** [comment]
这里是正确的，第一句话具体你是觉得哪里奇怪呢

**Comment by funing0912** [comment]
我最初以为“绕坐标系 E 下的 z 轴旋转 θz，在坐标系 E 下绕 z 轴旋转 θz后...” 是表达重复的，抱歉是我理解错了 ;P
