### ISSUE TITLE
p109 倒数第二段“用于描述输出结构体v2v”应该是 “v2f”吗？

### ISSUE THREAD

**Issue by funing0912** [candycat1992/Unity_Shaders_Book#38]
我看网上的勘误里说此处应该是 “a2v”，但在该段最后一句 “而在输出结构体 v2f 中...” 说的是 v2f，我觉得这两处 “输出结构体” 说的是不是一个东西？

**Comment by candycat1992** [comment]
你好，已更正，应该是v2f
