### ISSUE TITLE
p127 第二段“（3）新建一个 Unity Shader。”在 ")" 和 "新"之间的间距与其他段落不统一

### ISSUE THREAD

**Issue by funing0912** [candycat1992/Unity_Shaders_Book#39]
我纠结了一会儿要不要提上来... 虽然不重要，但还是期望能越来越好...

**Comment by candycat1992** [comment]
哈哈谢谢你的厚爱啊！

我看了下word原稿，")" 和 "新"之间和其他段落的字符是一样的，印刷稿出现这样的原因可能是因为这一行最后一个单词Shader是英文的，导致为了给它腾地方缩进了一点。这个勘误估计出版社也无能为力。

没事多小的都可以哈，我也曾给出版社提过某个公式图片有点大，希望稍微缩小一点点的问题，不知道排版人员看到作何感想，哈哈……再次感谢勘误 :)

**Comment by funing0912** [comment]
=D
