### ISSUE TITLE
勘误中 p132 顶部的反射方向计算公式为啥与 p124 的公式不一样呢？

### ISSUE THREAD

**Issue by funing0912** [candycat1992/Unity_Shaders_Book#41]
勘误表中说 p132 的公式是：r = l-2(n•l)n
p124 页的公式是： r = 2(n•l)n - l

**Comment by funing0912** [comment]
意思明白了｀

**Comment by candycat1992** [comment]
虽然close了但还是说一下~两个公式之所以是反的是因为图示里面的光照方向l是反的~

**Comment by funing0912** [comment]
哇，收到您的邮件我太吃惊了。真的非常感谢您如此细心负责的回复｀我很喜欢您的书，目前刚学完第七章｀继续努力中｀[😝]

再次表示感谢｀


________________________________
