### ISSUE TITLE
P128 第二个代码段中的fram，应该是from?

### ISSUE THREAD

**Issue by xdestiny110** [candycat1992/Unity_Shaders_Book#44]
P128 第二个代码段中有句注释

> // Transform the normal fram object space to world space

这里的fram应该是from吧？

另外就是，为什么这段代码要写成左乘转置矩阵的形式呢？直接右乘不是很顺手么？一眼看下去还以为`_World2Object`那个地方写错了呢···

**Comment by candycat1992** [comment]
首先感谢勘误，注释的确有问题~

其次，那里是必须那么写的，请参考[issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/45)。

**Comment by xdestiny110** [comment]
哦哦，原来忽略了这样一个细节...感谢解答~

**Comment by CadenJi** [comment]
@candycat1992 我买的2020年11月第25次印刷的版本注释的错误还没有更正过来
