### ISSUE TITLE
电子版

### ISSUE THREAD

**Issue by oOFlyOo** [candycat1992/Unity_Shaders_Book#46]
希望可以在亚马逊上搞个kindle电子版的，方便查看
平常上班，实在是不好意思把书拿出来，我已经买了书了，但是还是再有个电子版比较方便

**Comment by candycat1992** [comment]
为啥不好意思……我实习的公司也有很多人在看呀，有美术也有程序，没什么不好意思吧

电子版的话之前跟编辑提过，会在后续考虑的~
