### ISSUE TITLE
关于13.2节运动模糊特效的问题

### ISSUE THREAD

**Issue by adachigit** [candycat1992/Unity_Shaders_Book#50]
作者你好
书中13.2节使用深度纹理实现了运动模糊效果，其中在计算当前像素位置在世界空间下的坐标时使用的代码是这样的：
`			float d = SAMPLE_DEPTH_TEXTURE(_CameraDepthTexture, i.uv_depth);
			float4 H = float4(i.uv.x * 2 - 1, i.uv.y * 2 - 1, d * 2 - 1, 1);
			float4 D = mul(_CurrentViewProjectionInverseMatrix, H);
			float4 worldPos = D / D.w;
`
其中H是当前像素在NDC下的坐标，也就是世界坐标经过VP矩阵转换后得到的齐次坐标再除以w分量的结果。现在我们用这个H直接使用VP矩阵的逆矩阵进行变换，得到的结果应该是缺少w系数的坐标，按说最后应该是D * D.w，但不知道这里为什么要除以D.w。
我看了《GPU Gems 3》里面的文章，作者对推导过程也没有做详细的解释，所以我想问一下这里做除法的数学推导是怎么做出来的。
多谢了。

**Comment by candycat1992** [comment]
因为我们最终得到的应该是世界空间的点坐标，这个坐标很明显的特征就是它的w分量应该是1。而代码在从H得到D的过程中是不会保证w分量为1的，所以最后需要除以w分量保证它是一个有效的点坐标。

**Comment by adachigit** [comment]
多谢作者的解答，我想我应该明白了。：）

**Comment by vipshenji** [comment]
作者您好:
关于这一节能否接着问个问题 ：
Matrix4x4 currentViewProjectionMatrix = camera.projectionMatrix * camera.worldToCameraMatrix;书中代码中得到的是当前帧的视角*投影矩阵（VP矩阵）。因为变换的结果是依赖于变换顺序的。想请问下这个相乘顺序能麻烦作者给解释下。  看你第四章说我们使用的是列矩阵，因此阅读顺序是从右到左不是很明白。

**Comment by candycat1992** [comment]
@vipshenji 你好，你可以再仔细阅读一下第4章的相关内容，在纸上做一下练习题，仍然不懂的话欢迎再来更详细地提问 :)

**Comment by cookgoing** [comment]
乐乐你好；我对这个地方也不理解；如果不看最后的D/D.w;单看前面的，那个H表示的是NDC下的坐标，而_CurrentViewProjectionInverseMatrix表示的是裁剪空间到世界空间的变换；按照逻辑来说，应该要先把H转换成裁剪坐标，再做矩阵变换吧！所以我觉得上面的逻辑是有问题的，但是最后由于又有了d/d.w;所有即便前面的逻辑不好懂，却能保证最后的结构一致，是这样子吗？
