### ISSUE TITLE
关于12章运动模糊问题

### ISSUE THREAD

**Issue by vipshenji** [candycat1992/Unity_Shaders_Book#51]
作者 您好
想请问下关于书中第12章屏幕后处理效果之运动模糊中我的两个个疑问 

我理解您的思路应该是当前帧和前一帧数据做一个accumulation。用到了两个Pass。

第一个问题：
       您用到accumulationTexture.MarkRestoreExpected()这样一个函数，网上搜的内容也比较少，看你的解释是不让unity把上一帧（accumulationTexture）的信息删除掉。但是 Graphics.Blit(src, accumulationTexture, material)这句就是记录了上一帧accumulationTexture的值 代码里也没有清空accumulationTexture值得操作。所以本来值应该就是一直保存的啊

主要就是第二个问题：
第一个pass是做Alpha Blend。 ColorMask RGB 只写入rgb数据到颜色缓冲区。那这时候的颜色缓冲区的A值还是上一帧的A值（也就是目标缓冲区里的A值 ，是不是1？）让我理解应该就到此为止就行了。但是您又进行了第二个Pass。书中说是为了确保写入的是1。但是我自以为好像没有必要，做了很多实验。甚至我极端的把第二个Pass 写入的a值设置为0。运行起来感觉也没有什么变化。

能否请解答下 我理解的第一个pass思路是不是正确的，还有就是第二个pass存在的必要性（一定是有作用的，强大的作者肯定有自己的道理）。

**Comment by candycat1992** [comment]
第一个问题：
[RenderTexture.MarkRestoreExpected](https://docs.unity3d.com/ScriptReference/RenderTexture.MarkRestoreExpected.html)其实只是起到**表明**我们需要进行一个渲染纹理的操作，来不让Unity发出警告误以为是忘记清空了。正如文档里所说：
> If your rendering effect absolutely needs a RenderTexture restore, you can call this function to indicate that yes, a restore is expected, and Unity will not issue a warning here.

第二个问题：
首先执行Motion Blur的时候缓冲区的A通道不一定是1哦，如果有半透明物体或者背景色有透明有通道的话就不一定为1了。书里也没有说是为了确保是1，而是说维护渲染纹理的透明通道值，也就是保证在执行Motion Blur这个后处理前后、颜色缓存透明通道的值是保持不变的，这是为了保证如果有后续屏幕后处理的话不会有什么奇怪的事情发生。你说到“至我极端的把第二个Pass写入的a值设置为0。运行起来感觉也没有什么变化”，这是因为你后面没有进行其他和透明通道相关的处理，而直接显示到了屏幕上，自然不会有影响。但如果你把第二个Pass写入的a值设置为0、然后又进行一个和透明通道有关的后处理，例如：
`fixed4 fragRGB (v2f i) : SV_Target {
	fixed4 tex = tex2D(_MainTex, i.uv);
	fixed3 col = lerp(tex.rgb, fixed3(1.0, 0.0, 0.0), 1.0 - tex.a);
	return fixed4(col, 1.0);
}`

上面这个完全是瞎写的哈，就是为了演示使用透明通道和红色混合的结果。如果此时你把第二个Pass写入的a值设置为0，很显然就是错误的，这样整个屏幕都会是红色，而正确的结果应该是根据_MainTex的透明值进行混合，你可以往场景里放一些透明物体来看看效果。

其实，我写书的时候也在考虑这个Pass的必要性，如果没有这个Pass理论上A通道应该不会受这个屏幕后处理的影响。但我当时写的时候是参考了内置的Motion Blur，恩我担心是我考虑不周全没有明白官方的奥妙所以保留了这个Pass，确保A通道的正确性。个人感觉在没有发现明显错误的时候可以考虑去掉它。

**Comment by vipshenji** [comment]
Dear 群主 ，今天才看到你回复。首先表示非常的感谢。解答的文字比我的提问的还多。真是十分十分的感谢。
但是这里面还是有个问题，我理解了半天感觉很迷糊。需要您帮忙再看看。

就是按您举的栗子，我依旧将第二个Pass写入的A值设置为0。然后第一个Pass用您举的栗子想试试看，但是发现没有什么变化，我其实本以为也会像您说的那样整个屏幕会是红色的了，但是貌似是没有。还烦请作者帮忙再想想这里是什么意思。代码如下：
	fixed4 fragRGB (v2f i) : SV_Target
 {
			    fixed4 tex = tex2D(_MainTex, i.uv); 
		    fixed3 col = lerp(tex.rgb, fixed3(1.0, 0.0, 0.0), 1.0 - tex.a);
    			return fixed4(col, 1.0);
		}
		
		half4 fragA (v2f i) : SV_Target
 {
     			return fixed4(1,1,1,0);
		}
		
		ENDCG
		
		ZTest Always Cull Off ZWrite Off
		
		Pass {
			     Blend SrcAlpha OneMinusSrcAlpha
    			 ColorMask RGB
    			 CGPROGRAM

			     #pragma vertex vert  
			     #pragma fragment fragRGB  
			     ENDCG
		}
		
		Pass 
{   
     			Blend One Zero
			     ColorMask A
			   
     CGPROGRAM  
	
     			#pragma vertex vert  
			     #pragma fragment fragA
			  
			     ENDCG
		}

**Comment by candycat1992** [comment]
不是直接修改第一个Pass，是在之前Motion Blur的后面另建立一个后处理：
![2291246f-fb14-4604-b0be-29c49617596c](https://cloud.githubusercontent.com/assets/5907064/19257997/d95ed984-8fa6-11e6-9bd0-59e75a662076.png)

这个新的后处理shader的fragmenst shader是：
`fixed4 fragRGB (v2f i) : SV_Target {
	fixed4 tex = tex2D(_MainTex, i.uv);
	fixed3 col = lerp(tex.rgb, fixed3(1.0, 0.0, 0.0), 1.0 - tex.a);
	return fixed4(col, 1.0);
}`

其实就是根据屏幕纹理的透明通道去显示红色，越透明的地方也发红。因为当前的Scene_12_6都是不透明材质的，你可以把它们都换成透明材质的，比如Legacy的Transparent Shader。最后，还需要把主摄像机的Background颜色的透明通道调小，让它透明，这样最后的屏幕纹理透明通道才会是透明的。最后大概长这样：
![2016-10-11 11 32 26](https://cloud.githubusercontent.com/assets/5907064/19258013/e383c8ac-8fa6-11e6-83c7-9e56289a63aa.png)
如果你直接把Motion Blur的第二个Pass写入的A值设置为0的话，就直接是全红的了：
![2016-10-11 11 33 34](https://cloud.githubusercontent.com/assets/5907064/19258017/ec397d5c-8fa6-11e6-96c1-ad50f5ce22a9.png)

**Comment by vipshenji** [comment]
hi ，谢谢作者了 ，您的试验我是明白。
您的试验中用到两次屏幕后处理，第一次屏幕后处理中如果把第二个Pass把透明通道A 设置为0，然后再进行第二次屏幕特效处理根据frag计算 ，屏幕呈现为红色的。说明在同一帧情况下第二次屏幕后处理取得的_MainTex 的A是0的。
但是我的搞不懂的是，如果整个过程就一次屏幕后处理。第一个Pass 就执行采样_MainTex,根据A值的不同设置红色或是原颜色（和运动模糊没有关系），第二个Pass把透明通道A设置为0。但是接下来下一帧到来时候，执行第一个Pass时，按我之前的理解取得的_MainTex的A值0，屏幕应该为红色的。但是事实上还是显示的还是原颜色，说明下一帧重新执行shader取得的_MainTex的A值是不考虑上一帧的。不知道是不是这样呢。

**Comment by candycat1992** [comment]
额并不是，每一帧开始之前是会Clear当前帧缓存的，因此_MainTex每一帧都会重新绘制，不会保留上一次的结果。会被保留的是accumulationTexture：
`Graphics.Blit (src, accumulationTexture, material);`

**Comment by vipshenji** [comment]
哦哦哦 装牛角尖了哈  忘记Clear这个操作了 。
再问一个弱智的问题哈 屏幕特效最后上屏的是只有RGB颜色值？ 比如第二个Pass把A设置为0.5。想半透明。最后上屏是没有用的，只取得RGB三通道值上屏？

**Comment by candycat1992** [comment]
在PC上，最后一次会直接画到帧缓存中，你大概是和普通的透明图片混为一谈了，渲染不是这么粗暴的。按你的意思，是说这张图片的透明度会和背景混合，从来看起来是半透的，但你仔细想想就知道如果只有一次后处理的话就直接画上去了，不会再混合了。不要总是想当然。

**Comment by vipshenji** [comment]
好的 谢谢作者

**Comment by songtm** [comment]
@candycat1992  如果这样写是不是就可以不用第二个pass了呢?
Blend SrcAlpha OneMinusSrcAlpha, One Zero
ColorMask RGBA
