### ISSUE TITLE
关于矩阵变换函数里的参数

### ISSUE THREAD

**Issue by Rochester-Ting** [candycat1992/Unity_Shaders_Book#52]
最近刚开始学习shader,我看书上在进行世界变换时习惯这样写:
`o.worldNormal = mul(v.normal,(float3x3)unity_WorldToObject);`
想请教一下,上面的写法和下面的写法是否有什么区别:
`o.worldNormal = mul((float3x3)unity_ObjectToWorld,v.normal);`

**Comment by funing0912** [comment]
https://github.com/candycat1992/Unity_Shaders_Book/issues/45

**Comment by Rochester-Ting** [comment]
如果是矩阵需要计算,而这个矩阵又不容易算,所以采用转置矩阵并把参数放到后面的话我可以理解.但是这里unity_WorldToObject和unity_ObjectToWorld都可以直接获取,并不需要手动计算,所以我想知道为什么作者会选择使用前面那种写法呢.

**Comment by candycat1992** [comment]
额@funing0912 同学已经给你说了[相关issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/45)，所有提这个问题的同学我认为都没有仔细看第四章甚至是代码下面的解释……建议你再仔细看下第四章以及第一次在shader里进行法线变换时代码下面的解释，已经解释过多次了。
