### ISSUE TITLE
关于13.3全局雾效小节中重建世界坐标的疑问

### ISSUE THREAD

**Issue by Sharkafuc** [candycat1992/Unity_Shaders_Book#54]
先佩服小姊姊的书！难得的入门教材，太棒了！</br> 再说我拿到书看的如痴如醉，但是在13.3小节遇到了一个疑问，困扰了我2天。</br> worldPos = _WorldSpaceCameraPos + linearDepth * interpolateRay </br> 我理解render texture中某像素对应顶点的世界坐标的求法是，摄像机的世界坐标+该像素对应顶点相对于摄像机的坐标偏移向量。 </br>但我对linearDepth * interpolateRay是否能代表坐标偏移向量有疑问。主要是方向问题。</br> linearDepth是视角空间的深度值，是float是标量，那么主要看interpolateRay的方向。</br> 而书中求得的interpolateRay只有4个方向，
Vector3 topLeft = cameraTransform.forward * near + toTop - toRight;
float scale = topLeft.magnitude / near;
topLeft.Normalize();
topLeft *= scale; 
这是TL,我也明白同样求得了TR，BL，BR。它们代表的方向是，摄像机到近裁剪平面的4个角落点的方向。而interpolateRay就是根据所求像素点在render texture中的哪个四分块，选择其中一个方向。o.interpolatedRay = _FrustumCornersRay[index];
我的问题在于，如此计算出来的世界坐标，不就都在视锥体的4条边界上了么，因为按我理解摄像机的世界坐标不会动，偏移向量的方向也是可数的（4选1）。我觉得偏移向量的方向应该和它在视锥体中的位子相关。（我想到的方法就是变换矩阵的逆变换，就是13.2小节的方法）
以上就是我的问题，我实在是没想明白如何理解得到世界坐标。希望能得到解惑，感激不尽！

**Comment by candycat1992** [comment]
你好，首先感谢对书的肯定，作为作者每次看到这样的评价都很开心 :)

这个问题在于你忽略了从vertex shader到fragment shader的插值过程。代码的确是在vertex shader只选择了四个方向中的一个，但到了fragment shader里，它接收到的方向值已经是对各个顶点的interpolatedRay插值后的结果，所以并不会出现都在边界上的结果。

**Comment by Sharkafuc** [comment]
哦！非常感谢！

**Comment by DEVILPXCE** [comment]
非常感谢
