### ISSUE TITLE
关于绘制顺序的疑问

### ISSUE THREAD

**Issue by iiley** [candycat1992/Unity_Shaders_Book#55]
谢谢冯乐乐的shader书籍，最近学习shader，发现《Unity Shader入门精要》几乎是目前市面上能买到的最好的同类书籍了，文笔非常好，讲解得也非常易懂，一口气看到16章。
但是对于绘制顺序的内在原理，始终想不明白，疑问如下：
在16.6.1，文中你提到“Transparent”“Overlay”队列的物体，总体上是按照从后往前绘制的，请问这个排序是否是由GPU自动完成的，我们可以编写自己的排序算法吗？
在第8章，你引出了循环重叠的案例，并且最后一句“下面，让我们就来看一下Unity是如何解决排序问题的。” 但是在整个第八章，没有看到解决方案，渲染队列只是解决了不同队列之间的顺序，并没有解决循环重叠的问题。像素级别的排序是否存在？
对于图8.4的例子，我很好奇，GPU自动对物体进行排序的话，究竟是选择物体中的哪个点作为深度，我的猜测是物体的中心点（或者最靠近摄像机的点？）

最后非常感谢作者的奉献，此书对我帮助非常大！

**Comment by candycat1992** [comment]
你好，不是GPU完成的，是在CPU上由Unity按照一些基准点，例如网格的中心点，对所有该队列内的网格进行排序，然后再加以渲染。这样网格级别的排序是无法达到百分百正确的，你可以参照8.1节。额我觉得除非有源码不然这个内部实现很难修改的吧。如果是少量物体的话，你可以直接给物体A赋予Queue+1、给B赋予Queue+2来排序，每个Queue只有一个物体即可。

最后一句不是说可以解决循环重叠的问题，你再读一遍可以发现，如果不分割网格的话这种循序重叠是没法得到正确的排序的，Unity的方法也是这种传统的排序方法。文中已经说明了这种情况下的解决方法之一是拆分网格。P164页下面也提到了一些其他解决方法，例如让透明通道更加柔和，或者使用开启深度写入的半透明效果。而像素级的排序就是传统不透明物体利用深度缓存的方法，可以逐像素地比较深度值。

对于图8.4，上面已经说明这是由CPU排序完成的，每个引擎或者引擎版本都可能不同，记得之前在论坛里有人提到过Unity当时的版本是靠网格中心排序的，但不要过度依赖这个排序标准，就记住排序是不精确的，出现穿插是经常会遇到的问题。

感谢对书的支持 :)

**Comment by iiley** [comment]
谢谢，原来是Unity自己做了排序工作，这个提示很重要，正好也呼应了Unity粒子系统里面提供Sort Mode的情况，果然是CPU完成的，这说明理论上我们可以控制它了。
我当前的项目需要大量使用半透明，对这块的原理非常的好奇，刚刚在一个群里请教了一些朋友，发现了一些方案，比如depth peeling等Order-independent transparency方法，参见：https://en.wikipedia.org/wiki/Order-independent_transparency
正在研究中，希望这些提示对有同样疑问的同学有所帮助。
PS：期待第二版能够跟深入一些，我必须购买。 ：）

**Comment by candycat1992** [comment]
关于OIT，我也有在Unity里实现过一个项目[OIT_Lab](https://github.com/candycat1992/OIT_Lab)，你提到了depth peeling也有实现，但可能性能上需要继续优化。

第二版我也有开[issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/48)征集意见，如果你有好的建议可以在下面留言 :)

**Comment by iiley** [comment]
Cool，有实现太好啦，这就去看看。 ：） 
嗯，好的，我再多研究研究，有建议一定留言。

**Comment by foreverthinker** [comment]
刚买了书，等看完了再来留言。
