### ISSUE TITLE
关于13.3节全局雾效问题求解

### ISSUE THREAD

**Issue by vipshenji** [candycat1992/Unity_Shaders_Book#56]
感谢作者的书 ，让我学习到shader很多知识，同时也感谢作者的耐心，之前已经解答了我一些问题，自己感觉收获很多。
现在我看到了第13章的全局雾效，觉得有些难度。也看到之前有个同学在这里关于这节也是提过问题，但是我觉得我理解的程度还没有他深。所以就单独再提issue问下。
问题1、在通过深度纹理重建世界坐标 worldPos = _WorldSpaceCameraPos + linearDepth \* interpolateRay这里得到的世界坐标是否准确，是否就是他Transform组件的世界坐标xyz？感觉上一节在讲运动模糊时运用的矩阵逆变换的方式感觉更能理解点，可能是对于linearDepth*interpolateRay这个还是不能理解；
问题2、看代码在求TL、TR、BL、BR这四个向量时都看懂了 ，但是后面说到相似三角形计算scale就看不懂了，为什么会有相似三角形，我理解除非像素的顶点都在视锥体的边缘处才会存在相似三角形，如果一个点在视锥体以内的话，应该就没有相似三角形 ，我的理解如下图所示：
![image](https://cloud.githubusercontent.com/assets/22514606/19544500/fd5ac3ae-96b1-11e6-84d1-ef3f3dd53569.png)
问题3 、在vertex shader为什么只选择了四个方向中的一个，您说是到了fragment shader进行了插值，这个插值能否详细解释下，因为比如四个区域中的一块里面有很多个顶点，仅仅通过视锥体边界中的同深度值的一个向量怎么能插值得到视锥体里面同深度那个面上很多顶点的方向向量。这点应该就是不理解这节的关键。能否请作者讲解下。

**Comment by candycat1992** [comment]
我先回答问题3，因为这个是所有推导的基础。

**问题3**：利用Graphics.Blit进行屏幕后处理，其实本质上是在近裁剪平面上放置了一个四边形（quad），这样这个四边形就可以覆盖整个屏幕，然后，我们会使用自定义的材质绘制这个四边形（也就是第三个Material参数），达到屏幕后处理的目的。因此，在使用Graphics.Blit进行后处理的时候，只会有四个顶点，分别位于近裁剪平面的四个角。这就意味着vertex shader也只会在这四个顶点上进行，这四个顶点分别会选定自己对应的那个ray值，这是个一对一d的关系，而不会出现你说的有很多顶点共用一个ray的问题。下面是Frame Debugger查看这一步后处理的图片，你可以看到其中的顶点数目是4。

![2016-10-20 15 48 11](https://cloud.githubusercontent.com/assets/5907064/19550613/db5ea9de-96dc-11e6-8358-cf0022fc815c.png)

我再来说问题1和问题2。也就是到底怎么从depth求得世界坐标。最根本的公式是：

_世界坐标 = 摄像机的世界坐标 + 该点到摄像机的偏移值_

这点是很明白的。摄像机的世界坐标非常容易得到，那么问题就是求该点到摄像机的偏移值。我们先不管书里面的推导内容，看下面这张图（额需要点空间想象能力…）：
![fog_cont](https://cloud.githubusercontent.com/assets/5907064/19551558/53b775b8-96de-11e6-97ff-05b4057cafa7.png)

这张图里面，我们已知摄像机的世界坐标O，要求得任意一点P到O的偏移值OP。然后我们就可以P = O + OP得到最后的世界坐标。其中，灰色的平面是摄像机空间中的xz平面，摄像机在平面中的位置就是O。点C是向量OP和近裁剪平面的交点，A和B分别是P和C在xz平面上的投影。我们已知P对应的深度值depth（由深度纹理采样并处理后得到），以及近裁剪平面的距离Near。

那么，OP怎么求呢？那就是相似三角形。你说相似三角形只在边界上成立是不对的，这张图里面P的位置是任意的，它在视锥体内，但不一定在裁剪平面的边界处。这个相似结论是：

_depth/|OP| = Near/|OC|_              (1)

如果P在近裁剪平面的某一个顶点处的话，就会得到P277的倒数第三个公式；如果你从最上方往下看这张图的话，就是书上P278上的图13.7。我们现在来证明一下为什么有这个相似比。我们先看xz平面上的相似三角形，这个就是P278上的图13.7。很明显我们可以有：

_depth/|OA| = Near/|OB|_              (2)

而我们再看相似三角形OBC和OAP，可以有：

_|OA|/|OP| = |OB|/|OC|_               (3)

结合等式(2)(3)我们就可以得到(1)了。这样一来，我们的目标量

P到摄像机的偏移值 = OP = OC/|OC| * |OP| = OC/|OC| * |OC| * depth / Near = depth * (OC / Near)。

所以说，那个神秘的interpolatedRay就是OC / Near，也就是当前片元到摄像机的射线再除以Near。而这个interpolatedRay是可以由后处理时覆盖屏幕的四个顶点它们各自对应的interpolatedRay插值得到的。实际上，因为近裁剪平面是上下左右对称的，因此书里面的|TL| = |TR| = |BL| = |BR|，P278上面的四个Ray就是TL/Near、TR/Near等，和我们上面推导的公式是一致的。

-----------

额数学这个东西是要自己推一遍才能懂，光看我说的估计你也比较懵。总之，不考虑计算误差问题，按照这个公式出来的世界坐标是准确的，和用逆矩阵得到的结果是一致的，不然也就算不了准确的雾效了呀。

**Comment by vipshenji** [comment]
非常谢谢作者哈   我懂了 真的感谢哈

**Comment by tyl1989** [comment]
感谢作者哈，我也看到这节对一个问题 看的不是明白，希望能请您解答下。
我看书中P277 中间的计算的四个向量TL TR BL BR的值。其中 按照图13.6向量加减得出的TL = cameraTransform.forward * near + toTop - toRight;  我理解和P288最上面计算的四个向量其中Ray(TL) = TL/|TL|*scale 。是一样的值呢。不知道是不是我理解错了。
如果说是一样的。为什么还要从TL 换一种计算方式变成Ray（TL）呢？

**Comment by candycat1992** [comment]
@tyl1989 式子当然不一样了，你再仔细推导一遍，这个issue里面我也说了推导结果，建议再好好看一下

**Comment by tyl1989** [comment]
亲，您好，恕我愚钝，看了很多遍 。感觉还是想不通这个问题，能否帮我看看我的思路有什么问题哈。
就比如任意一点P，可以根据相似三角形得出：P到摄像机的偏移值 OP = OC/|OC| * |OP| = OC/|OC| * |OC| * depth / Near = depth * (OC / Near)。其中点C是向量OP和近裁剪平面的交点。depth是P点到近裁剪平面的垂直距离。这个没有问题哈。
现在比如P就是近裁剪平面四个顶点的其中一的话，比如说是左上那个顶点。那么这点和近裁剪平面的交点就和他本身就是一个点的啊，按三角形来看的话 depth也Near也应该是相等的。那么OP=depth * (OC / Near)=OC=TL。
这个是我的理解。因为我看书中的推导过程TL是世界空间下近裁剪平面上的左上角相对于摄像机的方向，Ray（TL）不也是近裁剪平面上的左上角相对于摄像机的偏移。
能否帮忙指点下我的思路问题在哪里哈。

**Comment by candycat1992** [comment]
depth是要通过在fragment shader里纹理采样后得到的。你的结论“OP=depth * (OC / Near)=OC=TL”只适用于近裁剪平面上的点。我建议你你按照你自己的想法实现一下，如果效果是对的那么说明你是对的。然而你会发现你还是要在fragment shader里除以一次Near……

**Comment by tyl1989** [comment]
恩 我按照我的思路仅仅是把四个点的向量topLeft、topRight、bottomLeft、bottomRight设置进Matrix，而不是经过处理后的Ray(tl)这些，最后 fragment shader里面重建世界坐标就变成了float3 worldPos = _WorldSpaceCameraPos +  i.interpolatedRay.xyz （这下连depth都没有了 ，感觉就不对了哈）。
出现的效果就是拉往上卷的窗帘式的雾化效果，不是您那样正确貌似有个高度的台子往上的雾化效果。而且在fragment shader得到 i.interpolatedRay.xyz 除以Near也是同样错误的效果。

**Comment by candycat1992** [comment]
我是说直接传TL进去，乘以采样后的depth后再除以Near，采样深度是必须的，不然哪里来的重建坐标呢？我想数学公式你大概知道了，再好好想想~

**Comment by tyl1989** [comment]
@candycat1992  恩 好的 有时候感觉自己总会想多了  谢谢了

**Comment by sajshuai** [comment]
看这章的时候卡了好久，一直没想明白如果不在边界的话如何用相似三角形根据那四个角向量求出距离，还好搜到了这个问题，顶点着色器只在4个角的顶点进行。

**Comment by vanxining** [comment]
我觉得这里关键是怎么从一个片元的**深度值**求出从摄像机到它的向量长度。
感觉书里写得不是很容易令人理解。主要是那个 `scale` 常量，真没必要把它提取出来，直接讲怎样从相似三角形得出向量长度更为清楚明了。
另外我认为把 `interpolatedRay * depth` 直接等同于从摄像机到片元的向量表示也不是很合适，因为射线是无限长的。
