### ISSUE TITLE
P181的表9.1和P184的表9.2

### ISSUE THREAD

**Issue by romantic2016cool** [candycat1992/Unity_Shaders_Book#57]
首先感谢作者的书籍，给初学者学习shader提供了很大的帮助
P181的表9.1 ForwardBase用于前向渲染，这个应该也可以逐像素？这个表格只说是逐顶点，P184的表9.2里面有2个_LightColor0，描述还一样的。

**Comment by candycat1992** [comment]
P181的表9.1原话是“该Pass会计算环境光、最重要的平行光、逐顶点/SH光源和Lightmaps”。其中，“最重要的平行光”就是意味着可以逐像素处理的光源，这里只是没有点名逐像素，因为你完全也可以不逐像素处理这个平行光，这和后面的逐顶点是不冲突的。P183的图9.4也很详细的标注了这些东西。

P184的表9.2是勘误问题，这个早就[勘误](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)过了，直接搜页号就发现了。在第二次印刷的时候已经改正了。

**Comment by romantic2016cool** [comment]
谢谢，才看到有这个勘误列表
