### ISSUE TITLE
想问下关于第九章透明物体阴影问题

### ISSUE THREAD

**Issue by dobegran** [candycat1992/Unity_Shaders_Book#58]
非常赞的一本书，之前没有接触过shader，然而看下去思路非常清晰顺畅，捧着泡图书馆看一天一点也不累。大赞。感觉同是90后差距好大23333。

今天看完第九章，9.4.5节中对半透明物体阴影问题在最后通过使用fallback VertexLit、Diffuse来生成阴影。这个解决方案纠结了好久。直观感觉上半透明物体的阴影一般会比不透明物体的阴影要淡些。所以就想请教下**如何生成半透明物体的半透明阴影**。

 唔 然后玩了下unity中standard shader，里面Rendering mode设置成transparent就可以使用Alpha通道调节透明度了，而且阴影也是随着物体透明度的改变而改变。所以就更加想知道如何实现。然而自己搜索好久也没有找到问题答案。所以想在此问一下。或者能给一些相关文章链接。多谢多谢。

本人初入shader大千世界，如若问题愚笨还望海涵海涵 XD

**Comment by candycat1992** [comment]
现在回过头看那一节，我觉得有不少地方需要继续补充，你可以再看一下这个[issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/49)。

再说你的问题。唔之前都没注意到Standard透明还有阴影。经你提醒去看了下，的确是很有意思的效果~我去看了下它的源码，发现是用了Dither去“伪造”半透明的效果。

这是Standard Shader中计算阴影的Pass：

```
//  Shadow rendering pass
Pass {
	Name "ShadowCaster"
	Tags { "LightMode" = "ShadowCaster" }
			
	ZWrite On ZTest LEqual

	CGPROGRAM
	#pragma target 3.0
	// TEMPORARY: GLES2.0 temporarily disabled to prevent errors spam on devices without textureCubeLodEXT
	#pragma exclude_renderers gles

	#pragma shader_feature _ _ALPHATEST_ON _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON
	#pragma multi_compile_shadowcaster

	#pragma vertex vertShadowCaster
	#pragma fragment fragShadowCaster

	#include "UnityStandardShadow.cginc"

	ENDCG
}
```

可以发现也是和我们一样定义了LightMode为ShadowCaster的Pass。_ALPHATEST_ON _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON这些keyword就是为半透明阴影效果定义的。再看fragShadowCaster的实现（在UnityStandardShadow.cginc中定义）：

`
half4 fragShadowCaster (
	#ifdef UNITY_STANDARD_USE_SHADOW_OUTPUT_STRUCT
	VertexOutputShadowCaster i
	#endif
	#ifdef UNITY_STANDARD_USE_DITHER_MASK
	, UNITY_VPOS_TYPE vpos : VPOS
	#endif
	) : SV_Target
{
	#if defined(UNITY_STANDARD_USE_SHADOW_UVS)
		half alpha = tex2D(_MainTex, i.tex).a * _Color.a;
		#if defined(_ALPHATEST_ON)
			clip (alpha - _Cutoff);
		#endif
		#if defined(_ALPHABLEND_ON) || defined(_ALPHAPREMULTIPLY_ON)
			#if defined(UNITY_STANDARD_USE_DITHER_MASK)
				// Use dither mask for alpha blended shadows, based on pixel position xy
				// and alpha level. Our dither texture is 4x4x16.
				half alphaRef = tex3D(_DitherMaskLOD, float3(vpos.xy*0.25,alpha*0.9375)).a;
				clip (alphaRef - 0.01);
			#else
				clip (alpha - _Cutoff);
			#endif
		#endif
	#endif // #if defined(UNITY_STANDARD_USE_SHADOW_UVS)

	SHADOW_CASTER_FRAGMENT(i)
}	
`

代码也很简单，我们需要关注的就是tex3D(_DitherMaskLOD, float3(vpos.xy*0.25,alpha*0.9375)).a这一句。可以看出来，它是对一张3D的dither纹理采样，这张纹理的z方向对应了透明度值。再使用clip对dither后的结果进行cutout，造成一种半透明阴影的假象。

说得简单点，这种Dither技术其实就是利用人眼的特性，我们看到的其实是有很多细小孔洞的阴影，由于这些空洞的大小和密度变化，在人眼看来就像是半透明了一样，但实际上真正的阴影颜色是没有变的。总结其实就是，dither texture + cutout。

如果我们要自己在shader中实现这种效果，也可以仿照Standard Shader的做法，对_DitherMaskLOD这张纹理进行采样。例如，我们可以在书里的“Unity Shaders Book/Chapter 9/Alpha Test With Shadow”这个Shader中添加自定义的ShadowCaster Pass：

`
Pass{
	Name "ShadowCaster"
	Tags{ "LightMode" = "ShadowCaster" }
 
	ZWrite On ZTest LEqual
 
	CGPROGRAM
	#pragma target 3.0
 
	#pragma vertex vert
	#pragma fragment frag

	#pragma multi_compile_shadowcaster
 
	#define UNITY_STANDARD_USE_SHADOW_OUTPUT_STRUCT
	#define UNITY_STANDARD_USE_DITHER_MASK
	#define UNITY_STANDARD_USE_SHADOW_UVS
 
	#include "UnityStandardShadow.cginc"

	fixed _AlphaScale;

	struct VertexOutput
	{
		V2F_SHADOW_CASTER_NOPOS
		float2 tex : TEXCOORD1;
	};
 
	void vert(VertexInput v, out VertexOutput o, out float4 opos : SV_POSITION)
	{
		TRANSFER_SHADOW_CASTER_NOPOS(o,opos)
		o.tex = v.uv0;
	}
 
	half4 frag(VertexOutput i, UNITY_VPOS_TYPE vpos : VPOS) : SV_Target
	{
		half alpha = tex2D(_MainTex, i.tex).a * _AlphaScale;

		half alphaRef = tex3D(_DitherMaskLOD, float3(vpos.xy*0.25,alpha*0.9375)).a;
		clip(alphaRef - 0.01);
 
		SHADOW_CASTER_FRAGMENT(i)
	}
 
	ENDCG
}
`

同时禁用其他Fallback，就可以得到“半透明”阴影的效果了。

------

有一些参考链接：

[主流的游戏引擎都是如何解决Alpha Blending问题的呢？](https://www.zhihu.com/question/40274034/answer/106994992)
[unity5破錠しない半透明描画を行う](http://notargs.com/blog/blog/2015/09/24/unity5%E7%A0%B4%E9%8C%A0%E3%81%97%E3%81%AA%E3%81%84%E5%8D%8A%E9%80%8F%E6%98%8E%E6%8F%8F%E7%94%BB%E3%82%92%E8%A1%8C%E3%81%86/)

**Comment by dobegran** [comment]
明白了，十分感谢这么耐心与仔细的解答

**Comment by iiley** [comment]
太好了，正因为Chapter9-AlphaBlendWithShadow测试自己项目的时候，透明部分也有了阴影而纳闷。没想到这里找到答案了。感谢作者的详细解答。
另外我在frag函数里面调用了SHADOW_ATTENUATION(i);本以为它就可以接收阴影了，但是目前测试看是没有，正在调查学习中……

**Comment by candycat1992** [comment]
@iiley 关于阴影已经新开了一个[issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/49)讲了

**Comment by JOKULLIU** [comment]
这个问题已经关闭了，但我还是来补充书上遗漏的一点。
在P207中说到要使用 FallBack "Transparent/Cutout/VertexLit" 来计算阴影时，需要提供一个_Cutoff的属性来进行透明测试。
其实这里还需要提供一个_Color 的颜色属性，如果你没有，同样无法出现阴影。当然我也不明白_Color起什么作用。
或者把那段名叫“Caster”的Pass直接copy过来用也是一样的，当然前提还是要保证之前有定义_Cutoff和_Color。
PS：_Color问题困扰了我整整一个下午。

**Comment by candycat1992** [comment]
@JOKULLIU 恩的确是个遗漏，不过你看了原Pass代码后应该就明白了吧：
```
float4 frag( v2f i ) : SV_Target
{
	fixed4 texcol = tex2D( _MainTex, i.uv );
	clip( texcol.a*_Color.a - _Cutoff );
	
	SHADOW_CASTER_FRAGMENT(i)
}
```

因为它的Alpha Test逻辑使用了_Color的a通道进行判断。

**Comment by 275302262** [comment]
V2F_SHADOW_CASTER_NOPOS  楼主请问下这个在哪里定义的啊  完全找不到
