### ISSUE TITLE
关于屏幕后处理效果的疑问

### ISSUE THREAD

**Issue by romantic2016cool** [candycat1992/Unity_Shaders_Book#59]
读完12章不是很清楚屏幕后处理到底是处于渲染的哪个阶段，网上多处资料显示：是流水线的最后阶段。（所谓屏幕后处理，简单来说就是渲染流水线的最后阶段，对由整个场景生成的一张图片进行处理，比如HDR，运动模糊等等效果，通过屏幕空间的后处理，可以整体改变整个游戏的风格或者效果。所以，要制作屏幕后处理，我们需要两样东西，一个是用于渲染后处理效果的shader，而另一个是我们需要调用这个渲染的脚本，好在Unity为我们提供了相关的功能，我们在渲染场景时，一般都是直接输出到帧缓存，然后输出到屏幕上，然而有的时候，我们并不想直接输出结果，而是需要对这个渲染的结果进行处理
）
也就是说屏幕后处理也需要一个shader，但是shader里面也有顶点处理和片元处理阶段。又重复了整个渲染管线的流程。
“流水线的最后阶段”这个说话是似有不妥，感觉就是2个独立的过程。
求群主解答下，谢谢！

**Comment by candycat1992** [comment]
的确，屏幕后处理本身本质上是在近裁剪平面处又渲染了一个四边形，这个四边形使用的是我们自定义的材质和shader，它的确本身会走一遍流水管线。

网上说的它是“流水线的最后阶段”，是想指明我们操作的顺序，也就是说我们会在进行完其他物体的渲染后，最后进行这个操作。

**Comment by romantic2016cool** [comment]
谢谢！
