### ISSUE TITLE
第9章复杂光照P184疑惑之处

### ISSUE THREAD

**Issue by romantic2016cool** [candycat1992/Unity_Shaders_Book#60]
书上说“前向渲染通常会定义一个Base Pass”和一个Additional Pass。一个base仅会执行1次，而每个逐像素光源会执行1次Additional Pass。
问题是：如果有一个最重要的平行光和一个逐顶点光以及3个逐像素光。那么Additional会执行3次，base中执行的是最重要的平行光和一个逐顶点光。它仅会执行1次？光照计算怎样去对应，怎样去访问光源呢？

还有一段话不明白：
例如，我们完全可以利用unity提供的内置变量在Base Pass中只进行逐顶点光照，同样我们也可以完全在Additional中按逐顶点的方式进行光照计算，不进行任何逐像素光照计算-----这里不是跟前面表9.1说的矛盾吗？前面的叙述都是说Additional只会进行逐像素光照计算。这个应该怎样解释。希望作者帮忙解答一下，多谢！

**Comment by romantic2016cool** [comment]
补充：既然存在多个点光源，那存在光源的位置变量unity_4lightPosX0，为什么不存在unity_4lightPosX1、unity_4lightPosX2、unity_4lightPosX3呢，这么逐顶点光源怎么在base pass里面一次执行完

**Comment by romantic2016cool** [comment]
是否可以这样理解呢，最重要平行光和逐顶点执行的是Base Pass。其他像素光执行的是Additional Pass。但是Base Pass不一定只计算顶点光照也可以在frag中计算光照，Additional中不一定只在frag计算光照也可以在vert中计算？

**Comment by candycat1992** [comment]
本质上来说，这些话都是在描述Unity内置shader的做法。你可以参考我在[这个issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/29)里的回答。简单来说，是因为Unity在执行每个不同的Pass之前会设置一些变量，它首先会对当前影响该物体的所有光源排序，也就是书中P183最上面所讲的那样，Unity会把这些光源变量赋值给特定的shader变量中，例如，在执行Base Pass前，它会把最重要的平行光的颜色放到_LightColor0中，把其他逐顶点光源放到unity_4lightPosX0等变量里。我们以Base Pass为例，在Unity内置的shader中，它大致上是这么计算光照的：

```
            struct a2v {
                float4 vertex : POSITION;
                float3 normal : NORMAL;
            };

            struct v2f {
                float4 pos : SV_POSITION;
                float3 worldNormal : TEXCOORD0;
                float3 worldPos : TEXCOORD1;
                half3 sh : TEXCOORD2; // SH
            };

            v2f vert(a2v v) {
                v2f o;
                o.pos = mul(UNITY_MATRIX_MVP, v.vertex);

                o.worldNormal = UnityObjectToWorldNormal(v.normal);

                o.worldPos = mul(_Object2World, v.vertex).xyz;

                // SH/ambient and vertex lights
                #ifdef LIGHTMAP_OFF
                    #if UNITY_SHOULD_SAMPLE_SH
                    o.sh = 0;
                    // Approximated illumination from non-important point lights
                    #ifdef VERTEXLIGHT_ON
                        o.sh += Shade4PointLights (
                            unity_4LightPosX0, unity_4LightPosY0, unity_4LightPosZ0,
                            unity_LightColor[0].rgb, unity_LightColor[1].rgb, unity_LightColor[2].rgb, unity_LightColor[3].rgb,
                            unity_4LightAtten0, o.worldPos, o.worldNormal);
                    #endif
                    o.sh = ShadeSHPerVertex (o.worldNormal, o.sh);
                    #endif

                #endif // LIGHTMAP_OFF

                return o;
            }

            fixed4 frag(v2f i) : SV_Target {
                fixed3 worldNormal = normalize(i.worldNormal);
                fixed3 worldLightDir = normalize(_WorldSpaceLightPos0.xyz);

                fixed3 ambient = UNITY_LIGHTMODEL_AMBIENT.xyz;

                fixed3 diffuse = _LightColor0.rgb * _Diffuse.rgb * max(0, dot(worldNormal, worldLightDir));

                fixed3 viewDir = normalize(_WorldSpaceCameraPos.xyz - i.worldPos.xyz);
                fixed3 halfDir = normalize(worldLightDir + viewDir);
                fixed3 specular = _LightColor0.rgb * _Specular.rgb * pow(max(0, dot(worldNormal, halfDir)), _Gloss * 128);

                fixed atten = 1.0;

                fixed3 color = ambient + (diffuse + specular) * atten;
#if UNITY_SHOULD_SAMPLE_SH
                color += i.sh;
#endif
                return fixed4(color, 1.0);
            }
```

书里说Bass Pass会处理一个逐像素的平行光和逐顶点/SH光源，其实就是因为它会把这些相关光源的信息存储到特定的shader变量中，表9.1描述的是内置shader的做法，也就是“一般情况下我们在拿到这些变量后会这么处理光照”。

诚如你所说的，Unity只是按照它的规定给我们了一些变量，只要我们知道这些变量里存储的是哪些光源的信息，怎么处理它们完全取决于我们自己。还是拿Bass Pass举例，Unity只负责把最重要的平行光信息存在了_LightColor0和_WorldSpaceLightPos0里面，按照“一般的做法”，我们的确是会在fragment shader里逐像素计算光照，让它真正是一个逐像素的平行光，就像6.4.2节那样。但是，我们也完全可以按逐顶点方式处理它，毕竟Unity只是传递给我们了一些变量而已，就像6.4.1节那样。

对于你的第二个问题，unity_4lightPosX0存储的是四个逐顶点光源的x坐标，unity_4lightPosY0是它们的y坐标，unity_4lightPosZ0是z坐标。同样的，Unity只是把这些光源的信息存在这里面而已，怎么处理它们完全取决于我们自己。内置shader的做法见上面的代码，就是Shade4PointLights这个内置函数处理的，你可以去查内置的cginc文件看它是怎么处理的。当然了，你完全可以自己写一个不同的函数、按自己的意愿处理它们，甚至可以在fragment shader里处理它们。但需要注意的是，这些光源只能在Bass Pass里处理，因为Unity已经判断得到它们是逐顶点光源的结论，所以才会在调用Bass Pass前设置它们的变量，而我们在Additional Pass中是无法通过内置变量访问到它们的光源信息的，这也就是表9.1的本质原因。

------

综上，Unity按照自己的一套规则会对影响某个物体的所有光源进行排序，并在调用Bass Pass和Additional Pass前把这些光源按照这套规则去设置相关的shader变量，导致我们在Bass Pass可以访问特定的光源信息，在Additional Pass里访问另一套光源信息，至于怎么处理这些信息，是逐顶点还是逐像素这是没有硬性规定的。

**Comment by romantic2016cool** [comment]
终于明白了，解释的非常详细！谢谢

**Comment by wukangjian** [comment]
666 3q作者，终于找到答案了
