### ISSUE TITLE
关于第十二章描边算法问题

### ISSUE THREAD

**Issue by l1000965431** [candycat1992/Unity_Shaders_Book#62]
请问第十二章里第一节描边算法，计算uv 9个相邻域的uv值时，如果超出图片范围不会影响最后的描边结果吗？比如计算得到的uv值<0或是>1

**Comment by candycat1992** [comment]
你好，这是卷积计算中的边界处理问题。具体到书里的这个例子，超出图像范围的uv值采样的结果取决于被采样图片的wrap mode，你可以参见书里中7.1.2节纹理属性。默认情况下，书里这种方法采样的屏幕图像的wrap mode会是clamp，也就是超出（0，1）范围的会截取到边界处。
