### ISSUE TITLE
关于模拟折射的问题请教

### ISSUE THREAD

**Issue by tyl1989** [candycat1992/Unity_Shaders_Book#64]
想请问下书里模拟折射出现了两部分，一块是在15.3水波效果P305,一块是在10.2章P223。模拟折射时计算偏移后重新计算坐标涉及两句代码：
float2 offset = bump.xy * _Distortion * _RefractionTex_TexelSize.xy; 
i.scrPos.xy = offset+ i.scrPos.xy;看的不是很懂，向作者请教下哈。
 为什么都要在切线空间下计算，您在书中说选择使用切线空间下的发现方向来进行偏移，是因为该空间下的发现可以反映顶点局部空间下的法线方向。
我对这句话不太理解。不知道offset的计算是不是经验性的做法。我理解这种加法是要在同一个坐标系下的。bump.xy是在切线空间下的。但是scrPos也不知道是哪个坐标系下的，只知道scrPos除以clip的w分量后范围是在（0,1），意义在于物体所在屏幕的位置。所以这两句话的计算依据我感觉不是很好理解。

**Comment by candycat1992** [comment]
对，其实这种做法我感觉是一种约定俗成的trick，并没有非常严格的数学证明。不过非要解释的话，你可以这么想，其实折射就是说光线传播方向发生了偏移，你可以参考P215的图10.8。这个偏移是发生在每个顶点的局部坐标系里的，也就是每个顶点的切线空间：这个空间里顶点法线就是它的z轴，因此它的偏移其实是发生在切线空间的xy平面上。

回到代码里，就是使用切线空间里的bump.xy去偏移屏幕采样坐标。scrPos的意义你可以再去读一下4.9.3节，里面详细解释了这个东西，单说scrPos是什么空间好像还真没什么术语……至于它为什么要先加上offset再去除以w、而不是先除以w后再加上offset，我觉得这个没什么太多的依据。

* 书里代码是写法是：
    ```
    float2 offset = bump.xy * _Distortion * _RefractionTex_TexelSize.xy;
    i.scrPos.xy = offset + i.scrPos.xy;
    ```
    这样经过w除之后，随着物体在裁剪空间中的位置变化，偏移范围是在[offset/Far, offset/Near]，离摄像机越远偏移越小，看起来折射越弱。尤其到了离摄像机远一点的时候折射就变得很弱了，接近于0。

* 其实github上这一节的代码是：
    ```
    float2 offset = bump.xy * _Distortion * _RefractionTex_TexelSize.xy;
    i.scrPos.xy = offset * scrPos.z + i.scrPos.xy;
    ```
    这种做法常见于Unity内置或官方的各个shader中，它是用offset乘以了scrPos.z，这样经过w除之后，其实偏移是受NDC坐标系中z分量（范围-1到1）的影响的，偏移范围是在[-offset, offset]，你可以根据投影矩阵（见P79）推导得到，当一个位于观察空间内z坐标为-2*N*F/(F+N)的点可以取到偏移值为0（这个推导just for fun……）。一些人不理解为什么要这里乘以scrPos.z，其实并没有特别重要的原因，当然可以不乘以scrPos.z，但正如上面说的，折射效果会快速变弱，这可能是我们想要的，也可能不是。如果先乘以了scrPos.z后，偏移值就永远不会很小，折射效果会一直比较明显。

* 当然还有一种做法是：
    ```
    float2 offset = bump.xy * _Distortion * _RefractionTex_TexelSize.xy;
    fixed3 refrCol = tex2D(_RefractionTex, i.scrPos.xy/i.scrPos.w + offset).rgb;
    ```
    这样offset就不会跟物体距离摄像机的远近有任何关系，永远都是offset的值，这也不能说这样做有什么问题。

其实我觉得吧这几种都可以，本来就是看起来对，各种trick，只要你觉得这种做法适合你现在的游戏效果最好就可以了，当然是个人意见。

**Comment by tyl1989** [comment]
十分感谢您在双十一，如此耐心的解答。
学习了，没有想过还有这么有趣的计算意义。
第一个i.scrPos.xy = offset + i.scrPos.xy; 除以w，是因为w的范围是（Near，Far），所以偏移范围是在[offset/Far, offset/Near]？
第二个i.scrPos.xy = offset * scrPos.z + i.scrPos.xy; 感觉有点难度，除以w后，偏移就是offset * scrPos.z/clip.w
，是不是scrPos.z = clip.z，其实就是offest*clip.z/clip.w，clip.z/clip.w范围是（-1,1），所以最后的便宜是偏移范围是在[-offset, offset]。但是您说的那个矩阵推导我没有看出来。

**Comment by candycat1992** [comment]
还是那个小节，scrPos的意义你可以再去读一下4.9.3节，里面详细解释了这个东西各个分量都是什么。你的分析基本是对的，矩阵推导就是让scrPos.z = 0，也就是clip.z = 0。

**Comment by tyl1989** [comment]
谢谢

**Comment by YuJie-Ding** [comment]
我发现如果将float2 offset = bump.xy * _Distortion * _RefractionTex_TexelSize.xy;
i.scrPos.xy = offset+ i.scrPos.xy;这里的bump转换到世界空间下再计算，会造成折射效果整体沿xy方向发生偏移。

**Comment by spicy-ice** [comment]
亲╭(╯3╰)╮邮件收到啦 ！   O(∩_∩)O~
                                                       -----徐方凯

**Comment by TheZoomFlash** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到邮件，尽快给您回复。
