### ISSUE TITLE
编辑器问题

### ISSUE THREAD

**Issue by wangshunping** [candycat1992/Unity_Shaders_Book#66]
请问大家用什么编辑器写 shader 呢？

mono 支持的不是很好，目前在用装了 shader package 的 sublime ，但是也不能正常匹配什么的～

有没有同学有好的建议？

**Comment by candycat1992** [comment]
Mac下一直在用MonoBehavior，不知道你说的支持都是啥，目前感觉只要有高亮就足够了，提示啥的从来没有用过。目前已知的是VS有网友做的插件，Sublime也有插件。

**Comment by mingchaoyan** [comment]
@candycat1992  人家明明叫 **MonoDevelop**  :)

**Comment by candycat1992** [comment]
@mingchaoyan 哈哈是打错了，对不起MonoDevelop……已改正~

**Comment by iiley** [comment]
vscode很简洁好用且功能强大，MonoDevelop实在是忍受不了啊。
如果纯写shader的话，推荐Unity插件Shader Forge和Amplify Shader Editor。
