### ISSUE TITLE
UnityObjectToWorldDir和UnityObjectToWorldNormal区别

### ISSUE THREAD

**Issue by oOFlyOo** [candycat1992/Unity_Shaders_Book#67]
# 如题
[Difference between UnityObjectToWorldDir and UnityObjectToWorldNormal?](https://forum.unity3d.com/threads/difference-between-unityobjecttoworlddir-and-unityobjecttoworldnormal.435302/)
- 这里面的那个回答我没看懂，里面评论的那个链接又打不开啊……

**Comment by candycat1992** [comment]
这两个函数名字已经写得非常清楚了，UnityObjectToWorldDir是把一个普通的矢量从模型空间变换到世界空间，UnityObjectToWorldNormal是专门用于把法向方向从模型空间变换到世界空间。至于为什么法线的方向变换与其他普通的矢量变换不同，这个在书里在4.7节就已经讲过了哦，而且UnityCG.cginc文件里面的代码也写得非常清楚了：
```
// Transforms direction from object to world space
inline float3 UnityObjectToWorldDir( in float3 dir )
{
	return normalize(mul((float3x3)_Object2World, dir));
}

// Transforms normal from object to world space
inline float3 UnityObjectToWorldNormal( in float3 norm )
{
	// Multiply by transposed inverse matrix, actually using transpose() generates badly optimized code
	return normalize(_World2Object[0].xyz * norm.x + _World2Object[1].xyz * norm.y + _World2Object[2].xyz * norm.z);
}
```

**Comment by oOFlyOo** [comment]
然而没看懂
回去温习下书 谢谢

**Comment by AIFSKATE** [comment]
> 
你好，你的评论十分有用，但是有一点需要注意的是Unity内置矩阵都是列主序
https://docs.unity3d.com/Manual/SL-UnityShaderVariables.html

**Comment by AIFSKATE** [comment]
@HongfeiXu 你好，你的评论十分有用，但是Unity内置矩阵是列主序
https://docs.unity3d.com/Manual/SL-UnityShaderVariables.html
