### ISSUE TITLE
关于第十章镜子（渲染纹理）的问题

### ISSUE THREAD

**Issue by ArionTT** [candycat1992/Unity_Shaders_Book#68]
在第十章的代码下，我扩展了一下，在镜子的对面又新建了一面镜子（Quad+Camera），重新写了Mirror_Double.shader和Material。然后，不知道为什么原本的镜子和新镜子关联了，当我改第二面镜子的材质时，第一面镜子也会跟着变化。例如第一面镜子是Mirror.mat，第二面我改成Mirror_double.mat后，第一面也变成Mirror_double.mat (哭笑不得)。
另外，镜子连续反射时，到第二次后，好像物象又会反过来，也不知道怎么回事（不过也许是因为上面没有改好的问题）。

**Comment by candycat1992** [comment]
更改材质的描述不清楚，只能猜测可能是[Renderer.sharedMaterial](https://docs.unity3d.com/ScriptReference/Renderer-sharedMaterial.html)和[Renderer.material](https://docs.unity3d.com/ScriptReference/Renderer-material.html)混淆造成的。
