### ISSUE TITLE
GaussianBlur实现的Shader中（P258），for循环对uv的采集

### ISSUE THREAD

**Issue by Millss** [candycat1992/Unity_Shaders_Book#69]
for(int it = 1;it < 3; it ++){
      sum += tex2D(_MainTex,i.uv[it]).rgb * weight[it];
      sum += tex2D(_MainTex,i.uv[2 * it]).rgb * weight[it];
}
这段代码计算的sum没有i.uv[3],但是i.uv[2]乘以了两个权重值，weight[1]和weight[2];

**Comment by candycat1992** [comment]
第2&3印刷版上的这段代码有问题，已经[勘误](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)了。你可以直接看github上的源码~

**Comment by Millss** [comment]
OK，好的，我去看一下，回复的还是蛮快的么。
