### ISSUE TITLE
使用Keyword制作多版本Shader出现的问题请教

### ISSUE THREAD

**Issue by JOKULLIU** [candycat1992/Unity_Shaders_Book#70]
作者你好，又来请教了~~
书上没有这块的内容，但是你的博客《自定义材质面板的小技巧》拜读了，目前我想采用这个办法来应对高中低档不同手机的Shader表现。
我的代码是这样的：
```
Properties{
	// [KeywordEnum(Low, Medium, High)] _Quality ("品质模式", Float) = 0
}
```
属性声明写了这句，但为了用代码控制，这句其实被注释了。如果不注释它，它是生效的，并达到了预期效果！
接下来是在Pass的开头，和一大堆#pragma……什么的写在一起：
`#pragma multi_compile _QUALITY_LOW _QUALITY_MEDIUM _QUALITY_HIGH`
接下来在片元着色器里面是：
```
half3 fresnel = half3(0,0,0);
#ifdef _QUALITY_HIGH
fresnel = _FresnelAmount * pow(1 - saturate(dot(viewDir, i.worldNormal)), _FresnelPower) 
    * _FresnelTint.rgb * saturate(saturate(dot(i.worldNormal, lightDir)) + _FresnelShadow);
#endif

half4 finalCol;
finalCol.rgb = albedo.rgb * halfLambert * _LightColor0.rgb + fresnel + spec + emission 
	+ albedo.rgb * cubeColor.rgb * _CubeIntensity + cameraColor.rgb * albedo.rgb;
finalCol.a = 1; 
return finalCol;
```
好了，Shader本身没有问题，用了很久了。
正如前面说的，如果使用KeywordEnum来控制是木有问题的。fresnel想它来就来，想它GUN就GUN。

现在我在代码里面写：
```
void Start () {	
	Shader.EnableKeyword("_QUALITY_LOW");
	Shader.DisableKeyword("_QUALITY_MEDIUM");
	Shader.DisableKeyword("_QUALITY_HIGH");
}

public void OnBtnTestClick(int index){
	print(Shader.IsKeywordEnabled("_QUALITY_HIGH"));
	Shader.DisableKeyword("_QUALITY_LOW");
	Shader.DisableKeyword("_QUALITY_MEDIUM");
	Shader.EnableKeyword("_QUALITY_HIGH");
	print(Shader.IsKeywordEnabled("_QUALITY_HIGH"));
}
```
写Start主要是为了确保关键字初始设置是正确的。主要是在OnBtnTestClick这个按钮事件里面，这个不管怎么搞是不起作用的，fresnel始终不显示。打印IsKeywordEnabled检查是正确的，第一句打印出来是False，后一句打印出来是True。
这个问题快把我逼疯了，请作者大人救命啊~~~

**Comment by candycat1992** [comment]
先问个问题啊，你说“LOD不能使用，因为国内某知名奇葩手机上Pass过多会出问题，国内android市场上充斥者大量的深受吃瓜群众喜爱的奇葩手机……”，是指小米是吧，SubShader+LOD没法用吗？你是指超过了几个就出问题啦？

然后，你问的这个问题，是指在编辑器下就不管用吗？还是说发布到手机才出了问题？你可以把整个代码打个包给我，比较好让我调试看一下。

**Comment by JOKULLIU** [comment]
邮件发了。
