### ISSUE TITLE
插值寄存器的基础问题

### ISSUE THREAD

**Issue by ZJNPRI** [candycat1992/Unity_Shaders_Book#71]
你好，我是一个策划，最近在学习shader相关的知识，买了你的书，有个基本概念没找到，希望能得到你的帮助。
书中P200有介绍SHADOW_COORDS(2)中的参数2是可用的插值寄存器的索引值，请教一下插值寄存器的概念是什么？书里好像没找到。
一个插值寄存器是存储一组纹理坐标吗？

**Comment by candycat1992** [comment]
你好，这个概念是和P104以及P109的语义相关的。当把数据从vertex shader传递给fragment shader的过程中，我们需要使用语义来修饰结构体v2f里面的每个变量，除了一些系统数值语义外（比如SV_POSITION）等，我们通常会使用TEXCOORDn（n的范围取决于使用的Shader Model，比如SM 2.0一般是8），这些被TEXCOORD0、TEXCOORD1、TEXCOORD2…等修饰的变量是会被存储在特定的寄存器里，然后这些数值会被**插值**后传递给fragment shader，因此简称为插值寄存器。

除了Unity特定语义修饰的插值寄存器变量（比如SV_POSITION）等外，其他插值寄存器里存储的什么没有规定，可以是纹理坐标也可以是其他需要从vertex shader传递给fragment shader的值。这个你可以参见P110的表格。具体到P200阴影的例子，SHADOW_COORDS(2)，你可以在P201代码里找到这句宏的实现，其实就是写了一句代码：

```
#define SHADOW_COORDS(idx1) unityShadowCoord4 _ShadowCoord : TEXCOORD##idx1
```

SHADOW_COORDS(2)就意味着占用TEXCOORD2所在的寄存器声明并用于存储一个_ShadowCoord变量。书里没有过多涉及硬件底层方面的内容，如果你对这些标准更感兴趣的话可以看[High-Level Shading Language](https://en.wikipedia.org/wiki/High-Level_Shading_Language)以及Real-time Rendering一书，P120的扩展阅读里也有其他资料。
