### ISSUE TITLE
关于书中271页输出深度值和法线

### ISSUE THREAD

**Issue by wgf120513** [candycat1992/Unity_Shaders_Book#72]
书中写到输出法线方向在framedebugger中查看
return fixed4(normal*0.5+0.5,1);
我有两个问题
1.这个normal已经是转换到视角空间下的线性值应该不需要乘以0.5再加上0.5吧。
2.这个normal不是矢量吗？ 怎么还能加上0.5？
还是说我理解有错误，请指正。

**Comment by candycat1992** [comment]
你说的是P271下面的代码对吧？以后提问的时候如果能告诉我页码就最好啦~

你的问题：
1. 通过DecodeViewNormalStereo得到的是解码后的观察空间的法线方向，各分量范围仍然在[-1, 1]。你说的线性空间描述的是深度值，不存在“线性空间下的法线方向”这种概念，只有“线性空间下的深度值”。你可以去UnityCG.cginc里面仔细看下各种Encode/Decode法线和深度的函数。
2. normal的确是矢量，直接加上一个标量值05的话，Cg会自动按另一个加数的维数用0.5补全其他维度得到一个相同维数的矢量，这被称为[**"Smearing" Of Scalars To Vectors**](http://http.developer.nvidia.com/Cg/Cg_language.html).

**Comment by wgf120513** [comment]
好的，多谢。
