### ISSUE TITLE
P273页视角*投影矩阵

### ISSUE THREAD

**Issue by wgf120513** [candycat1992/Unity_Shaders_Book#73]
P273页写到
 Matrix4x4 currentViewProjectionMatrix =   Camera.projectionMatrix* Camera.worldToCameraMatrix;
因为矩阵一般是不满足交换律的
我没有明白这里为什么是Camera.projectionMatrix* Camera.worldToCameraMatrix
而不是Camera.worldToCameraMatrix*Camera.projectionMatrix
这其中有什么原因嘛？

**Comment by candycat1992** [comment]
因为你是从左往右读的，而我们书里面包括unity的矩阵都是按列向量的方式摆放和相乘的，应该是从右往左读才对~
