### ISSUE TITLE
我向请教一下，传递数组的问题。

### ISSUE THREAD

**Issue by wgf120513** [candycat1992/Unity_Shaders_Book#74]
你好，我看到CG上说是支持的数组的。但是我在unity中没有找到相应的方法。那我应该如何传递数组呢？
数组的类型、大小、维度有限制吗？如果可以传递，我在shader中的Properties中如何写呢？在数组使用的过程中又有什么注意的地方？

**Comment by candycat1992** [comment]
具我所知Properties属性面板里面是没有数组类型的声明的，但可以在脚本里调用API来传数组。在Unity 5.4之前，是不支持传递真正的数据的，如果我们在shader里声明一个uniform float array[4]，Unity其实是会把把它拆成array0、array1、array2和array3，然后我们可以在脚本里通过material.SetFloat("array0", 0.0f)这样来设置它们。在Unity 5.4之后，开始支持真正的数据属性，相关的API有[Material.SetFloatArray](https://docs.unity3d.com/ScriptReference/Material.SetFloatArray.html)、[Material.SetVectorArray](https://docs.unity3d.com/ScriptReference/Material.SetVectorArray.html)等，你可以参考下面的两个帖子：

* [Passing Arrays to shaders](https://forum.unity3d.com/threads/passing-arrays-to-shaders.178682/)
* [Passing Array To Shader](https://forum.unity3d.com/threads/passing-array-to-shader.392586/)

不过我建议还是要在真机上测试一下，之前那种material.SetFloat("array0", 0.0f)的方法我记得好像有人说过有遇到失效的情况。

另外，我们还可以在顶点着色器到片元着色器的输出结构体v2f中定义数组类型的变量。例如：

```
struct VertexOutputForwardBase
{
	float4 pos	: SV_POSITION;
	float4 tex	: TEXCOORD0;
	half3 eyeVec 		: TEXCOORD1;
	half4 tangentToWorldAndParallax[3]	: TEXCOORD2;	// [3x3:tangentToWorld | 1x3:viewDirForParallax]
	half4 ambientOrLightmapUV	: TEXCOORD5;	// SH or Lightmap UV
}
```

里面声明了一个三维的数据变量tangentToWorldAndParallax。需要注意的就是要自己算一下占用的插值寄存器的个数。比如这里tangentToWorldAndParallax实际上占了3个寄存器，所以尽管它的修饰符是TEXCOORD2，它的下一个变量ambientOrLightmapUV的修饰符应该后推到TEXCOORD5，而不是TEXCOORD3。

**Comment by wgf120513** [comment]
非常非常感谢。
