### ISSUE TITLE
关于67页的旋转顺序问题

### ISSUE THREAD

**Issue by huyiyuan** [candycat1992/Unity_Shaders_Book#75]
就是矩阵MzMxMy 乘以向量v ，按照书中所说是按照y,x,z的旋转顺序来做的。但是给出的欧拉角是x,y,z,然后查阅了unity文档说是按zxy的顺序。书中给出的公式为 MzMxMy *v 。是不是意味着只要是矩阵变换，在第一个旋转变换后，今后每次变换都是根据新的坐标系来变换的？ 可以回复到我的邮箱504460664@qq.com或者这里。不知道这里有没有邮箱提示。。

**Comment by huyiyuan** [comment]
说的有点拗口，简单点就是为什么要反向写？ 还是说按照矩阵MzMxMy *v 每次旋转变换后坐标系也做了变换？

**Comment by candycat1992** [comment]
其实这一段的意思是为了让读者理解Unity文档里面说的那种顺序映射到数学公式上是如何理解的，没想到好多人反而看了更糊涂了…

这一段的起因是这样的，当时其实我没写这一段，直接写的是大概是：

> 在Unity里的旋转顺序是zxy，它的公式是：
MzMxMy *v = ……

然后，提前看过我书的一个朋友建议说这里他很迷惑，因此我书里面一直是按列向量和矩阵相乘的规则去进行矩阵和向量乘法的，这意味着它们之间相乘的时候应该是从右往左读（书里很多地方都强调过了）。如果是这样从右往左读的话，那顺序应该是YXZ，而Unity里写的是ZXY，这不是反了吗？然后我就加了这一段解释。

说白了就是，其实没有反着写，Unity文档里的写的那个顺序的理解方式是从左往右读矩阵相乘，通俗理解就是进行一次旋转时不一起旋转当前坐标系，但这其实和我们书里面约定的阅读顺序是反着的，这里是希望读者看到这个顺序的时候不要感到迷惑。

**Comment by huyiyuan** [comment]
谢谢回复，那从实际数学意义上来讲，是unity的正确还是书中的旋转顺序正确？ 比如我要旋转一个物体（unity中和非unity中）按YXZ旋转。两者分别是哪种写法？从广义上来讲，哪种写法更有普遍性？

**Comment by candycat1992** [comment]
你还是没有理解，他们都是正确的，区别只在于你的理解或者说你倾向于是从左往右理解还是从右往左理解。如果你在Unity的环境下说“我要按YXZ旋转一个物体”，那么因为Unity里面的理解顺序是右乘但是从左往右读和理解，因此就是书里面的公式。如果你没有在Unity里面，那也需要提供一个上下文来指明这个理解和相乘顺序。

**Comment by huyiyuan** [comment]
你说的这个理解是相当于标准么？就一个列向量和矩阵进行左乘不是才有数学意义么，这样从右往左读才能解释这个数学意义，所以还是不太懂。。

**Comment by candycat1992** [comment]
不是标准，就是当给定一个公式后如何理解，以及根据一段描述如何给出对应公式。你不理解的话可以多做几道数学变换题。

**Comment by huyiyuan** [comment]
好的 。可以关闭了
