### ISSUE TITLE
关于第七章法线贴图的切线空间

### ISSUE THREAD

**Issue by tvrcaiyy** [candycat1992/Unity_Shaders_Book#76]
在法线贴图中，是每个面的每个像素点都有自己的切线空间？还是只有这个面的三个顶点有各自切线空间，其他像素点的法线都是插值计算出来的？
如果是第一种情况，那么每个像素点的法线应该都是和它自己的切线空间的z轴重合的，怎么会有扰动之类的？
如果是第二种情况，那其他像素点的法线是根据哪个点的切线空间算出来的？

**Comment by candycat1992** [comment]
你可以先不要考虑法线贴图。切线空间是由**模型中该顶点处**的法线、切线和副切线组成的，就算没有法线纹理，模型的每个顶点也是有自己的切线空间的。因为我们要在fragment shader里构建变换矩阵，所以到了像素级别的时候你可以认为此时每个像素的切线空间的三个坐标轴是由顶点处的三个向量插值过来的。

你所说的“每个像素点的法线应该都是和它自己的切线空间的z轴重合的”，准确说来是每个像素点的插值法线应该都是和它自己的z轴重合的，因为我们就是使用了这个值肯定是一致的……法线贴图里存储的是在这个切线空间里面的某个方向，是我们希望高模中该处的法线方向。

你会有这样的问题应该是把**模型法线**和我们期望的法线弄混了。法线贴图一般是由高精度模型得来的，而我们真正使用的模型是由高模简化而来的，它包含了的顶点数和面片数都大大小于高模，这就意味着法线精度一定会缺失。所以我们就需要使用一张像素精度级别的纹理来存储高模的法线信息，这就是法线纹理。

**Comment by tvrcaiyy** [comment]
明白了，非常感谢！
