### ISSUE TITLE
渐变纹理效果偏差

### ISSUE THREAD

**Issue by tvrcaiyy** [candycat1992/Unity_Shaders_Book#77]
![1121](https://cloud.githubusercontent.com/assets/17244980/22276196/fb755234-e2ec-11e6-94e7-6ebc6fad3691.jpg)

上面一行的结果是我照着书上做的
下面一行是这里下载的项目里的效果
请问下，这两个结果有色差，是哪里设置不一样造成的吗？

**Comment by tvrcaiyy** [comment]
角度，光照，颜色之类的我对照过了，都跟你的项目里的设置是一样的，所以不知道还有哪里不一样会造成偏差

**Comment by candycat1992** [comment]
额仅靠图让我猜么。。。如果光照和材质颜色都一样的话，那我猜一个好了，可能是颜色空间设置吧。。。这种问题很难帮你，版本不同或者有些设置不同都有可能，我也没有你的工程文件，只能猜了。。。还是要靠自己debug

**Comment by tvrcaiyy** [comment]
版本一样的
我再找找
谢谢！

**Comment by p0e0o0p0l0e0** [comment]
我也是同样的问题，unity用的5.3.8，能看到的设置都设置成一样的了。和题主效果一样，但和这里下载的工程不同。
