### ISSUE TITLE
关于法线归一化的问题

### ISSUE THREAD

**Issue by tvrcaiyy** [candycat1992/Unity_Shaders_Book#78]
在书上 vert函数里都有计算世界坐标里的法线
o.worldNormal = UnityObjectToWorldNormal(v.normal);
然后在frag函数里有一句
fixed3 worldNormal = normalize(i.worldNormal);
但是在UnityCG.cginc里面UnityObjectToWorldNormal这个内置的方法已经归一化了，是不是多做了一次归一化
fixed3 worldNormal = normalize(i.worldNormal);
这句改成下面这句渲染结果是不一样的
fixed3 worldNormal = i.worldNormal;

// Transforms direction from object to world space
inline float3 UnityObjectToWorldDir( in float3 dir )
{
	return normalize(mul((float3x3)unity_ObjectToWorld, dir));
}
// Transforms normal from object to world space
inline float3 UnityObjectToWorldNormal( in float3 norm )
{
#ifdef UNITY_ASSUME_UNIFORM_SCALING
	return UnityObjectToWorldDir(norm);
#else
	// mul(IT_M, norm) => mul(norm, I_M) => {dot(norm, I_M.col0), dot(norm, I_M.col1), dot(norm, I_M.col2)}
	return normalize(mul(norm, (float3x3)unity_WorldToObject));
#endif
}

**Comment by candycat1992** [comment]
如果想得到正确的方向的话，并没有多做。虽然已经在vert里归一化了，但是从vert到frag会经过插值，到达frag里面的逐像素方向就不再能保证是归一化的。

![renormal](https://cloud.githubusercontent.com/assets/5907064/22324316/9039ad24-e3e3-11e6-92dd-a55648c6b17f.png)

你可以参考上图，图里面n1和n2是vert里面归一化后得到的两个顶点法线方向，经过插值后的方向实际上都是位于三角形的第三条边上的，比如p，可以看出来它们其实并不是单位向量。正确的方向应该是q这样位于圆弧上的。所以还是要在frag里进行一次归一化操作。不过一些shader为了简化计算量，节省指令可能会跳过这步normalize的计算，如果视觉上可以接受的话。

**Comment by tvrcaiyy** [comment]
明白了，谢谢！！
