### ISSUE TITLE
206页关于forward add pass中#pragma multi_compile fwdadd_fullshadows的问题

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#79]
书上说只有加上这个预编译指令才会计算额外的逐像素光的阴影 但是我在unity5.5中就算在additional pass中使用#pragma multi_compile fwdadd 仍然可以显示点光源之类的阴影

**Comment by candycat1992** [comment]
因为过年这两天没回复issue不好意思~大过年都这么用功啊。

------

我在Unity 5.5中验证了下，不加_fullshadows是无法让该物体显示阴影的。我们可以以Scene_9_4_4为例，我们让场景里的所有三个物体（一个立方体和两个平面）都使用我们自定义的Shader——"Unity Shaders Book v2/Chapter 9/Attenuation And Shadow Use Build-in Functions"，然后在场景里放一个聚光灯，并打开它的阴影，保持Shader里使用#pragma multi_compile_fwdadd，结果如图：
![2017-01-31 17 24 01](https://cloud.githubusercontent.com/assets/5907064/22459096/3362b762-e7da-11e6-98a3-fdf396c39a24.png)

我猜想你说的情况大概是那种两个平面使用默认材质材质的情况，也就是原始的Scene_9_4_4的配置，这种情况下的确平面上是有阴影的：
![2017-01-31 17 24 22](https://cloud.githubusercontent.com/assets/5907064/22459097/33a0845c-e7da-11e6-8c53-64e10726ede7.png)

这是因为，加上_fullshadows影响的是本Shader编译出来的keywords和shader variants，跟阴影有关的主要是SHADOWS_XXX等的一些keywords，这些shader variants会决定这个Shader会不会**采样**阴影纹理，但实际上它不会影响阴影纹理的**产生**，关于阴影纹理也就是shadowmap的产生你可以参见之前的[一个issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/49)，其实简单来说就是找到一个LightMode为ShadowCaster的Pass（实验表明如果场景里没有物体需要采样阴影纹理的话Unity 5.5也不会浪费力气去渲染）。所以在第一种情况下，所有的物体由于都没有对应采样聚光灯阴影纹理的shader variants，因此就不会出现阴影。而第二种情况下，尽管立方体没有对应的shader variants，但由于下方的平面使用的是默认材质即Standard Shader，它是有multi_compile fwdadd_fullshadows编译指令的，因此会去采样阴影纹理从而显示出了立方体的阴影。你可以从Frame Debugger里看到这两个drawcall的keywords的不同：
![2017-01-31 17 28 54](https://cloud.githubusercontent.com/assets/5907064/22473041/67db979c-e812-11e6-9f72-bc83e0ca52b5.png)
![2017-01-31 17 29 03](https://cloud.githubusercontent.com/assets/5907064/22473042/67e1fb1e-e812-11e6-9d24-fa7c6ee57735.png)

明显第一个event有相应的SHADOWS_XXX的阴影对应宏，而下面立方体的event则没有。

------

阴影这块问题总是最多的，我觉得有一句话一定要谨记在心，那就是：

> **物体能接收（显示）和投射（向其他物体投射）阴影是两件需要单独考虑的问题。**

这两件事的机制是不同的，属于两个不同的步骤。#pragma multi_compile fwdadd_fullshadows影响的是物体接收和显示阴影的这一步骤，而不会影响向其他物体投射阴影的步骤。具体你可以再参考[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/49)。

**Comment by lic1227** [comment]
哦谢谢！看来我以前没理解透啊~
