### ISSUE TITLE
关于 第八章中渲染Kot的中开启深度写入的方式

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#80]
开启深度写入能解决内部遮挡的一些问题，但是这样内部遮挡部分(比如两个节相交部分)看起来就不透明了，请问如何在解决遮挡的同时又能透明，就像现实中真的透明物体那样？

我尝试写入z的同时关闭深度测试，这样能解决遮挡部分的透明，但是别的不透明物体也能透过这个物体~

**Comment by candycat1992** [comment]
使用传统透明度混合的方法或者pre-z这种方法永远会有得不到正确效果的情况，这是它们的机制所限…搞不出新的花样了。如果需要健壮性更好的透明效果同时可以承受一定的性能耗损可以使用[Order-Independent Transparency（OIT）](https://en.wikipedia.org/wiki/Order-independent_transparency)相关技术，但是一般也有层数限制。你可以参考[这个issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/55)以及我的另一个[OIT_Lab项目](https://github.com/candycat1992/OIT_Lab)。

**Comment by lic1227** [comment]
谢谢谢！！

**Comment by lic1227** [comment]
顺便问下pre-z是啥？是指先开一个pass写入深度吗？

**Comment by candycat1992** [comment]
对的~

**Comment by TableBreaker** [comment]
请问在这里先开一个pass写深度和在原来的pass里写深度的区别在哪里呢，在单独的pass里写入深度之后，该物体之后渲染的半透明物体也是无法通过深度测试的吧，这里有点不太理解，想请教下

**Comment by candycat1992** [comment]
@TableBreaker 你说的没错，如果该物体背后还有其他物体在它后面渲染的话，这些物体无法通过深度测试，不会渲染出来。这种Z-Pre Pass与直接开启ZWrite的不同之处在于，这个物体本身内部的渲染效果。如果直接在同一个Pass里开启ZWrite，由于该物体内部三角面片的渲染顺序无法保证，因此会出现书里P171图8.10所看到的那种效果，即内部的渲染效果出现明显错乱。如果我们使用Z-Pre Pass的话，由于第一个Pass只渲染深度，不输出颜色，等到第二个Pass渲染的时候，无论三角面片的渲染顺序如何，只有那些在最前面的fragments才能通过深度测试，实现颜色混合，而该物体内部的那些fragments则不会渲染出来，从而避免出现内部混合混乱的结果。

这种Z-Pre Pass的半透明效果主要用于一些复杂物体的淡入淡出，是想要避免在淡入淡出过程中让玩家看到物体内部复杂错乱的半透明效果。而传统的透明混合应用的物体大多比较简单，是会避免出现复杂的内部遮挡关系的。

其实遇到这种不理解的地方，自己动手实践一下看看效果就很容易发现差别。比如我们有个场景是：
![qq 20170901120830](https://user-images.githubusercontent.com/5907064/29956025-c7c50124-8f16-11e7-9aee-410aa5a6c26b.png)
传统透明混合、直接开启深度写入的透明混合和使用Z-Pre Pass的透明混合效果如下：
![qq 20170901095417](https://user-images.githubusercontent.com/5907064/29956076-219037a0-8f17-11e7-8eb9-5bf6dae862f7.jpg)
![qq 201709010954171](https://user-images.githubusercontent.com/5907064/29956061-0dfa6d0a-8f17-11e7-8662-688d8e3b08aa.jpg)
![qq 201709010954172](https://user-images.githubusercontent.com/5907064/29956079-26c6d3aa-8f17-11e7-87b6-7cdd8c15a134.jpg)

你可以分析下是如何出现上面这些效果的。

**Comment by TableBreaker** [comment]
明白了~  多谢指导！
