### ISSUE TITLE
P150页构建 (binormal)副切线时通过发现和切线的叉乘为什么还要乘以个w分量？是因为mirror的存在吗？

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#81]
说上P151页解释说切线和发现方向都垂直的方向有两个，但是根据右手定则cross应该能确定结果向量的朝向吧？为啥还要再乘以一个w？听别人说是因为建模的时候回把法线镜像？

**Comment by candycat1992** [comment]
你可以参考[之前的issue](https://github.com/candycat1992/Unity_Shaders_Book/issues/32)。

**Comment by lolanto** [comment]
这个问题也困扰了我很久，这是[我的猜测](http://blog.luyonghao.top/unity-wei-shi-yao-ji-suan-fu-qie-xian-yao-cheng-yi-tangent-w/)。图形学新手，求指点。另外，作者的书不错，Unity太坑，说明文档太少
