### ISSUE TITLE
10.3 节的程序纹理显示不了

### ISSUE THREAD

**Issue by tvrcaiyy** [candycat1992/Unity_Shaders_Book#83]
![sdf1](https://cloud.githubusercontent.com/assets/17244980/22640271/d74b66a6-ec8c-11e6-84dd-ffc1f13f2889.png)
![sdf2](https://cloud.githubusercontent.com/assets/17244980/22640295/f566696a-ec8c-11e6-9d88-2df0f8cd4ab7.png)

如图，刚把脚本挂上去的时候是正常的，保存下场景，材质里的纹理就丢失了，请问下这个是舒格以原因造成的？

**Comment by candycat1992** [comment]
保存场景的时候Unity会清理一次资源，这个例子里面的程序纹理就会被删掉，你再运行下程序就好啦

**Comment by tvrcaiyy** [comment]
谢谢
