### ISSUE TITLE
P83页 4.6.8 第三段第二三行的问题

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#84]
你好！书上写到 齐次坐标系的w分量去**除以**x,y,z
请问是不是应该是 除 啊？

**Comment by hungry0** [comment]
今天我也发现这个问题了，不过感觉这无伤大雅，理解就可以啦

**Comment by candycat1992** [comment]
你好，的确是我的笔误问题，已经更新到[勘误列表](http://candycat1992.github.io/unity_shaders_book/unity_shaders_book_corrigenda.html)中，感谢反馈！
