### ISSUE TITLE
P223页 中的offset计算是什么原理啊？

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#85]
你好！书中有一行代码
 float2 offset=bump.xy*_Disortion*_RefracTex_TextelSize.xy;

请问这句应该怎么理解？书上说的没看懂。bump不是切线空间的吗？RefracTex_TextelSize和bump相乘是什么意思？两个向量相乘怎么理解为偏移？

请详细说下，谢谢！！

**Comment by candycat1992** [comment]
你可以参考[之前的issue：关于模拟折射的问题请教](https://github.com/candycat1992/Unity_Shaders_Book/issues/64)。

**Comment by lic1227** [comment]
顺便问一句是不是向量直接用 * 相乘就是各个标量相乘然后组成一个新的向量？
例如**a=（x1,y1,z1,w1） b=(x2,y2,z2,w2)**
**a*b=(x1*x2,y1*y2,z1*z2,w1*w2**)?

**Comment by candycat1992** [comment]
对，就是逐分量相乘得到新的向量。
