### ISSUE TITLE
P232 序列帧动画-结果和预期不符Bug

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#86]
要实现的效果应该是从左上角第一个是第一帧，但是当Speed调1时候(降低播放速度)，（随书demo）实际上播放效果是从最底下行开始播放。
请问这是什么原因导致的？谢谢！！

**Comment by lic1227** [comment]
fixed4 frag (v2f i) : SV_Target {
				float time = floor(_Time.y * _Speed);  
				float row = floor(time / _HorizontalAmount);//0
				float column = time - row * _HorizontalAmount;//3
				row+=1;
				half2 uv = i.uv + half2(column, -row);
				uv.x /=  _HorizontalAmount;
				uv.y /= _VerticalAmount;
				
				fixed4 c = tex2D(_MainTex, uv);
				c.rgb *= _Color;
				
				return c;
			}
这个好像可以，row+1

**Comment by candycat1992** [comment]
时间从0开始增长时，一开始的row和column都是0，即取值是从纹理的原点开始的，书中在第七章就说明了在Unity中纹理的原点位置和OpenGL一致，位于纹理的左下角，所以第0行就对应了最底行，并依次向上增加，这并不是bug。

**Comment by lic1227** [comment]
但是这序列帧动画的用法不应该是从左上角第一个依次往后面播放吗？这样不就不对了吗？
把row+1，就能从第一个播放了啊
fixed4 frag (v2f i) : SV_Target {
				float time = floor(_Time.y * _Speed);  
				float row = floor(time / _HorizontalAmount);//0
				float column = time - row * _HorizontalAmount;//3
				row+=1;
				half2 uv = i.uv + half2(column, -row);
				uv.x /=  _HorizontalAmount;
				uv.y /= _VerticalAmount;
				
				fixed4 c = tex2D(_MainTex, uv);
				c.rgb *= _Color;
				
				return c;
			}

**Comment by candycat1992** [comment]
恩呢，你把row+1的话的确可以实现从左上角开始播放。恩，我的看法是，目前书里这种做法适用于类似书里示例的那种火焰图，也就是序列帧动画的最后一行和最上面一行是衔接在一起的，因此即便是从最后一行开始播放再播放第一行也不会有问题。不过的确有需要强制从左上角开始播放的情况，应该在书里面指明会更好。
