### ISSUE TITLE
7.3.2节 中平移矩阵和旋转矩阵是正交矩阵的问题。

### ISSUE THREAD

**Issue by mustbeyouqq** [candycat1992/Unity_Shaders_Book#87]
148页7.2.3节中讲：如果一个变换中仅存在平移和旋转变换，那么这个变换的逆矩阵就等于它的转置矩阵。

心里有个疑问，好像平移矩阵并不是正交矩阵，旋转矩阵和镜像矩阵才是正交矩阵（3D数学基础：图形与游戏开发116页 9.3.2节）。那么平移变换的逆矩阵就不是转置矩阵了。书中说一个变换中仅存在平移和旋转变换，那么这个变换的逆矩阵就等于它的转置矩阵。

刚开始接触图形学，若理解有错误或者不到位请谅解，谢谢。

**Comment by lic1227** [comment]
不是只有镜像和旋转才是，**3D数学基础：图形与游戏开发中说的是“例如”，**你可以看看那本书第八节讲过一个图表，平移矩阵也是正交的

**Comment by mustbeyouqq** [comment]
疏忽了，非常感谢，元宵快乐 :) ！

**Comment by mustbeyouqq** [comment]
@lic1227 您好，书上没有找到平移矩阵是正交矩阵的相关证明。还是有疑惑
1 0 0 2       1 0 0 0            5   6   8   2
0 1 0 3       0 1 0 0    =》  6  10 12  3
0 0 1 4       0 0 1 0            8  12 17  4
0 0 0 1       2 3 4 1            2   3   4   1
前面是一个平移矩阵M，后面是该平移矩阵的逆矩阵MT，但是 M MT != I 呀？我哪里弄错了，谢谢。

**Comment by candycat1992** [comment]
你好，这段话实际上是有问题的，非常抱歉。

@mustbeyouqq 你说得对，平移矩阵并不是正交矩阵，如P63的图表所示，你自己也证明了（其实也很明显它的每一行都不是单位矩阵，我原书这里的确有非常不应该的笔误%>_<%）。原书里面这一段的描述是有问题的，从第六行“在4.6.2节中我们已经知道，如果一个变换中只存在平移和旋转变换……”开始后面的内容需要重新修改，这是一个bug，我之前写的时候没有意识到，非常不好意思。我后来在[issue：【常见问题】关于法线转换的问题（以及在切线空间下计算法线纹理的问题）](https://github.com/candycat1992/Unity_Shaders_Book/issues/45)里给出了如何在切线空间下计算的正确方法。简单来说，其实从切线空间到模型空间的变换会存在旋转和缩放变换（因为是对方向矢量进行变换，因此平移变换在这里可以不用考虑），旋转矩阵是正交矩阵，但缩放矩阵并不是。如果只存在统一缩放，那么我们仍然可以像书中目前所描述的方法直接使用转置矩阵（此时转置矩阵和逆矩阵之间的差别只在于差了一个统一缩放的系数），我们只需要把最后的结果归一化就可以抵消统一缩放的影响。但如果存在非统一缩放，那么我们就不能直接使用转置矩阵来作为逆矩阵了，而需要真的对从模型空间变换到切线空间的矩阵求逆，得到真正的逆矩阵，也就是[issue：【常见问题】关于法线转换的问题（以及在切线空间下计算法线纹理的问题）](https://github.com/candycat1992/Unity_Shaders_Book/issues/45)中的方法。

所以总体来说，书里目前的实现方法仅适用于模型只存在统一缩放的情况，不然就会有视觉问题。如果误导你了我感到非常抱歉……我会在后续的版本里进行订正。

**Comment by mustbeyouqq** [comment]
@candycat1992 乐乐，您好 :）。#45仔细理解过了，心理还存有一个问题没有想明白，忘指教。

        为什么用第二种在世界空间下计算的方式，把法线转换从模型空间转换到世界空间，就不用考虑非统一缩放了（或者说非统一缩放就不会对展示结果造成错误影响了）。忘详述（基础差，怕如果讲解太简略，会理解不了），非常感谢 :)

**Comment by candycat1992** [comment]
在第二种方法里，我们想要把法线空切线空间变换到世界空间，回想第4章空间变换的本质，即如果我们想要把向量从空间A变换到空间B，则需要得到空间A的三个基向量在空间B下的表示，并把这三个基向量依次按列摆放，再与需要进行变换的列向量相乘即可。因此，我们需要得到切线空间的三个基向量在世界空间下的表示，并把它们按列摆放。切线空间下的三个基向量分别是TBN（切线、副切线和法线），我们已知这三个向量在模型空间下的表示，即模型自带的TBN的值。而它们在世界空间下的表示就可以通过把它们从模型空间变换到世界空间即可。切线T的变换直接用UnityObjectToWorldDir(v.tangent.xyz)变换即可，而法线N的变换就需要考虑非统一缩放的影响，如果我们仍然使用UnityObjectToWorldDir(v. normal.xyz)来直接变换法线就会出现变换后的法线不再于三角面垂直的情况，所以由此构建出来的基向量空间也会是有问题的，导致变换后的法线方向也是错误的，你可以参考下图中的第一行的情况。正确的做法是，在变换法线N时使用UnityObjectToWorldNormal(v.normal)来进行变换，即使用逆转置矩阵去将模型法线N从模型空间变换到世界空间，由此我们就可以得到正确的变换，参考下图第二行的情况。

![world_space_normal_transform](https://cloud.githubusercontent.com/assets/5907064/22923450/7f7d5c30-f2dc-11e6-984c-a5bcb65783e8.png)

**Comment by mustbeyouqq** [comment]
@candycat1992 非常感谢，乐乐妹子。主要是没看过UnityCG.cginc里UnityObjectToWorldNormal的实现，不知道这个函数做了逆转置的运算，一直纠结为什么不用对法线做逆转置运算，看来以后得多多思考，多思考应该能发现UnityObjectToWorldNormal肯定里面有做转换。再次感谢。

**Comment by boboEmily** [comment]
想继续上面有关平移矩阵是不是正交矩阵的问题再问一下：
为什么在"3D Math Primer for Graphics and Game Development"这本书里，158页（第二版，英文版）5.7.5节 Orthogonal Transformations讲到：
Translation, rotation, and reflection are the only orthogonal transformations. 呢？
我也觉得平移矩阵不是正交矩阵，所以这句话是这本书的一个bug么？还是我理解的有问题？

**Comment by candycat1992** [comment]
@boboEmily  平移矩阵不是正交矩阵，你可以仔细看上面的讨论，谢谢支持~:)

**Comment by boboEmily** [comment]
这是这个段落的截图：
![translation](https://cloud.githubusercontent.com/assets/10578628/24135131/95d2a932-0dc5-11e7-84ff-0c55af117f5e.png)

**Comment by boboEmily** [comment]
@candycat1992 谢谢你的回复！我理解平移矩阵不是正交矩阵，但是3D Math Primer这本书这段又让我觉得很混乱QAQ所以是3D Math Primer这本书的问题啦？还是我对上面的段落理解有误呢
