### ISSUE TITLE
书上说道延时渲染路径不支持半透明？

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#88]
ProjectSetting中打开了延时渲染，发现半透明仍然可以用，请问不支持具体指哪些？谢谢谢谢！

**Comment by lic1227** [comment]
我看到有一篇文章提到
“  对不透明物体采用延迟渲染，透明物体采用正向渲染，可以解决Alpha Blend的问题（Unity3D采用这种解决方案）。”
这是unity自动处理的吗

**Comment by candycat1992** [comment]
对，不透明对象会渲染到GBuffer里，半透明的物体会使用额外的前向渲染的方法再进行渲染。你要说是自动的吧也不能这么说，要渲染到GBuffer里需要物体使用的Unity Shader定义了延迟渲染所需的Pass（LightMode= Deferred），如果找不到这个Pass就不会渲染到GBuffer。Unity的确是这样的解决方案。
