### ISSUE TITLE
关于第十三章运动模糊用两次矩阵转换的问题

### ISSUE THREAD

**Issue by tvrcaiyy** [candycat1992/Unity_Shaders_Book#89]
你好，书上在处理运动模糊的时候用了两次矩阵转换，有一点不明白，我的理解是：通过对深度纹理的采样得到深度值，用它和纹理坐标构建出顶点当前帧在NDC下的坐标，然后先通过当前帧的VP矩阵的逆矩阵得到世界坐标，再通过和前一帧的VP矩阵相乘得到顶点前一帧在NDC下的坐标，再相减得到速度

问题是为什么不能通过直接存储前一帧在NDC下的坐标，直接和当前帧在NDC下的坐标相减得到速度，而要通过两次转换呢，或者是我的理解有问题？
另 float2 velocity = (currentPos.xy - previousPos.xy) / 2.0f; 这里得到的速度为什么还要除2呢

另外把测试代码放在5.5.0f3版本上运行，模糊的效果非常夸张，第二张是在5.4.1f1版本上运行的，正常
两个测试的条件完全一样，就版本不同
![111233](https://cloud.githubusercontent.com/assets/17244980/22876972/2c1a92de-f20e-11e6-8466-35ad878633b0.png)

![111230](https://cloud.githubusercontent.com/assets/17244980/22876931/ec5022e0-f20d-11e6-87c0-580511a6bb6c.png)

**Comment by candycat1992** [comment]
你所说的“为什么不能通过直接存储前一帧在NDC下的坐标”这一方法你可以自己想一下如何实现，就会发现为什么会是文中的实现方法了。书中的方法只需要保存前一帧的摄像机的一个矩阵即可，而你所说的方法则需要保存当前屏幕空间内所有像素的NDC坐标，这需要单独存储一张RenderTexture，还需要额外的Shader来渲染NDC。实际上，你说的这种思想基本就是Velocity Buffer的想法，这也在GPU Gems3的[Motion Blur](http://http.developer.nvidia.com/GPUGems3/gpugems3_ch27.html)一章中的开头被提到过，你可以参考Unity 5.5新添加的[DepthTextureMode.MotionVectors](https://docs.unity3d.com/ScriptReference/DepthTextureMode.MotionVectors.html)接口来实现这种方法。书中的只存储一个矩阵的做法实现起来更加简单。

至于你说的第二个问题，额我这里的效果都是一致的。如果你确定其他设定都没变（例如Blur Size的值确保是一样的），可以考虑是不是帧率的问题，是否是5.5.0f3下帧率变得过低了。

**Comment by tvrcaiyy** [comment]
float2 velocity = (currentPos.xy - previousPos.xy) / 2.0f; 
这里得到的速度为什么还要除2呢

**Comment by candycat1992** [comment]
不除2也可以，没啥特定的原因，书里除2的原因么是因为我基本就是按照GPU Gems3的[Motion Blur](http://http.developer.nvidia.com/GPUGems3/gpugems3_ch27.html)的原文代码来实现的……

**Comment by tvrcaiyy** [comment]
。。。好的，明白了，非常感谢！！
