### ISSUE TITLE
练习题4.3.3的第7题有疑惑

### ISSUE THREAD

**Issue by CaigerDeng** [candycat1992/Unity_Shaders_Book#9]
在看到“如果该值为负，由左手法则判断可得到3个顶点的顺序是顺时针方向”这里就没有看懂。这里的左手法则是怎么摆弄的，怎么就是顺时针了？人眼方向这个条件是怎么用的？图因为没有旁注，我也没有看懂。希望能得到解答。

**Comment by candycat1992** [comment]
人眼方向的条件就是用来判断是顺时针还是逆时针的。你应用左手法则后，如果结果值的z值为负，说明叉积结果是指向z轴负方向的，如图4.52所示的情况，此时从人眼看过去就是顺时针的排列。图4.52画的就是顺时针的情况，其实逆时针的话他们之间不是图示这种关系，会是类似交换了p1和p2之后的样子，只有这样它们的叉积结果才会为正，而此时从人眼看过去就是逆时针了。

**Comment by CaigerDeng** [comment]
想了有一会，再查了下资料，终于弄懂了。
附上我看到的资料，方便也不清楚这个题目的人参考参考：
[Unity游戏开发]向量在游戏开发中的应用（一）:
http://blog.csdn.net/wenxin2011/article/details/50810102
 [Unity游戏开发]向量在游戏开发中的应用（二）:
http://blog.csdn.net/wenxin2011/article/details/50972976
 [Unity游戏开发]向量在游戏开发中的应用（三）:
http://blog.csdn.net/wenxin2011/article/details/51088236
