### ISSUE TITLE
关于书上的 “8.6.3 常见的混合类型” 的问题

### ISSUE THREAD

**Issue by do-nothing** [candycat1992/Unity_Shaders_Book#90]
P175 
8.6.3 常见的混合类型
柔和相加 与 滤色 两种类型的代码一样，都是 Blend OneMinusDstColor one

这两种类型在计算上没有区别么？

**Comment by candycat1992** [comment]
滤色（Screen）的混合公式在网上很好查，转换过来的确就是Blend OneMinusDstColor One或者Blend One OneMinusSrcColor。柔和相加（Soft Additive）这个模式其实并不常见，我在PS里没有找到类似的混合模式，网上也没有查到什么资料，书里这么写是参考了[Unity的Blend命令文档](https://docs.unity3d.com/Manual/SL-Blend.html)添加上去的，似乎除了官方文档外没有找到其他有利的数学公式支持，所以暂且认为它们就是一样的吧。恩，在之后的版本里会考虑把柔和相加这一个模式给去掉，省得给大家造成迷惑……

参考资料：
[Photoshop的帮助文档：Blending modes](https://helpx.adobe.com/photoshop/using/blending-modes.html)
[Photoshop Blend Modes Explained（包含数学公式）](http://photoblogstop.com/photoshop/photoshop-blend-modes-explained)
[Stackoverflow上的帖子：How does photoshop blend two images together?](http://stackoverflow.com/questions/5919663/how-does-photoshop-blend-two-images-together)
