### ISSUE TITLE
关于书上的反射函数计算的问题

### ISSUE THREAD

**Issue by do-nothing** [candycat1992/Unity_Shaders_Book#93]
P214
顶点计算中的代码：
o.worldRefl = reflect(-o.worldViewDir, o.worldNormal);

reflect 函数的第二个参数应该归一化吧。我这样改了一下：
o.worldRefl = reflect(-o.worldViewDir, o.worldNormal * 100);

发现渲染图中反射的光线发生了变化。（Unity 版本：Unity 5.4.0f3 (64-bit)）

这个茶壶没有发生缩放变形，所以这个例子中可以不归一化法线变量。我是看书上在计算折射（P216）时，强调了一下第二个参数法线方向需要归一化的，所以好奇这两个内置函数的算法，才问了这个龟毛的问题。

感谢你在我上一个问题 “常见的混合类型” 给出的详细回答以及参考资料。我想了解一下 Shader 内置函数的具体实现方式，不知到可以从哪些资料中获取，求推荐。

**Comment by candycat1992** [comment]
这个例子里也是归一化后的法线变量，因为之前的代码有o.worldNormal = UnityObjectToWorldNormal(v.normal)，Unity的内置函数UnityObjectToWorldNormal已经做过归一化了。如果你是指reflect的实现的话，书里提到过这是Cg的函数，你可以直接搜Cg的reflect函数就可以找到文档。
