### ISSUE TITLE
书上P254页的二维高斯函数函数展开成 两个一维数组的原理是什么

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#94]
我看水平的权数组是每列的和，垂直的权数组的是水平的和，请问这个是什么原理？能提供这个优化的推导过程吗？网上都搜不到。。。万分感谢

**Comment by candycat1992** [comment]
这是由高斯函数的数学定义所决定的性质，额推导的话就是一个步骤，简单而言就是G(x, y) = G(x)*G(y)，因为幂数的加可以变成一个乘法。

参考资料：
* [Gaussian blur的Wiki](https://en.wikipedia.org/wiki/Gaussian_blur)
* 《Real-time Rendering》的10.9节
* [Efficient Gaussian blur with linear sampling](http://rastergrid.com/blog/2010/09/efficient-gaussian-blur-with-linear-sampling/?utm_source=tuicool&utm_medium=referral)
* [GPU Gems的Chapter 21. Real-Time Glow](http://http.developer.nvidia.com/GPUGems/gpugems_ch21.html)
