### ISSUE TITLE
关于第八章alpha blend的疑问

### ISSUE THREAD

**Issue by Wangsh09** [candycat1992/Unity_Shaders_Book#98]
作者你好~
	读了你的书，受益匪浅~
	关于alpha blend要求关闭深度写入的问题，有一点小疑问。
	关闭深度写入的目的：是以防在该物件被绘制之后，又绘制了在该物件后面的物体，结果被深度测试剔除掉了。
	然而alpha blend要求的绘制顺序是：
	1.先绘制不透明的，2.绘制其他在该物件后面的半透明的物体。
	那么，我觉得，其实是否关闭深度写入，都没有关系呢。因为不会在该物件被绘制之后，绘制该物件后面的物件。
	不知我想的是否正确~

**Comment by candycat1992** [comment]
你好，你的理解是有问题问题的。是先绘制 _所有_ 的不透明物体，再按照从后往前的顺序绘制 _所有_ 半透明物体。你可以参考之前的issue：[关于8.1开篇zwrite关闭的问题](https://github.com/candycat1992/Unity_Shaders_Book/issues/22)。

**Comment by Wangsh09** [comment]
嗯~多谢！我理解了~
