### ISSUE TITLE
在运动模糊特效代码里为什么要使用RenderTexture.MarkRestoreExpected()

### ISSUE THREAD

**Issue by lic1227** [candycat1992/Unity_Shaders_Book#99]
这个代表什么意思？为什么要恢复rendertexture？麻烦讲解下，谢谢谢！

**Comment by lic1227** [comment]
对了还有shader里面写的
	Blend SrcAlpha OneMinusSrcAlpha
	ColorMask RGB

这是什么意思？为什么输出掩码只有RGB还是用了混合？怎么理解？
我实际把ColorMask RGB注释掉效果也不影响？很困惑。。。

**Comment by candycat1992** [comment]
你好，你可以参考之前的issue：[关于12章运动模糊问题](https://github.com/candycat1992/Unity_Shaders_Book/issues/51)

**Comment by lic1227** [comment]
好的谢谢
